Add networking sections content
systems-cs-pub-ro/uso-lab-book pull request #12
Opened 2020-08-11 16:59 UTC by Sergiu121

Acest Pull Request este Work In Progress. Am adăugat conținut pentru 1/2 din capitole, dar vreau să dau un status report al muncii și să primesc un feedback despre structură și exprimare.

TODO list:

- [ ] adaugă conținut pentru secțiunea de troubleshooting
- [ ] termină conținutul pentru secțiunea de lucru în browser
- [ ] adaugă subtitluri pentru numele exercițiilor
- [ ] formatează corect observațiile
- [ ] completează output-urile comenzilor
- [ ] adaugă demo-uri cu poze pentru controlul la distanță prin GUI
- [ ] adaugă poze pentru secțiunea de lucru în browser
- [ ] spell checking
- [ ] identifică soluție pentru nmcli folosind rețele wireless
- [ ] identifică soluție pentru exercițiul cu TeamViewer

2020-08-11 17:01 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-08-12 08:00 UTC, CostinCarabas commented on chapters/net/services.rst
> +installer-ul unui joc nu poate să fie rulat din linie de comandă.
s/rulat/executat/g

2020-08-12 08:00 UTC, CostinCarabas commented on chapters/net/services.rst
> +Controlul aplicațiilor se poate reduce la doua probleme:
s/doua/două/g

2020-08-12 08:01 UTC, CostinCarabas commented on chapters/net/services.rst
> +transferul datelor care ar fi afișate pe stația pe care rulează serverul pe
s/rulează/funcționează/g
s/rulează/se află/g

2020-08-12 08:02 UTC, CostinCarabas commented on chapters/net/services.rst
> +transferul datelor care ar fi afișate pe stația pe care rulează serverul pe
E puțin ambiguă ultima parte a propoziției.

2020-08-12 08:03 UTC, CostinCarabas commented on chapters/net/services.rst
> +protocol care nu este menit pentru trasfer de date sensibile la latență, cum
s/trasfer/transfer/g

2020-08-12 08:04 UTC, CostinCarabas commented on chapters/net/services.rst
> +latență, cum ar fi chituri de instalare ale programelor, această metodă este
**chituri de instalare** este corect?
Poate mai bine pui **kit-uri de instalare** sau **pachete de instalare**.

2020-08-12 08:05 UTC, CostinCarabas commented on chapters/net/services.rst
> +autentificarea la o mașină folosind un cod.
**cod** este ambiguu. Ce zici de: **cod de caractere** sau **înșiruire de caractere**?

2020-08-12 08:06 UTC, CostinCarabas commented on chapters/net/services.rst
> +VPN-urile sunt aplicațiile care permit creare rețelelor de calculatoare în
s/creare/crearea/g

2020-08-12 08:07 UTC, CostinCarabas commented on chapters/net/services.rst
> +<TODO> sunt foarte similare. Asta înseamnă ca cele două stații sunt acum în
s/ca/că/g

2020-08-12 08:08 UTC, CostinCarabas commented on chapters/net/services.rst
> +Pentru a verifica că drumul pachetului chiar trece prin VPN, rulăm comanda
s/rulăm/executăm/g

2020-08-12 08:08 UTC, CostinCarabas commented on chapters/net/services.rst
> +interfața eth0 ci trec prin interața virtuală, ajung la serverul VPN în pasul
s/interața/interfața/g

2020-08-12 08:09 UTC, CostinCarabas commented on chapters/net/services.rst
> +VPN, deoarece pachetele au fost trimise în Internet începând de la serverul DE
Sunt 2 *deoarece*-uri și este greu de urmărit. Poți sparge în 2 propoziția?

2020-08-12 10:01 UTC, razvand commented on chapters/net/services.rst
> +Descărcați fișierul <insert link>. Observați că descărcarea nu funcționează,
Folosit `..note` pentru hint.

2020-08-12 10:02 UTC, razvand commented on chapters/net/services.rst
> +Pentru a ne conecta la stație este nesar să introducem parola utilizatorului cu
rulează

2020-08-19 11:52 UTC, razvand commented
@Sergiu121 , să folosești o propoziție pe linie, pe moment ai line break-uri.

2020-08-19 12:05 UTC, razvand requested changes
Am recenzat restul din pull request.

2020-08-19 12:05 UTC, razvand commented on chapters/net/services.rst
>  a. Controlul unei ferestre la distanţă
Nu începi cu asta. începi cu ceva simplu, precum VNC sau altceva. SSH X Forwarding e prea greu și complicat de folosit.

Cel mai bine începi, de fapt, cu TeamViewer sau Askdesk. Nimeni întreg la cap pe un use case normal nu ar folosi SSH X Forwarding. Aia e pentru geekși.

2020-08-19 12:05 UTC, razvand commented on chapters/net/services.rst
> +latență, cum ar fi chituri de instalare ale programelor, această metodă este
kituri

2020-08-19 12:05 UTC, razvand commented on chapters/net/services.rst
> +cum ar fi VNC, sau FreeRDP, dar noi ne vom concentra pe soluția numită
Și TeamViewer e gratis. Poate ai vrut să spui open source.

2020-08-19 12:05 UTC, razvand commented on chapters/net/services.rst
> +VPN-urile sunt aplicațiile care permit creare rețelelor de calculatoare în
VPN nu este o aplicație, este un tip de infrastructură de rețea. De clarificat asta. Și de dezacronimizat VPN. Și de pus o poză cu infrastructura pentru VPN.

Din nou, top-down. Definiția e "down". Începi de la use case, de la nevoie, dă exemplu de situație concretă, arată soluția și spune că se cheamă VPN și apoi definește VPN.

2020-08-19 12:05 UTC, razvand commented on chapters/net/services.rst
> +LAN, putem folosi un VPN, cum ar fi Hamachi, la care se conectează doi
Referință (footnote or otherwise) la Hamachi.

2020-08-19 12:05 UTC, razvand commented on chapters/net/services.rst
> +Pentru a porni VPN-ul, vom folosi openvpn. Rulați următoarea comandă pe ambele
Nu, nu, nu, nu, nu. Nu openvpn, mori cu zile. E prea tehnic, e prea de RL. Trebuie ceva GUI, ceva simplu de folosit.

2020-08-19 12:05 UTC, razvand commented on chapters/net/services.rst
> +.. code-block::
Mi se pare că ai un mindset prea tehnic, mindset potrivit pentru RL, nu pentru USO. Aici e focusul pe "cum fac rapid ceva să-mi meargă" nu pe "cum se întâmplă în spate, de ce merge așa, cum e făcuta asta". Focusul e pe utilizare, nu pe interne, pe funcționalitate, nu pe anatomie.

2020-08-19 15:06 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-09-02 14:49 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-09-07 20:08 UTC, Sergiu121 commented on chapters/net/extra.rst
> +Proxy-ul HTTP este o alternativă a VPN care în loc să tuneleze tot traficul
O vor avea din capitolul de servicii

2020-09-07 21:21 UTC, Sergiu121 commented on chapters/net/extra.rst
> +Aplicația SSH permite configurarea scurtăturilor pentru destinații la care vrem
Cunosc conceptul de SSH de la secțiunea de servicii

2020-09-07 21:28 UTC, Sergiu121 commented on chapters/net/extra.rst
> +Proxy-ul HTTP este o alternativă a VPN care în loc să tuneleze tot traficul
Am adăugat un context despre trecerea peste "filtre de locație".

2020-09-07 21:31 UTC, Sergiu121 commented on chapters/net/extra.rst
> +evităm filtre bazate pe locație.
Sufletul meu vrea să de exemplu concret pornhub, dar revin cu ceva mai SFW.

2020-09-08 06:21 UTC, Sergiu121 commented on chapters/net/extra.rst
> +    student@tom:~$ ssh -o ServerAliveInterval=100 user@statie
După cum am discutat și în call-ul săptămânal, aici am dat un exemplu arbitrar. Am modificat astfel încât să fie direct ce ne intereseaza

2020-09-08 07:50 UTC, Sergiu121 commented on chapters/net/extra.rst
> +mediul grafic parametrii de rulare ai rețelei, cum ar fi serverul DNS folosit.
Învață la capitolul de troubleshooting.

2020-09-08 07:53 UTC, Sergiu121 commented on chapters/net/extra.rst
> +Pentru a vizualiza parametrii de rulare ai unei conexiuni rulăm comanda:
Am avut conversația asta pe slack. Voi lăsa "rulare"

2020-09-08 07:54 UTC, Sergiu121 commented on chapters/net/extra.rst
> +TODO, nu sunt sigur că pot face o infrastructură pentru asta
Subscriu. Voi face doar demo.

2020-09-08 07:57 UTC, Sergiu121 commented on chapters/net/services.rst
>  Servicii şi clienţi de reţea
Nu am folosit concepte de servicii mai avansate de ideea unei aplicații care ascultă pe un port în capitolul de configurarea și diagnosticarea rețelei.

2020-09-08 07:58 UTC, Sergiu121 commented on chapters/net/services.rst
> +Ce înseamnă un serviciu?
Asta era o întrebare retorică pentru mine, atunci când am scris capitolul. Am uitat să o șterg când am dat push.

2020-09-08 08:43 UTC, Sergiu121 commented on chapters/net/services.rst
> +apelează la ele. Serviciile în computer science lucrează folosind paradigma
Am adăugat un context top-down.

2020-09-08 08:45 UTC, Sergiu121 commented on chapters/net/services.rst
> +le folosesc oamenii și pentru a reduce puterea de calcul necesară pentru rularea
Done.

2020-09-08 14:34 UTC, Sergiu121 commented on chapters/net/services.rst
> +OBSERVAȚIE:
Voi face asta odată ce ajung la un format final.

2020-09-08 15:01 UTC, Sergiu121 commented on chapters/net/services.rst
> +Nu sunt accesate doar pagini web folosind clienți web. Putem folosi clienți web
Am reformulat.

2020-09-08 15:03 UTC, Sergiu121 commented on chapters/net/services.rst
> +Descărcați fișierul <insert link>. Observați că descărcarea nu funcționează,
Vezi observația de mai sus.

2020-09-08 15:03 UTC, Sergiu121 commented on chapters/net/services.rst
> +de manual a utilitarului `wget` (`man wget`), pentru a identifica opțiunea
Done.

2020-09-08 15:05 UTC, Sergiu121 commented on chapters/net/services.rst
> +hostname-ul stației la care vrem să ne conectăm.
Au de la DNS, de la secțiunea de troubleshoot.

2020-09-08 15:06 UTC, Sergiu121 commented on chapters/net/services.rst
> +Baby's first SSH
Am modificat

2020-09-08 15:07 UTC, Sergiu121 commented on chapters/net/services.rst
> +specificăm un nume de utilizator valid. Dacă utilizatorul nu există, server-ul
Done.

2020-09-08 15:07 UTC, Sergiu121 commented on chapters/net/services.rst
> +nu va specifica faptul că utilizatorul nu există pe sistem, ci va cere parola
Done.

2020-09-08 15:08 UTC, Sergiu121 commented on chapters/net/services.rst
> +folosim, dar dacă nu este necesar putem să rulăm mai multe comenzi, sau vrem să
Am discutat pe slack că e ok și așa.

2020-09-08 15:08 UTC, Sergiu121 commented on chapters/net/services.rst
> +automatizăm rularea comenzilor pe alte stații putem folosi comanda SSH în felul
Vezi comentariul de mai sus.

2020-09-08 15:09 UTC, Sergiu121 commented on chapters/net/services.rst
> +Rulați comanda <insert comanda> pe stațiile <insert stații> fără să intrați în
Vezi comentariul de mai sus.

2020-09-08 15:35 UTC, Sergiu121 commented on chapters/net/services.rst
> +comandă pe 10 stații. Dacă am folosi autentificare bazată pe parolă fie ar fi
Nu știu cum aș putea să o reformulez, este o frază care argumentează ceva, nu prea am ce să tai/scurtez la ea.

2020-09-08 15:55 UTC, Sergiu121 commented on chapters/net/services.rst
> +
Aici nu aș menționa securitatea conexiunii. Securitatea conexiunii e dată de algoritmul de criptare folosit pe durata conexiunii. Securitatea identității utilizatorului este asigurată câtă vreme utilizatorul nu leakuiește cheia privată.
Am modificat astfel încât să precizez asta.

2020-09-08 15:58 UTC, Sergiu121 commented on chapters/net/services.rst
> +    TODO
Am adăugat această precizare.

2020-09-08 16:00 UTC, Sergiu121 commented on chapters/net/services.rst
> +Generați o nouă cheie SSH de tip ECDSA.
Am discutat și în call despre asta. M-am gândit să pun o cheie ECDSA, deoarece voiam să caute în manual după asta.
Am modificat, astfel încât să fie o cheie RSA.

2020-09-08 16:12 UTC, Sergiu121 commented on chapters/net/services.rst
> +    TODO
Am adăugat un exemplu pentru asta.

2020-09-08 16:14 UTC, Sergiu121 commented on chapters/net/services.rst
> +Trimiterea fișierelor poate fi realizată în orice direcție, de la client la
Am adăugat clarificări pentru asta.

2020-09-08 20:44 UTC, Sergiu121 commented on chapters/net/services.rst
>  a. Controlul unei ferestre la distanţă
Le-am sucit.

2020-09-08 20:45 UTC, Sergiu121 commented on chapters/net/services.rst
> +transferul datelor care ar fi afișate pe stația pe care rulează serverul pe
Am clarificat.

2020-09-08 20:46 UTC, Sergiu121 commented on chapters/net/services.rst
> +latență, cum ar fi chituri de instalare ale programelor, această metodă este
Am corectat.

2020-09-08 20:47 UTC, Sergiu121 commented on chapters/net/services.rst
> +cum ar fi VNC, sau FreeRDP, dar noi ne vom concentra pe soluția numită
Am vrut doar să enumăr niște soluții posibile, ca apoi să o prezint pe cea pe care o folosim noi. Nu e ok așa?

2020-09-08 20:47 UTC, Sergiu121 commented on chapters/net/services.rst
> +autentificarea la o mașină folosind un cod.
Am clarificat.

2020-09-08 20:50 UTC, Sergiu121 commented on chapters/net/services.rst
> +Pentru a porni VPN-ul, vom folosi openvpn. Rulați următoarea comandă pe ambele
E prea tehnică comanda de mai jos?

```sudo openvpn --config PUB-GRID.ovpn```

La ce soluții am mai folosit eu, primeam un config și rulam comanda openvpn + datele mele de autentificare. Ce are?

2020-09-08 20:55 UTC, Sergiu121 commented on chapters/net/services.rst
> +VPN, deoarece pachetele au fost trimise în Internet începând de la serverul DE
A fost o rămășiță a procesului de redactare. Am modificat.

2020-09-16 09:49 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-09-16 19:09 UTC, razvand commented on chapters/net/services.rst
> +cum ar fi VNC, sau FreeRDP, dar noi ne vom concentra pe soluția numită
E OK, doar să exprimi corect gratis vs open source.

2020-09-16 19:10 UTC, razvand commented on chapters/net/services.rst
> +Pentru a porni VPN-ul, vom folosi openvpn. Rulați următoarea comandă pe ambele
Dacă merge pentru un setup existent, OK. Și dacă e ușor de configurat. Altfel, o alternativă GUI e binevenită. Pot fi amândouă, aș prefera GUI cea principală și CLI (`openvpn`) la nice to know.

2020-09-16 20:16 UTC, razvand requested changes
Adaugă recenzie

Îmi place cum arată capitolul și cum e scris. E bine structurat, cantitatea de informații și explicații e cât trebuie. Exprimarea este fluentă, simplă, clară, nepretențioasă. Comenzile sunt utile, fără brizbrizuri.

Trebuie să mai insiști cu exemple și tutoriale, vor avea nevoie studenții.

La secțiunea de SSH cred că ordinea ar trebuie să fie conformă cu dificultatea și nevoia: conexiune folosind comanda ssh cu parolă, copiere folosind scp, conexiune folosind chei, tunel SSH pentru conexiune între două stații din rețele private. Poate aia cu tunel SSH să fie mutată în secțiunea finală ("Funcționalități suplimentare de rețelistică").

Trebuie formatat conținutul:
* pus notes
* folosit double backticks și alte formatări de text
* de scos prefixul din fața titlului secțiunilor

2020-09-16 20:16 UTC, razvand commented on chapters/net/services.rst
> +Există anumite tipuri de aplicații care funcționează în mod implicit și aceste
"în mod implicit în mediul grafic"

2020-09-16 20:16 UTC, razvand commented on chapters/net/services.rst
> +Pentru control complet al sesiunii există o multitudine de soluții, fie gratis,
al unei sesiuni desktop grafice (că nu e clar la ce sesiune te rferi)

2020-09-16 20:16 UTC, razvand commented on chapters/net/services.rst
> +VPN-urile sunt aplicațiile care permit crearea rețelelor de calculatoare în
O aplicație de tip VPN (*Virtual Private Network*) este o aplicație ...

2020-09-16 20:16 UTC, razvand commented on chapters/net/services.rst
> +internet fără ca acestea să fie neapărat în aceeași rețea fizică.
Internet, cu majusculă

2020-09-16 20:16 UTC, razvand commented on chapters/net/services.rst
> +mai departe datele către destinație.
Ai nevoie de o diagramă aici.

2020-09-16 20:16 UTC, razvand commented on chapters/net/services.rst
> +Identificați adresele IP ale celor stații la care aveți acces.
ale celor ... stații (ai uitat numeraul)

2020-09-16 20:16 UTC, razvand commented on chapters/net/services.rst
> +EXERCIȚIU:
Întâi exemplu, tutorial, chiar 2 exemple, abia apoi exercițiu.

2020-09-16 20:16 UTC, razvand commented on chapters/net/extra.rst
> +practici și cunoștințe extra despre conectarea calculatorului la internet și
Internet (cu majusculă)

2020-09-16 20:16 UTC, razvand commented on chapters/net/extra.rst
> +Vom configura o scurtătura pentru utilitarul ssh folosit de utilizatorul
``ssh``

2020-09-16 20:16 UTC, razvand commented on chapters/net/extra.rst
> +student. Fișierul de configurare se regăsește la calea ``~/.ssh/config``, iar
``student``

2020-09-16 20:16 UTC, razvand commented on chapters/net/extra.rst
> +Pentru modificarea unui atribut al conexiunii folosim comanda `nmcli` în felul
double backtick

2020-09-24 08:11 UTC, CostinCarabas requested changes

2020-09-24 08:11 UTC, CostinCarabas commented on chapters/net/services.rst
> +Funcționalitatea unui VPN este încapsularea datelor trimise de către un
Ai de 3 ori "datelor" în propoziție. Folosește și **acestora** și poți să mai folosești "...criptarea și trimiterea lor/acestora...", "..care le va trimite mai departe către destinație".

2020-09-24 08:11 UTC, CostinCarabas commented on chapters/net/services.rst
> +adică stația de pe care se trimit datele. Astfel, datele nu mai pot fi văzute de
"Astfel, **acestea**" ca să eviți repetiția.

2020-09-24 08:11 UTC, CostinCarabas commented on chapters/net/browser.rst
> +Browserul este format dintr-o fereastră care conține bara cu taburi, bara cu
Ar fi mișto să pui și în poză niște săgeți sau cercuri cu culori diferite și referi în textul de sub poză.

2020-09-24 08:11 UTC, CostinCarabas commented on chapters/net/browser.rst
>     Using too many tabs kills the RAM
Schimbi în română?

2020-09-27 08:15 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Primul nivel cu care noi interacționăm este nivelul fizic. Nivelul fizic este
O sa adaug mai mult pe parea de motivatie la aceasta sub-sectiune.

In experienta mea, majoritatea timpului problemele de conexiune la net incep de la a verifica daca cablul este bagat. De multe ori de la asta e.

2020-09-27 08:55 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Dacă acestea nu sunt aprinse, atunci nu vom avea conectivitate la rețea.
Are sens. Voi pune un GIF.

2020-09-27 09:05 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +În cadrul Linux numim interfață de rețea o placă de rețea.
Am modificat.

2020-09-27 10:08 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +parametrii săi de rulate.
MTU si alte chestii de genul. Am zis sa nu insist pe ele. Voi mentiona ca acestia nu sunt importanti pentru noi.

2020-09-27 10:08 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Starea fiecărei interfețe de rețea este reprezentată pe câte o linie împreună cu
Am adăugat o clarificare. Este ok acum?

2020-09-27 10:13 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Le vom arăta cum să se conecteze la o rețea folosind interfaţa vizuală a unui
Sa o transform intr-o subsectiune de sine statatoare, adica cu ``-`` in loc de ``^``

2020-09-27 13:14 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Pentru conectarea la Internet între stații este nevoie să identificăm stațiile.
Mi se pare ca daca incep asa intru prea mult in "Dar de ce e asa? Dar care e tara/orasul?". @razvand  ce parere ai?

2020-09-27 13:19 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Porniți interfața eno2.
E mai bine acum?

2020-09-27 13:33 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +    student@uso:~$ ip address flush eno2
Pentru toate trebuie sudo. Voi modifica in toate propturile si voi lasa acest comentariu deschis pana rezolv.

2020-09-27 13:35 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Configurați adresa IP pe interfața eno3
Sunt suficiente interfete. Trebuie sa le modific numele in enunturi.

2020-09-27 13:36 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +odată ce am obținut o adresă IP de la serverul DHCP:
Am adaugat mai devreme o explicatie.

2020-09-27 14:01 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +RECAPITULARE:
Nu raman asa, le voi modifica cu ceva potrivit. Un subtitlu sau o notita, in functie de caz.

2020-09-27 14:44 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
>  3) Configurarea nivelului Transport
Mi se pare ca mai rau ii aburesc. @razvand ce parere ai?

2020-09-27 14:45 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +    student@uso:~$ dig google.com
Am modificat.

2020-09-27 14:50 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Pentru a trimite mesaje, indiferent de tipul aplicației care primește mesajul folosim comanda `nc` în felul următor
Mi se parea ca e cam in plus in scenariul expus, dar in acelasi timp mi se pare un tool folositor ca sa verifici conectivitatea la o aplicatie. Chiar il folosesc destul de des.
Nu stiu ce modificari as putea sa fac ca sa fie mai practic, dar fara sa fie prea mult.

2020-09-27 19:30 UTC, Sergiu121 commented on chapters/net/services.rst
> +nu avem acces la o interfață GUI, sau încercăm să automatizăm un proces.
Merge exemplul dat?

2020-09-27 19:31 UTC, Sergiu121 commented on chapters/net/services.rst
> +Deschideți în browser pagina web descărcată pentru a vedea conținutul său
Nu, pur si simplu sa dea ``firefox index.html``.

2020-09-27 19:44 UTC, Sergiu121 commented on chapters/net/services.rst
> +acțiune de tip GET, browserul primește ca răspuns o pagină web, în formatul
De acord. Suna mai bine.

2020-09-27 19:55 UTC, Sergiu121 commented on chapters/net/services.rst
> +Căutați în pagina de manual a utilitarului ``wget`` (``man wget``), pentru a
Nu mi se pare ca e ceva vital, era mai mult ideea sa repete ``wget with a twist``. Propun sa il sterg si sa ii pun sa descarce inca ceva.
@CostinCarabas  tu ce parere ai?

2020-09-27 20:46 UTC, Sergiu121 commented on chapters/net/services.rst
> +* *cheia publică*, este o cheie care este copiată pe stația care rulează
Am modificat. Este mai bine?

2020-09-27 20:49 UTC, Sergiu121 commented on chapters/net/services.rst
> +Pentru generarea unei perechi de chei folosim comanda ``ssh-keygen`` în felul
Se aplica in general? E o problema cu formularea asta, sau e doar redundanta?

2020-09-27 20:53 UTC, Sergiu121 commented on chapters/net/services.rst
>  d. Transferul datelor la distanţă
De ce?

2020-09-27 20:59 UTC, Sergiu121 commented on chapters/net/services.rst
> +    student@uso:~$ scp <username>@<stație>:~/file1 .
Am specificat acum in paranteza.

2020-09-27 21:00 UTC, Sergiu121 commented on chapters/net/services.rst
> +EXERCIȚIU:
Inteleg problema si voi face asta, dar vreau sa fac asta pentru mai multe exercitii. Din aces motiv las aceasta conversatie deschisa.

2020-09-27 21:25 UTC, Sergiu121 commented on chapters/net/services.rst
> +Pentru control complet al sesiunii există o multitudine de soluții, fie gratis,
Am taiat expresia. Nu isi avea sensul.

2020-09-27 21:28 UTC, Sergiu121 commented on chapters/net/services.rst
> +protocol care nu este menit pentru transfer de date sensibile la latență, cum
Am inlocuit cu "pentru aplicatii care au nevoie sa fie responsive". Este mai ok?

2020-09-27 21:43 UTC, Sergiu121 commented on chapters/net/services.rst
> +mai departe datele către destinație.
Subscriu. E pe TODO list.

2020-09-27 21:45 UTC, Sergiu121 commented on chapters/net/services.rst
> +EXERCIȚIU:
Mai am de lucru la sectiunea asta odata ce am infrastructura.

2020-09-27 21:56 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-09-28 07:50 UTC, CostinCarabas commented on chapters/net/services.rst
> +Căutați în pagina de manual a utilitarului ``wget`` (``man wget``), pentru a
Înclin spre ce a zis Răzvan. Mi se pare o chestie destul de grea să o facă ei prima oară, fără să fi văzut vreodată.
Cred că e bine ce ai propus tu. Pune-i să descarce ceva ce are **.pdf**. 

O altă variantă ar fi să faci un GIF cu căutarea după autentificare în manual și eventual și execuția comenzii.

2020-09-28 07:54 UTC, CostinCarabas commented on chapters/net/troubleshoot.rst
> +Starea fiecărei interfețe de rețea este reprezentată pe câte o linie împreună cu
Da, super ok.

"parametrii săi de rulate" <- typo cred.
"Singurul șir de caractere care ne este ``state``" -> Pentru un utilizator la început, șir de caractere este abstract; poți folosi **opțiune**. Poți folosi expresia: "O opțiune relevantă este valoarea ``state``"

2020-09-28 09:29 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-09-28 14:38 UTC, razvand commented on chapters/net/troubleshoot.rst
> +Pentru conectarea la Internet între stații este nevoie să identificăm stațiile.
În regulă. E cvasi-evident că e nevoie de adresă. Lasă așa.

2020-09-28 14:41 UTC, razvand commented on chapters/net/troubleshoot.rst
>  3) Configurarea nivelului Transport
E prea complicată o stivă TCP/IP aici. Nu intrăm în asta. Se face la RL.

2020-09-28 14:46 UTC, razvand commented on chapters/net/services.rst
> +* *cheia publică*, este o cheie care este copiată pe stația care rulează
Looks good to me.

2020-09-28 14:54 UTC, razvand commented on chapters/net/services.rst
> +protocol care nu este menit pentru transfer de date sensibile la latență, cum
Mie îmi sună OK.

2020-10-21 23:39 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-21 23:42 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-21 23:52 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-22 07:29 UTC, razvand requested changes
Am recenzat tot conținutul.

E în regulă. Sunt unele exprimări mai informale, le-am raportat. E o idee bună să le internalizezi și pentru alte scrieri sau prelegeri / prezentări.

Am în minte și ce ar trebui să intre în laborator.

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Recapitulare - Instalarea aplicației TeamViewer
De ce se cheamă "Recapitulare"?

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Deasupra cadrului în care apare desktop-ul de la distață apar putoane ce ne
putoane ->butoane

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +permit să închidem conexiune, sau trimiterea de acțiuni și fișiere către
sau să trimitem acțiuni și fișiere

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +permit să închidem conexiune, sau trimiterea de acțiuni și fișiere către
conexiunea

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +conectăm la această stație folosind opțiunea ``-X`` a comenzii ssh.
ssh cu monotype

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Pentru a rula browserul ``firefox`` pe mașina de la adresa ``10.10.10.3``, ne-am
mașina -> sistemu / stația

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +    video pentru aplicații noi pornite.
nou pornite

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Deschideți aplicația ``qbittorrent`` ca utilizatorul ``student`` pe stația
aplicația grafică ... (să fie clar că e cu GUI)

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +O aplicație de tip VPN (Virtual Private Network) este o aplicație care permite
italic la Virtual Private Network

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Primul avantaj al folosirii unui VPN sunt "ascunderea" traficului între client,
sunt -> este

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +mai pot fi văzute de alte entități până când ajung la server-ul VPN.
serverul

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +care se află în rețele private diferite. De exemplu, pentru a juca un joc în
Ei au undeva înțelegerea de rețea privată?

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Recapitulare - Identificarea adreselor IP ale interfețelor
De ce se cheamă recapitulare?

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Recapitulare - Verificarea conexiunii între două stații
De ce se cheamă recapitulare?

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Verificați conectivitatea între cele doua stații folosind IP-urile identificate
două

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Verificați conectivitatea între cele doua stații folosind IP-urile identificate
adresele IP

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +Acesta a fost un demo didactic, dar și în viața de zi cu zi, când ne conectăm la
o demonstrație didactică

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +nu se întâmplă folosind ``openvpn`` ci alte soluții cum ar fi WireGuard sau
, ci

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +nu se întâmplă folosind ``openvpn`` ci alte soluții cum ar fi WireGuard sau
referințe la WireGuard și Cisco AnyConnect

2020-10-22 07:29 UTC, razvand commented on chapters/net/services.rst
> +normal.
Șterge un "în mod normal".

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Aceste exerciții sunt menite să abordeze lucruri care nu sunt neapărat necesare
Nu sunt toate exerciții. Spune "Exercițiile și tutorialele din această secțiune ..."

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Totuși noi ne dorim să accesăm aceste site-uri. Putem identifica din ce țară
De ce ne dorim asta. O dai prea direct. Zi "Presupunem că ne aflăm într-o astfel de situație, în care nu ne putem conecta la un site din locul / rețeaua în care ne aflăm. Sau vrem să ascundem poziția noastră."

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +<https://free-proxy-list.net>`.
Nu e formatat bine URL-ul, sintaxa RST e alta.

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +internet care oferă serviciul de proxying gratis. Putem să obținem o listă cu
Internet

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +internet care oferă serviciul de proxying gratis. Putem să obținem o listă cu
proxy-ing sau proxying, fii consecvent

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Proxy-ul se bazează pe faptul că este un calculator undeva care va primi
există un sistem / stație în Internet

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Odată selectat un server, trebuie să îl setăm în browser. Pentru asta accesăm
configurăm, nu setăm

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +cuvântul cheie ``proxy`` în setările browser-ului:
configurația browserului (fără cratimă)

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Acesta sunt setările implicite pentru folosirea proxy-ului în Mozilla Firefox:
În imaginea de mai jos se găsește configurația implicită ....

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +proxy-urilor și vom introduce adresa proxy-ului selectat împreuna cu portul
împreună

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Folosind site-ul `WhatsMyIP <https://whatsmyip.com/>` vedem că adresa noastră nu
Fomatarea proastă a URL-ului.

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Sunt unele site-uri pe internet să accesăm un număr limitat de articole pe ele.
în Internet

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Funcționalitatea de blocare a conținutului de pe un site până la plata unei sume
Prea lungă fraza

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +*Paywall*-urile se reduc la niște elemente HTML care pot fi șterse din pagină
fără niște

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Pentru ștergerea automată a blocajelor putem folosi `acest
formatare greșită de URL-uri

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +``root`` folosind opțiunea ``-X`` ar fi nevoie să rulăm comanda:
, ar fi

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Tastarea acestei comenzi pentru fiecare conexiune succesivă este ineficientă și
Introducerea acestei comenzi

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +După cum am observat în secțiunea <TODO>, ca să ne copiem singuri cheia publică
referință la secțiune

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +După cum am observat în secțiunea <TODO>, ca să ne copiem singuri cheia publică
"să ne copiem singuri", sună prea informal; pune o exprimare tehnică sau mai formală

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +În această situație putem să configurăm cheia publică folosindu-ne de fișierele
situație,

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Atunci când verifică cheile publice ale utilizatorilor care încearcă să se
Fraza asta e întortocheată și greșită. În authorized_keys sunt cheile publice, nu private.

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +fost adoptat ca serviciu standard pentru gestionarea conexiunilor la Internet
Internet:

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +mediul grafic parametrii de funcționare ai rețelei, cum ar fi serviciul DNS
a rețelei

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Pentru interfețe conectate prin cablu exista doar o singură conexiune în mod
există

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Atributul ``ipv4.dns`` reține date despre DNS-ul care va fi folosit în cadrul
serverul DNS

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +Exercițiu - Setarea DNS-ului permanent folosind ``nmcli``
Configurarea serverului DNS

2020-10-22 07:29 UTC, razvand commented on chapters/net/extra.rst
> +``Wired Connection 1`` să folosească DNS-ul ``8.8.8.8``.
serverul DNS

2020-10-22 08:25 UTC, Sergiu121 commented on chapters/net/browser.rst
> +Pentru instrucțiuni despre folosirea scurtăturilor în browser urmăriți secțiunea
Yep. E ok?

2020-10-22 09:32 UTC, Sergiu121 commented on chapters/net/browser.rst
Ar ma fi de zis doar de password manager, mai am paywall la extra. Sa mai adaug?

2020-10-22 09:52 UTC, Sergiu121 commented on chapters/net/extra.rst
> +Funcționalitatea de blocare a conținutului de pe un site până la plata unei sume
Am taiat. E mai bine?

2020-10-22 09:57 UTC, Sergiu121 commented on chapters/net/extra.rst
> +După cum am observat în secțiunea <TODO>, ca să ne copiem singuri cheia publică
E mai bine? Încă nu am pus referințele. Le voi face pe toate dintr-o bucată

2020-10-22 10:41 UTC, Sergiu121 commented on chapters/net/extra.rst
> +Atunci când verifică cheile publice ale utilizatorilor care încearcă să se
Am modificat.

2020-10-22 11:42 UTC, Sergiu121 commented on chapters/net/services.rst
> +Unde root este numele utilizatorului și 10.10.10.3 este adresa IP, sau
Am scris mai jos, nu e suficient?

2020-10-22 12:39 UTC, Sergiu121 commented on chapters/net/services.rst
> +Recapitulare - Instalarea aplicației TeamViewer
De bou. Am corectat.

2020-10-22 12:40 UTC, Sergiu121 commented on chapters/net/services.rst
> +Recapitulare - Instalarea aplicației TeamViewer
Ba nu. E recapitulare de la instalarea aplicațiilor, acum mi-am amintit. E ca sa iși amintească cum se intaleaza o aplicație de la laboratorul anterior.

2020-10-22 12:47 UTC, Sergiu121 commented on chapters/net/services.rst
> +care se află în rețele private diferite. De exemplu, pentru a juca un joc în
Nu, dar nu stiu cum/unde sa o mai bag.

2020-10-22 12:48 UTC, Sergiu121 commented on chapters/net/services.rst
> +Recapitulare - Identificarea adreselor IP ale interfețelor
Pentru că este un exercițiu de recapitulare pentru ce au facut la o alta sectiune. Sa schimb?

2020-10-22 12:48 UTC, Sergiu121 commented on chapters/net/services.rst
> +Recapitulare - Verificarea conexiunii între două stații
Vezi mai sus.

2020-10-22 13:34 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +.. note::
Sunt comenzi diferite pentru fiecare sub-sectiune, din cauza asta este aici.

2020-10-22 13:37 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +.. note::
Nu îmi este clar cum ar arăta ca footnote. Cu ce să fac legătura din text? Mai degrabă scote note-ul și îl fac parte din enunțul demo-ului.

2020-10-22 13:38 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Exercițiu - Pornirea unei interfețe
@CostinCarabas păreri?

2020-10-22 13:46 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +    mv: cannot move '/etc/resolv.conf.dhclient-new.35' to '/etc/resolv.conf': Device or resource busy
Am adăugat o observație.

2020-10-22 13:52 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +    student@uso:~# ping -c 4 10.10.10.10
Voiam să nu stau sa le explic de Ctrl+c. Am adăugat explicația.

2020-10-22 15:13 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-22 15:39 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-23 07:56 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-26 13:35 UTC, CostinCarabas commented on chapters/net/services.rst
> +Acesta a fost o demonstrație didactică, dar și în viața de zi cu zi, când ne
Acesta -> Aceasta

2020-10-26 13:35 UTC, CostinCarabas commented on chapters/net/extra.rst
> +Sunt unele site-uri pe Internet să accesăm un număr limitat de articole pe ele.
lipsește ceva din propoziția asta.

2020-10-26 13:35 UTC, CostinCarabas commented on chapters/net/extra.rst
> +se numește un *paywall*. *Paywall*-urile sunt foarte agasantă atunci când
agasantă -> agasante

2020-10-26 13:35 UTC, CostinCarabas commented on chapters/net/extra.rst
> +descărcat și instalat în browser de `aici
Am intrat pe link și nu este straight-forward cum să instalez add-on-ul. Poate adaugi detalii despre procesul de instalare.

2020-10-26 20:54 UTC, Sergiu121 commented on chapters/net/extra.rst
> +descărcat și instalat în browser de `aici
Ai intrat pe link-ul de Chrome, sau Firefox? Am văzut acum că nu am dat link-ul către pagina de releases pentru chrome.

2020-10-26 21:15 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Pentru identificarea și repararea problemelor de conectivitate la rețea (sau,
E mai bine acum?

2020-10-26 21:42 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +  format hexazecimal care pot lua valori de la ``0x0000" la ``0xFFFF``.
Decât să îi aburesc cu detalii despre adresele IPv6 am zis ca mai bine tai bucata incompletă și dau un link către wikipedia. E mai bine?

2020-10-26 21:44 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +    mv: cannot move '/etc/resolv.conf.dhclient-new.35' to '/etc/resolv.conf': Device or resource busy
Eu am făcut așa pentru că noi vrem ca ei să urmeze demo-urile pas cu pas și să replicăm ce vor vedea și ei când rulează comanda. @razvand păreri?

2020-10-26 21:46 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Dacă schimbăm adresa DNS-ului cu altă adresă, cum ar fi cea a DNS-ului oferit
Scopul exercițiului este să își reconfigureze DNS-ul când nu merge, nu să obțină o adresă diferită, dar ăsta este un efect ușor de observat. Are sens?

2020-10-26 21:50 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +Atunci când folosim Internetul, ce facem de fapt este că ne conectăm la
E mai bine acum?

2020-10-26 21:52 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +* verificăm dacă putem să ne conectăm la alte calculatoare din aceeași rețea
Cred că mai rău încurcă.

2020-10-26 21:59 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-27 00:14 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-27 07:06 UTC, lizababu commented on chapters/net/troubleshoot.rst
> +    funcționalitate oferită de opțiunea ``-p`` a utilitarului ``netstat``.
reformulează că pare că sudo îți afișează porturile și nu netstat

2020-10-27 08:30 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-27 08:55 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-27 09:26 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-10-28 13:17 UTC, lizababu commented on chapters/net/troubleshoot.rst
> +    297: eth1@if298: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
s/UP/DOWN

2020-10-28 13:17 UTC, lizababu commented on chapters/net/troubleshoot.rst
> +    299: eth2@if300: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
s/UP/DOWN

2020-10-28 13:17 UTC, lizababu commented on chapters/net/troubleshoot.rst
> +    299: eth2@if300: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
s/UP/DOWN

2020-10-28 13:36 UTC, lizababu commented on chapters/net/troubleshoot.rst
> +acesta se află pe linia care conține șirul de caractere ``default``.
nu există linia cu "default" în output

2020-11-07 22:20 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2020-11-16 15:00 UTC, CostinCarabas commented on chapters/net/services.rst
> +    ``~/uso.git/labs/03-user/lab-containers/`` comanzile ``./lab_prepare.sh install vpn``.
comanzile -> comenzile

2020-11-16 15:00 UTC, CostinCarabas commented on chapters/net/services.rst
> +    Pentru a ne conecta la infrastructura pentru această secțiune vom folosi
Pentru a ne conecta la infrastructura necesară acestei secțiuni, vom folosi...

2020-12-01 08:40 UTC, razvand requested changes
Am adăugat recenzie.

Capitolul e foarte bun. Observațiile sunt multe, dar sunt de formă. O să fie țuț după ce le aplici. O să se închine maicile la el.

Să faci formatarea să ai o propoziție pe linie.

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +automatizăm rularea comenzilor pe alte stații putem folosi comanda SSH în felul
comanda `ssh`

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Am rulat comanda ``ip address show`` pentru a afișa setările de rețea pe
de pe stația

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Rulați comanda ``cat /etc/passwd`` pe stația de la IP-ul ``10.10.10.3`` fără să
IP-ul -> adresa IP (că nu suntem țărani)

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +intrați în interfața în linia de comandă de pe stații. Vă veți autentifica
fără "de pe stații"

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +se folosește de protocolul SSH pentru transferul de date între stații, astfel
se folosește de -> folosește

. Astfel, ...

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Pentru descărcarea fișierelor de pe un server folosim comanda ``scp``:
... ca mai jos:

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +``/etc/`` de pe stația ``10.10.10.3`` în directorul curent (``.``).
Adaugă o notă despre importanța folosirii argumentului . (dot), că se mai confundă cu final de frază. Comanda are două argumente: sursă și destinație și, frecvent, destinația este directorul curent.

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +În anumite scenarii ne dorim să evităm introducerea parolei pentru
Nu mi se pare realist scenariul. Mai degrabă insistă că e mai safe, că parolele se uită, sunt notate. Așa nu trebuie să ne face griji, e mai sigur.

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Pentru a trece de această problemă putem să folosim mecanismul de autentificare
problemă,

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +* **cheia publică**, este o cheie care este copiată pe stația unde este rulat
, -> :

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Cele două chei sunt legate matematic, iar posesorul cheii private să se poată
să se poată-> se poate

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +(și protejat) ca orice altă parolă. Este indicat să nu protejați cheia printr-un
Taie partea cu "Este indicat", e nefactuală. Mai bine spune: "Pentru simplitate, nu vom folosi passphrase-uri; în viața de zi cu zi, e indicată folosirea passphrase-urilor în măsura în care le puteți gestiona. Dacă există riscul să le notați pe un suport fizic sau să folosiți passphrase-uri simple, atunci mai degrabă nu folosiți."

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Recapitulare - Instalarea aplicației TeamViewer
Mi se pare că nu se va gândi nimeni la asta. Taie "Recapitulare", nu mi se pare că ajută.

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +să mă conectez. În cazul de față este vorba de un sistem MacOS pe care am rulat
macOS

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Acest mod de transfer nu este rapid, deoarece transferul se face printr-un
, pentru că protocolul este mai lent, pentru că realizează criptarea datelor transferate.

Atât. Restul par cam lucruri subiective sau nefactuale.

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +conectăm la această stație folosind opțiunea ``-X`` a comenzii ``ssh``.
ca în imaginea de mai jos:

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Deschideți aplicația grafică ``qbittorrent`` ca utilizatorul ``student`` pe
Deschideți la distanță ...

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +    Pentru rularea acestui demo rulați în directorul
Pentru acest demo ...

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +adică stația de pe care se trimit datele și serverul VPN-ului. Astfel, acestea nu
date,

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +adică stația de pe care se trimit datele și serverul VPN-ului. Astfel, acestea nu
acestea -> aceste date

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +``tun0`` sunt foarte similare. Asta înseamnă că cele două stații sunt acum în
Asta-> Acest lucru (că nu suntem țărani)

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Observăm că a apărut o nouă interfață de rețea în sistem care nu are o componentă
în sistem -> pe fiecare stație (``tun0``), interfață care nu are un corespondent fizic (o placă de rețea).

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +``openvpn-client2`` folosind adresele configurate pe interfața ``tun0`` de pe
. Folosiția adresele IP configurate pe interfațele ``tun0`` de pe fiecare stație.

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Pentru a verifica că drumul pachetului chiar trece prin VPN, rulăm comanda
Pentru a valida că datele chiar trec prin VPN, ...

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +interfața eth0, ci trec prin interfața ``tun0``, ajung la serverul VPN
``eth0``. Mesajele trec prin ...

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Astfel, un pachet care se va îndrepta spre o destinație, poate să depășească
destinație poate (fără virgulă)

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Astfel, un pachet care se va îndrepta spre o destinație, poate să depășească
Nu folosi cuvântul pachet ca să nu introduci un termen nou și confuzie. Folosește date, mesaje sau informație.

2020-12-01 08:40 UTC, razvand commented on chapters/net/services.rst
> +Aceasta a fost o demonstrație didactică, dar și în viața de zi cu zi, când ne
Mi se pare prea mult precizarea asta, nu văd ce a duce în plus. Nu contează că e cu fișier de configurare. Poți lăsa precizarea legată de WireGuard sau Cisco AnyConnect și că sunt principii similare.

2020-12-27 20:06 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2021-08-01 12:44 UTC, Sergiu121 commented on chapters/net/troubleshoot.rst
> +acesta se află pe linia care conține șirul de caractere ``default``.
Comenzile se rulează pe fizic. Voi adăuga un reminder.

2021-08-01 14:55 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge

2021-08-21 10:29 UTC, merged

2021-08-21 10:29 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/12/merge