Add Application Development content (RO)
systems-cs-pub-ro/uso-lab-book pull request #17
Opened 2020-08-18 21:17 UTC by lizababu

2020-08-18 21:18 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-19 12:39 UTC, razvand requested changes
Adaugă recenzie pentru partea de Git și GitHub

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +În majoritatea proiectelor la care veți lucra pe parcursul carierei voastre nu veți fi singuri.
Folosit persoana 1 plural. Nu aș spune "carieră", că nu e doar de carieră vorba.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +În majoritatea proiectelor la care veți lucra pe parcursul carierei voastre nu veți fi singuri.
De făcut trecerea de la proiecte în general la proiecte software în particular. Nu e clar că te referi la proiecte software și ar fi bine de înțeles că aceleași reguli se aplică și la alte proiecte.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Pentru a putea rezolva problemele de sincronizare între 2 sau mai mulți colegi de echipă care lucrează la același proiect, a fost introdusă noțiunea de **versionarea codului**.
"a fost introdusă" -> "este util să avem o gestiune versionată a codului, adică să avem un istoric de modificări, adică o listă de versiuni."

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Git este utilitarul folosit, iar GitHub este serverul pe care păstrăm repository-ul remote.
serverul și aplicația web care rulează pe acesta

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Similar cu GitHub există și alte platforme precum Bitbucket sau GitLab.
Linkuri la toate (footnote sau altcumva)

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Așadar, până a începe parcurgerea secțiunilor acestui capitol, haideți să ne familiarizăm cu câțiva dintre ei.
Mi se pare cam informal "haideți să".

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Proiectul este stocat într-un **repository**.
repository software

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Inițializarea repository-ului local presupune crearea, în directorul specificat, structura necesară pentru a putea iniția un proiect versionat Git.
a structurii

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +.. note:: În general este bine ca orice director de pe sistemul vostru care conține un proiect Git să aibă extensia ``.git``.
Nu știu dacă asta e o recomandare generală. Ai găsit-o undeva? Adică eu o aplic, dar nu cred că e ceva recomandat de cineva sau care a devenit un fel de best practice.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +.. note:: Să luăm următorul exemplu.
Prea mult "bla bla". Trebuie să fie mai practic materialul, ce ai spus aici e material pentru o carte de curs. Trim it, bagă mai rapid practic. Vezi Git Immersion.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Acum că aveți un cont valid de GitHub putem trece la treabă.
Prea informal.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Primul pas care trebuie făcut este să setați local câteva informații despre voi.
configurati

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +a. Configurarea numelui
Prea mult a și b. Direct comenzile și spus că vom configura nume și e-mail, nu mai decupăm în două subsecțiuni.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Pentru a putea trece la treabă, trebuie mai întâi să creăm un repository în care să lucrăm.
Prea informal.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Pentru acest tutorial recomandăm ca repository-ul să fie privat.
Pot să-l facă privat doar dacă au cont de studenți. Cel mai bine nu intrăm în partea cu privat ci îl lăsăm public, că e cel mai sigur.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +    student@uso:~/my-first-repo.git$  git remote add origin https://github.com/{username}/my-first-repository.git
Spune că `{username}` e numele utilizatorului de pe GitHub.

2020-08-19 12:39 UTC, razvand commented on chapters/app-dev/git-intro.rst
> +Vom detalia în următoarele secțiuni ce este un ``branch`` și de ce acum apare ``HEAD branch`` ca fiind necunoscut (``unknown``).
Poate ar fi bine de pus o diagramă de tip before and after cu cele două repository-uri neconectate, apoi conectate.

2020-08-19 13:30 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +Similar cu GitHub există și alte platforme precum Bitbucket sau GitLab.
Am pus href.

2020-08-19 13:32 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +.. note:: În general este bine ca orice director de pe sistemul vostru care conține un proiect Git să aibă extensia ``.git``.
N-am găsit-o, la tine am văzut-o prima oară, după la Costin și cam atât.

2020-08-19 13:37 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +Vom detalia în următoarele secțiuni ce este un ``branch`` și de ce acum apare ``HEAD branch`` ca fiind necunoscut (``unknown``).
Pun un TODO ca să nu uit, nu o fac acum

2020-08-19 13:42 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +.. note:: Să luăm următorul exemplu.
Am mai tăiat. E ok așa?

2020-08-19 13:48 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-19 14:13 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-19 14:47 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-19 16:42 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-19 22:42 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-20 07:28 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-20 10:31 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-20 10:41 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-25 16:00 UTC, edi33416 commented on chapters/app-dev/git-intro.rst
> +Aici este locul în care veți putea contribuțiile voastre pe GitHub, proiectele la care lucrați, informațiile despre voi pe care le faceți publice.
typo "veți putea contribuțiile voastre"

2020-08-25 16:02 UTC, edi33416 commented on chapters/app-dev/git-intro.rst
> +Acum este momentul în care veți da un nume proiectului vostru, o descriere succintă al acestuia și veți putea decide dacă să fie public (vizibil tuturor utilizatorilor) sau privat (vizibil doar pentr
s/al acestuia/a acestuia/g

2020-08-25 16:03 UTC, edi33416 commented on chapters/app-dev/git-intro.rst
> +Vă va apărea un form similar cu cel din imaginea de mai jos.
s/form/formular/g ?

2020-08-25 16:05 UTC, edi33416 commented on chapters/app-dev/git-intro.rst
> +Vor apărea câteva instrucțiuni pentru crearea unui repository local noi și conectarea celui noi cu cel remote.
s/noi/nou/g

2020-08-25 16:12 UTC, edi33416 commented on chapters/app-dev/git-first-commit.rst
> +.. admonition:: Example
Exemplu

2020-08-25 16:47 UTC, edi33416 commented on chapters/app-dev/git-first-commit.rst
> +    În general, acesta va lua ultima versiune a codului sursă și va începe să facă modificări pe acesta.
modificări pe aceasta?  Deoarece este vorba despre ultima versiune

2020-08-25 16:48 UTC, edi33416 commented on chapters/app-dev/git-first-commit.rst
> +    Așadar putem spune că acest colaborator **lucrează pe branch-ul master**.
De pus o notă undeva că este bad-practice să lucrezi direct pe **master** și că nu se practică

2020-08-25 16:50 UTC, edi33416 commented on chapters/app-dev/git-first-commit.rst
> +În acel moment, branch-ul master este actualizat astfel încât cea mai nouă versiune de cod este cea modificată de cel care a efectuat primul un commit.
branch-ul master remote

2020-08-25 16:51 UTC, edi33416 commented on chapters/app-dev/git-first-commit.rst
> +La momentul ``T+x``, celălalt colaborator publică și el schimbările sale și acum branch-ul master va referi codul sursă ce conține schimbările aduse de cel de-al doilea commit.
Între T și T+x, al doilea trebuie să tragă modificările de pe masterul remote. Altfel o să crape cu o chestie de genul "local master is one commit behind and one commit ahead of remote master"

2020-08-25 16:54 UTC, edi33416 commented on chapters/app-dev/git-first-commit.rst
> +Branch-uri secundare
Cred că în subsecțiunea asta poți să menționezi că nu se lucrează pe master, cum ziceam mai sus

2020-08-25 20:02 UTC, razvand requested changes
Add review

2020-08-25 20:02 UTC, razvand commented on chapters/app-dev/git-more-commits.rst
> +Pentru a depăși această situație, folosim opțiunea ``--force`` a lui ``git push``.
Fără --force, e prea bad habit centric.

2020-08-25 20:02 UTC, razvand commented on chapters/app-dev/git-more-commits.rst
> +Operația merge dintre un branch secundar și master
Scoate conflictele. Le pui altundeva dacă vrei, dar nu aici. Poate la o secțiune bonus.

2020-08-26 16:08 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-08-28 13:14 UTC, edi33416 requested changes
Am terminat de recenzat versiunea actuală

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +          Pentru a schimba setarea implicită urmați tutorialul de `aici <https://help.github.jp/enterprise/2.11/user/articles/associating-text-editors-with-git/>`_.
Nu mai bine le dai tu direct comanda `git config --global core.editor "C:/Users/_USERNAME_/AppData/Local/atom/app-_VERSION_/atom.exe"` actualizată pentru `nano` ?

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +Pentru a depăși această situație, folosim opțiunea ``--force`` a lui ``git push``.
De acord. Singurul caz în care văd ok să spui de `--force` este dacă vorbești despre `rebase`, altfel cred că este prea mult

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +             Implicit pe branch-ul ``master`` se preferă **evitarea folosirii** acestei opțiuni.
**NU** se lucrează pe master :))

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +În acest moment, outputul comenzii ``git log`` ne arată că avem 3 commit-uri, toate publicate.
s/commit-uri/commituri/g

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +În acest moment, outputul comenzii ``git log`` ne arată că avem 3 commit-uri, toate publicate.
nu așa era regula?

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +Salvăm fișierul.
folosind combinația de taste `Esc+:+w+Enter`

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +          Pentru a modifica textul apăsați mai întâi tasta ``i``, faceți modificările necesare, după care apăsați ``Esc+w+q`` și apăsați tasta enter.
s/Esc+w+q/Esc+:+w+q/g ai mâncat **:** și o să își dea pumni în cap ca să iasă din vim.

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +Operația merge dintre un branch secundar și master
Da, conflicte la bonus. S-au adunat deja mult prea multe concepte

2020-08-28 13:14 UTC, edi33416 commented on chapters/app-dev/git-more-commits.rst
> +    student@uso:~/my-first-repository$ git commit -m "Merge branch my-new-branch into master"
Pune un `git log` între `commit` și `push`

2020-09-01 08:58 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +    student@uso:~$ git config --global user.name "Prenume Nume"
poate un note? pare mult, @razvand tu ce zici?

2020-09-01 11:00 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +Următorul pas este de a inițializa repository-ul folosind opțiunea ``init``. Observați că se crează directorul ``.git`` în directorul nostru.
le-am făcut

2020-09-02 12:03 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +    student@uso:~$ git config --global user.email "adresa_de_email@email.com"
era "email" nu "gmail", dar cred că am văzut mult mai des "example", am schimbat

2020-09-02 14:35 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Problema este rezolvată, însă ce se întâmplă dacă al doilea commit nu este tocmai în regulă, iar primul da?
cumva trebuia să sugerez că pe branch-ul master am dat push la ceva bun, după vine al doilea băiețaș care dă push pe master cu ceva care n-a fost recenzat și acum pe master avem ceva ce nu vrem și aici voiam să accentuez nevoia folosirii mai multor branch-uri: să păstrăm masterul bun mereu, iar pe restul să le integrăm în master doar dacă se ajunge la concluzia că e totul în regulă

2020-09-02 14:44 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +    student@uso:~/my-first-repository$ echo "# My first project ever" >> README.md
Trebuie să mă uit/să vorbesc cu Costin. Aș zice că da, discută el asta.

2020-09-02 14:59 UTC, lizababu commented on chapters/app-dev/git-more-commits.rst
> +.. figure:: ./img/GitHub-branches.png
Mamă, se cheamă fișierul "Github-branched.png" în loc de "GitHub-branches". Am modificat

2020-09-04 13:25 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-07 15:49 UTC, razvand requested changes
Am recenzat secțiunea `git-first-pull-request.html`.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** Verificați istoricul de commituri din acest repository.
Nu-l pune exercițiu. Spune-le să dea ``git log``. Și explică ce însemnă istoricul. Și spune-le că pot vedea asta și pe GitHub.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** Creați un nou repository pe contul vostru de GitHub intitulat ``my-second-repository``.
Evident, îi dai un nume ca lumea nu ``my-second-repository``.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Clonarea repository-ului
Înainte să începi secțiunea asta, sumarizează-i cititorului pașii pe care-i urmezi. Spune
"""
Ca să avem o contribuție prin Pull Request în mod uzual se urmează pașii:
1. Se realizează un fork sau o clonă a repository-ului.
2. Creăm un branch nou.
3. Realizăm push pe noul branch.
4. Creăm un PR în interfața GitHub.

Ulterior, un maintainer al repository-ului va recenza PR-ul. Dacă e nevoie de modificări, vom face actualizări pe care le vom adăuga (push) din nou în branch-ul nou creat, PR-ul fiind actualizat. După un număr dat de iterații, PR-ul va fi definitivat. Atunci maintainerul va integra branch-ul în master (merge).
"""

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Crearea unui commit de pe branch-ul master
De ce complici lucrurile? Întâi pune-i să facă cap coadă un pull request. Du-i de mânuță. Apoi faci exerciții similare, repetitiv, de exersat. Secțiunea asta ar merge mai încolo ca o formă de exersare. Pentru început, doar tutorial, duși de mânuță.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** Creați un branch numit ``awesome-feature-branch``.
Aș face doar tutoriale aici, nu aș pune exerciții. Alea mai târziu.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** Modificați de pe acest branch titlul fișierului README în ``# Greatest titles of them all``.
Mutat la sfârșit pentru un exercițiu, de exersat lucrul cu Pull Request-uri și cu Git. Acum doar tutorial, ținuți de mânuță până fac primul pull request.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +După publicarea schimbărilor anterioare, intrăm pe GitHub.
Vezi că apare un link când dai push la un branch nou. Ăla e direct linkul la PR. Aș spune de astă până la interfața GitHub cu ``Compare & pull request``.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Explicăm semnificația celor mai importante componente prezente în imagine.
Mai jos ...

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** Scrieți un comentariu în căsuța de text în care să descrieți ce modificări aduceți repository-ului prin acest PR.
La final. Aici ținuți de mânuță.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Touși, este bine de știut că putem schimba acest branch prin apăsarea butonului ``base: master`` din imaginea de mai jos.
Pune propoziția asta cu ..note:: în RST, că nu e ceva central.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Recenzii și recenzori
Recenzenți e mai potrivit decât recenzori: https://dexonline.ro/definitie/recenzent

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Conflicte
E prea mult. Asta merge la final de tot. Poate chiar scoți secțiunea asta.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Noi commituri pe același PR
OK, toată partea de conflicte și --force și restul e extra la extra. E bine că ai făcut-o dar e peste nivelul de baza.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** cum că am înțeles componentele unui Pull Request, îl putem crea.
Acum

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Putem crea commituri noi complet separate, iar acest lucru îl facem trecând prin pașii deja învățați, sau putem adăuga noi schimbări la **același commit**.
Nu îmbina lucrurile. Commituri noi e un subiect, commituri actualizate (``--amend``) e alt subiect. Keep it separated, că e greu de priceput altfel.

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Când facem acest lucru se va deschide un fișier în Vim care conține pe prima linie mesajul de commit.
în editorul sistemului (poate să nu fie Vim)

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Acest lucru se întămplă deoarece commitul de pe GitHub nu mai corespunde cu commitul local.
nu mai corespunde commitului local (să nu apară "cu co").

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Inspectăm istoricul de commituri și vede că nu a fost creat un commit nou pentru această schimbare.
vedem

2020-09-07 15:49 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Avem trei posibilități prin care să efectuăm un ``merge`` din interfața web Github.
Nu, nu, nu, nu , nu. E prea mult cu tipurile de merge. Taie asta.

2020-09-08 15:02 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +De asemenea, este indicat ca numele repository-ului să descrie bine proiectul.
pun TODO să modific peste tot când o să fac și noile screenshot-uri, dau commitul cu update așa

2020-09-08 15:21 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +Dacă aveți deja un cont pe GitHub puteți trece la subsecțiunea următoare.
TODO

2020-09-08 15:23 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +Acest lucru este acoperit în secțiunile următoare.
TODO

2020-09-08 15:29 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-08 17:16 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Adăugarea fișierelor (în staging)
Făcut; am tăiat toată nebunia cu `.`, `-u`. Momentan face "git add <filename>", când va fi nevoie să adauge mai mutle fișiere deodată o să pomenesc de `-A`

2020-09-09 06:56 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +La momentul ``T+x``, celălalt colaborator publică și el schimbările sale și acum branch-ul master va referi codul sursă ce conține schimbările aduse de cel de-al doilea commit.
am tăiat asta de aici, mi s-a părut prea devreme
o pun la branch-uri, dar trebuie șlefuită dacă o pun

2020-09-09 06:56 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-09 06:57 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Problema este rezolvată, însă ce se întâmplă dacă al doilea commit nu este tocmai în regulă, iar primul da?
mutat la branch-uri, urmează commit și cu asta

2020-09-09 06:58 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +
am lăsat asta pe atunci când vor crea un al doilea repo pe GitHub, să vadă și cu și fără, ce zici?

2020-09-09 07:01 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Opțiunea ``.`` va ignora fișierele șterse, iar opțiunea ``-u`` va ignora fișierele nou create.
am șters-o de tot; o să folosesc de -A când o să facă un commit cu mai multe fișiere, acum mi se pare prea multă teorie și prea puțină practică

2020-09-09 07:02 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Prima variantă presupune folosirea opțiunii ``-A`` care va pune în staging toate fișierele modificate (include fișierele deja existente modificate, fișierele nou create și fișierele șterse).
bag un TODO cu git rm, git mv la următoarea secțiune

2020-09-09 07:03 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Această variantă este de folos atunci când avem mai multe fișiere modificate, însă nu vrem să facem un commit decât cu o parte dintre ele.
bag în secțiunea următoare

2020-09-09 07:11 UTC, lizababu commented on chapters/app-dev/git-more-commits.rst
> +Opțiunea ``-b`` urmată de un nume pentru branch specifică faptul că trebuie creat un nou branch cu acel nume.
la secțiunea următoare

2020-09-09 07:14 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-09 11:58 UTC, lizababu commented on chapters/app-dev/git-more-commits.rst
> +**Exercițiu:** Adăugați o nouă linie în fișierul README.md. Puteți folosi orice editor de text doriți.
am șters de tot, dar am ținut cont de asta în alte situații

2020-09-09 11:58 UTC, lizababu commented on chapters/app-dev/git-more-commits.rst
> +Ne amintim de la subsecțiunile anterioare că am salvat modificările aduse asupra fișierului README.md în stivă.
deci?

2020-09-09 12:38 UTC, lizababu commented on chapters/app-dev/git-more-commits.rst
> +Ne amintim de la subsecțiunile anterioare că am salvat modificările aduse asupra fișierului README.md în stivă.
pe Slack pare că rămâne cu stash

2020-09-09 12:45 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** Creați un nou repository pe contul vostru de GitHub intitulat ``my-second-repository``.
pe TODO

2020-09-09 12:51 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-09 12:54 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-09 12:58 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-09 14:16 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Conflicte
tăiat

2020-09-09 14:18 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Crearea unui commit de pe branch-ul master
bineee

2020-09-10 07:42 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +În această secțiune vom crea un nou repository pe GitHub.
am tăiat asta

2020-09-10 07:43 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +          De fapt, în momentul în care un repository este inițializat cu un fișier README, se face un prim commit pentru a adăuga acest fișier în repository.
tăiat

2020-09-10 07:53 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +**Exercițiu:** Modificați de pe acest branch titlul fișierului README în ``# Greatest titles of them all``.
îi pun la sfârșit de tot să facă același lucru (aici vor adăuga algoritmul Bubble Sort - îl dăm noi în carte), să facă același lucru cu un alt algoritm (merge, radix, ce-o fi)

2020-09-10 07:55 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Când facem acest lucru se va deschide un fișier în Vim care conține pe prima linie mesajul de commit.
am tăiat partea asta

2020-09-10 07:55 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Acest lucru se întămplă deoarece commitul de pe GitHub nu mai corespunde cu commitul local.
a dispărut

2020-09-10 07:56 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Inspectăm istoricul de commituri și vede că nu a fost creat un commit nou pentru această schimbare.
tăiat

2020-09-10 13:39 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-10 13:40 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-16 19:02 UTC, razvand requested changes
Adaugă observații și sugestii pe secțiunile despre Git / GitHub

2020-09-17 02:33 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +#. Accesăm linkul ``https://github.com/{username}/my-second-repository/pull/new/bubble-sort-implementation``, unde ``{username}`` este username-ul vostru de pe GitHub.
Adică nimeni nu scrie de mână linkul ăla.

2020-09-17 07:20 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +#. Accesăm linkul ``https://github.com/{username}/my-second-repository/pull/new/bubble-sort-implementation``, unde ``{username}`` este username-ul vostru de pe GitHub.
am precizat mai sus de unde e linkul ăla: de la git push origin <branch>
e și o notă în care se precizează că vom avea nevoie de linkul ăsta, nu îl scrie nimeni de mână

2020-09-17 12:38 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +Primul pas pentru a crea un repository local este să alegeți un director în care să inițializați repository-ul.
De ce-ul este mai sus:

`
Crearea primului repository
---------------------------

Pentru a lucra la un proiect software, creăm un repository.
Vom crea unul pe GitHub, unul local, după care le vom interconecta.
`

La secțiunile `Crearea unui repository gol pe GitHub` și `Crearea unui repository gol local` arăt doar pașii.

2020-09-17 13:00 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +**Repository software**
aș lăsa repository software aici pentru că întreaga secțiune se învârte în jurul repository-urilor, iar pe celelalte le-aș pune acolo unde apare prima dată nevoia de ele

2020-09-17 13:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-17 13:43 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Adăugarea unui fișier README
"Cineva vrea să adauge un fișier README și atunci execută comenzile" nu mi se pare că sugerează "hai fă și tu", e mai mult "dacă vrei să faci"

2020-09-17 14:02 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +**Exercițiu:** Adăugați propoziția "We use a very very cool and new sorting algorithm for arrays named Bubble Sort." pe a doua linie din fișierul ``README.md``.
am schimbat ordinea: mai întâi să creeze un fișier nou, după să modifice README-ul

sunt 3 commituri de făcut la exercițiile astea, cred că e OK pentru acum

2020-09-17 14:17 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-17 14:46 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-17 14:56 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-19 04:28 UTC, razvand requested changes
Am parcurs din nou secțiunile de Git. E în direcția bună, conținutul a fost scuturat. Mai sunt modificări de exprimare și de formă de făcut.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. admonition:: Pași Pull Request
Fă o secțiune numită "Pași Pull Request", nu admonition. Sunt importanți.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  Ca să avem o contribuție prin Pull Request în mod uzual se urmează pașii:
, în mod uzual urmăm pașii:

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +În momentul în care vrem să adăugăm o funcționalitate nouă unui proiect software pe GitHub este recomandat să o facem printr-un **Pull Request**, prescurtat **PR**.
Pune footnote la https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests și/sau https://www.atlassian.com/git/tutorials/making-a-pull-request

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  #. Se realizează un fork sau o clonă a repository-ului. Noi vom folosi în continuare repository-ul TODO.
s/Se realizează/Creăm

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  #. Realizăm commit pe noul branch și îl publicăm pe GitHub.
Creaăm un commit

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +În acest caz, vom lucra pe un nou branch, diferit de branch-ul **master**.
Taie fraza cu "În acest caz", nu aduce nimic în plus.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Creăm un branch numit **bubble-sort-implementation**.
pune două puncte la final

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. note::
Nota asta nu mi se pare relevantă, ditch it.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. note::
Știu deja asta de la secțiunea anterioră, ditch it.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  void swap(int *x, int *y) {
static void swap(...), acolada pe linie nouă, indentare cu Tab-uri

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. note::
Fără note, e în text.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  Trebuie să precizăm acest lucru și în fișierul ``README.md``
s/Trebuie/Vrem

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +
Fără linie liberă, sunt în același paragraf.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Modificăm fișierul ``README.md`` astfel încât el să aibă următorul conținut:
Modificăm fișierul `README.md``ca să aibă conținutul de mai jos:

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  The algoritm is implemented in C.
s/algoritm/algorithm

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. note::
E în text, nu în notă, explicația.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  Așadar, am actualizat și fișierul README în acest caz.
Taie acest paragraf, se știe despre ce este vorba.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Acum trebuie să creăm un **commit** cu schimbările făcute.
"Creăm un commit cu schimbările făcute. Adăugăm întâi modificările în zona de lucru (**staging area**) folosind `git add`:"

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Comitem modificările.
Creăm un commit cu modificările din staging area: (fară alte explicații, știu deja de git commit, știu că trebuie pus mesaj, all good).

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  TODO: adaugă mai mult output ?
Nu mai pune aoutput, eventual pui `[...]`.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. note::
Fără notă, pui în text explicațiile despre git log.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. note::
Fără note. Explică ce înseamnă output-ul și că ăla e link la PR. Vin cam dintr-o dată explicația de mai jos.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +După publicarea schimbărilor anterioare, intrăm pe GitHub.
"accesăm linkul PR-ului:" (și apui aici explicația cu linkul și arați și poza)

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +În imaginea de mai jos vedem o parte a interfeței GitHub în care avem posibilitatea de a lăsa un comentariu în care să descriem (chiar și mai în detaliu decât într-un mesaj de commit) ce schimbări am
avem posibilitatea -> putem

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Modificările pe care le-am făcut urmează a fi integrate într-un branch.
Nu e clar ce urmărești cu fraza asta. Probabil o exprimare "ca să finalizăm PR-ul, modificările din acesta trebuie să fie adăugate într-un branch, cel mai adesea în branch-ul master"

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +În general, branch-ul ``master`` este cel care conține codul sursă actualizat la zi, deci este branch-ul în care se integrează PR-urile.
asta poate dispărea, dacă faci la anterioara comentariile de care am zis

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  Totuși, este bine de știut că putem schimba acest branch prin apăsarea butonului ``base: master`` din imaginea de mai jos.
Fără "Totuși, este bine de știut că"

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Motivul principal pentru introducerea PR-urilor este pentru a putea avea posibilitatea de a primi feedback pe modificările aduse.
Folosirea PR-urilor ne aduce un beneficiu important: putem primi feedback pe modificările aduse.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +În acest tutorial nu vom adăuga recenzenți la PR-ul creat.
Nu înțeleg care este rolul / beneficiul acestei fraze.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Așa cum am precizat în secțiunea TODO, unul sau mai mulți recenzenți se vor ocupa de recenzarea schimbărilor propuse în PR-ul nostru.
Ai mai zis mai sus, cut it.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +  După ce aplicați feedbackul de la recenzenți veți crea un nou commit local pe același branch, în acest caz pe branch-ul **bubble-sort-implementation**.
Nu e clar din forma de exprimare dacă e ceva ce *trebuie* să facă, e ceva ce *pot* să facă, sau e ceva ce *vor* face ducându-i tu de mânuță.

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Apăsăm mai întâi butonul ``Merge pull request`` după care butonul ``Confirm merge`` ca în GIF-ul de mai jos.
ca în GIF-ul de mai jos -> ca în imaginea de mai jos

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Trebuie să ștergem și branch-ul din repository-ul local.
Fără Trebuie să. Spus "Ca să ștergem branch-ul bubble-sort-implementation și din repository-ul local folosim comanda git branch -d:" (incheie cu două puncte)

2020-09-19 04:28 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Creați un nou repository pe GitHub cu numele TODO și clonați-o la voi pe calculator.
Fără clone, nu au făcut până acum nimic de asta. Pune-i ca exercițiu să facă ei un nou PR tot pe repo-ul ăsta.

Pentru fork / clone e nevoie de o secțiune *nouă*.

2020-09-24 07:24 UTC, lizababu commented on chapters/app-dev/git-intro.rst
> +    student@uso:~/my-first-repository$  git remote add origin https://github.com/{username}/my-first-repository.git
ce ochi de vultur

2020-09-24 14:28 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-24 14:36 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-24 14:42 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-24 15:09 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Vom crea commituri pentru fiecare schimbare, după care vom publica commiturile astfel încât schimbările să fie vizibile și pe GitHub.
spread the love

2020-09-24 15:10 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Verificarea stării clonei
nu fac git clone, peste tot fac repo remote+local
o nouă secțiune cu asta ar fi cam ca un pumn în gură, cred

2020-09-24 15:11 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Ne interesează întotdeauna starea clonei pe care lucrăm.
așa?

2020-09-24 15:22 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Verificarea stării clonei
da, are mai mult sens să las clona deoparte, m-am mai gândit

2020-09-24 15:32 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Crearea commitului local cu un mesaj corespunzător
corect, corespunzător
frumos, elegant

2020-09-24 15:35 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +    Trebuie să ne asigurăm că altcineva care va vedea acest mesaj înțelege exact ce schimbări am adus proiectului prin acest commit.
să nu ucizi

2020-09-24 15:37 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Exerciții practice
mult bubble-sort.c la exemplu și celelalte două rămân ca exerciții

2020-09-24 15:41 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Exerciții practice
pot să trec prin el doar printr-un code-block sau e prea mult? nu mai dau explicații acum nu?

2020-09-24 15:43 UTC, razvand commented on chapters/app-dev/git-first-commit.rst
> +Exerciții practice
Mută bubble sort la exemplu. Nu mai dai explicații. Da, printr-un code block, care e alternativa.

2020-09-24 15:58 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +Exerciții practice
printr-un *singur* code-block am vrut să scriu

2020-09-24 16:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-24 16:33 UTC, lizababu commented on chapters/app-dev/git-first-commit.rst
> +        void sort() {
aveam indentare, ok?!

2020-09-24 18:26 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-24 18:35 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-28 08:01 UTC, lizababu commented on chapters/app-dev/git-branches.rst
> +Adăugarea unui fișier .gitignore repository-ului
am lăsat gitignore pe branch separat, rămâne scop didactic
dacă ne răzgândim, tai

2020-09-28 19:08 UTC, lizababu commented on chapters/app-dev/git-branches.rst
> +#. Creați un branch cu numele ``update-gitignore``.
e ok dacă sunt 2 exemple: primul cu fișier nou, al doilea cu modificări, iar exercițiul cu modificări? nu am un exemplu bun pentru creare de alt fișier aici

2020-09-28 19:26 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +
nu e liberă, e doar altă propoziție

2020-09-28 19:32 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +În acest tutorial nu vom adăuga recenzenți la PR-ul creat.
spunem de recenzenți și ca e bine cu feeback cu review cu nebunii și dacă nu zic pare că am uitat să continui toată treaba și trec direct la integrarea PR-ului

2020-09-29 05:59 UTC, razvand commented on chapters/app-dev/git-branches.rst
> +#. Creați un branch cu numele ``update-gitignore``.
Ideal este: exercițiu de adăugare fișier nou, exemplu de adăugare modificare fișier, exercițiu de adăugare modificare fișier.

Dacă nu găsești exercițiu de adăugare de fișier nou, atunci e OK doar cu ultimele două.

2020-09-29 07:39 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +  După ce aplicați feedbackul de la recenzenți veți crea un nou commit local pe același branch, în acest caz pe branch-ul **bubble-sort-implementation**.
cred că mai bine șterg, cu cât citesc cu atât mi se pare mai puțin relevant

2020-09-29 08:19 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Acum vom integra schimbările prin intermediul unui **Pull Request** urmând pașii enumerați mai sus.
am pus pașii într-o subsecțiune și am dat cu ref

2020-09-29 10:01 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Creați un nou repository pe GitHub cu numele TODO și clonați-o la voi pe calculator.
da, așa e
va fi o secțiune nouă cu clone și fork la aia extra (unde vor avea de clonat un repo deja existent care nu e al lor)

2020-09-30 08:20 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-30 08:24 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-09-30 22:01 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +.. note::
Pus ca footnote

2020-09-30 22:02 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Exercițiu practic - Crearea unui PR
Fără "practic".

2020-09-30 22:07 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +    .. code-block:: c
altfel o ia numărătoarea razna + că mi se pare că bara aia ține cumva ordinea acolo (că fișierele alea *-sort.c sunt destul de mari și ocupă mult spațiu pe ecran și se pierde privirea când dai scroll, ai linia aia acolo care te ajută)

2020-09-30 22:07 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +Exerciții practice
de la tine am luat asta!!11

2020-09-30 22:22 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Ca să avem o contribuție prin Pull Request, în mod uzual se urmează pașii:
nici nu e scrisă de tine

2020-10-30 16:27 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +    Noi am pornit de la un repository gol, așadar operațiile ``merge`` și ``pull`` nu au fost necesare.
șterg de tot, că e prea mult oricum

2020-10-30 16:33 UTC, lizababu commented on chapters/app-dev/git-branches.rst
> +Acum avem 2 branch-uri **add-gitignore** și **master** și ne aflăm pe branch-ul **master**.
e mai sus

2020-10-30 16:36 UTC, lizababu commented on chapters/app-dev/git-branches.rst
> +În acestă secțiune vom șterge branch-ul **add-gitignore** atât din repository-ul local cât și din interfața GitHub.
am pus acum mai sus

2020-10-30 16:41 UTC, lizababu commented on chapters/app-dev/git-branches.rst
> +#. Publicați commitul folosind comanda ``git push origin merge-sort-implementation``.
am explicat mai sus..

2020-10-31 08:41 UTC, razvand requested changes
Am recenzat secțiunile legate de build.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/intro.rst
> +Printre IDE-urile preferate se număra: `Microsoft Visual Studio <https://visualstudio.microsoft.com>`_, `Eclipse <https://www.eclipse.org/ide/>`_, `IntelliJ <https://www.jetbrains.com/idea/>`_, `XCod
Nu văd rostul cuvântului "preferate".

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/intro.rst
> +În această carte vom folosi *GNU Nano* ca editor de text principal.
Spune că e un editor CLI și se pornește folosind comanda `nano`. Leagă de capitolul de fișiere, unde a fost întâlnit prima oară.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +În această secțiune vom crea un program care verifică dacă un număr citit de la tastatură este prim sau nu.
Spui ce faci, dar nu spui de ce faci. Încep cu ce urmărești de fapt: să învățăm pașii pentru a compila un program, adică a-l aduce de la cod sursă la executabil. Apoi spui "Pentru aceasta, în secțiunea curentă vom crea ..." Nice and easy.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +Vom scrie într-un nou fișier algoritmul, vom compila codul sursă folosind `compilatorul GNU Compiler Collection <https://gcc.gnu.org>`_ (*GCC*) și vom testa că programul funcționează.
programul care implementează algoritmul

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +Vom scrie într-un nou fișier algoritmul, vom compila codul sursă folosind `compilatorul GNU Compiler Collection <https://gcc.gnu.org>`_ (*GCC*) și vom testa că programul funcționează.
zi doar compilatorul gcc, că îi confuzezi cu GNU Compiler Collection

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +Creăm fișierul ``is-prime.c`` folosind Nano, ca în imaginea de mai jos:
Invers. Faci în ordinea asta:
* spui ce vrei să faci (crearea fișierului)
* spui ce e de făcut: copy paste codul sursă de mai jos în nano
* apoi arăți efectiv cum faci, adică adaugi GIF-ul

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +Compilăm codul sursă pe care l-am scris în fișierul ``is-prime.c`` pentru a obține un program pe care putem să îl rulăm pe sistemul nostru.
Iar spui ce faci, nu ce urmărești. Întâi spune care e finalitatea, obiectivul, apoi spui ce faci. Lucrează la mindset-ul ăsta: "Întâi spun ce vreau să obțin, apoi spun cum ajung acolo." Chiar dacă ambele puncte intră într-o frază, cum e mai sus, întâi începi fraza cu finalitatea (*end*) apoi continui cu mijlocul (*mean*).

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +Executabilele sunt fișiere care conțin instrucțiuni pe care procesorul știe să le interpreteze și să le ruleze.
Nu spune "procesorul", spune "sistemul de calcul". Evită folosirea antropomorficului "știe", găsește un cuvânt neutru, pentru subiecte ne-umane.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +*ELF 64-bit LSB shared object* din output ne indică acest lucru.
Asta e ca nuca. Spune de la ce vine ELF și LSB, spune că nu sunt relevante acronimele, dar că, în Linux, când vezi ELF, ăla e indicație că e executabil.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +    13 is not prime
Dă și tu o concluzie, nu lăsa în aer.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +Numele ``a.out`` nu este intuitiv, vrem ca executabilele să aibă un nume care să sugereze ceea ce fac.
Zi că este implicit. Problema nu e că nu e intuitiv; problema e că e la fel pentru toate fișierele compilate.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +Opțiunea ``-o`` urmată de numele ales pentru program(``is-prime``) specifică compilatorului ca programul să se numească ``is-prime``, și nu ``a.out``.
spațiu înainte și după parantează

specifică -> transmite

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-intro.rst
> +* Creați un fișier cu numele ``is-palindrome.c`` care să conțină următorul conținut:
Ar trebui să fie liste ordonate, pentru consecvență cu celelalte secțiuni.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +
Fii completă. Spune ce conține fiecare fișier. Spune că `algorithms.h` este fișier *header* (de unde extensia `.h`).

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +Fișierul ``algorithms.h`` conține **declarația** (*antetul*) funcției ``factorial``:  ``unsigned factorial(int n);``, iar fișierul ``algorithms.c`` conține **definiția** (*implementarea*) ei.
Spune-le să vadă conținutul fișierului, pentru verificare, folosind fie comanda `cat`, pagerul `less` sau editorul `nano`.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +Ștergem fișierul ``algorithms`` folosind comanda ``rm``:
Spune de ce.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +Acest lucru este ineficient atunci când lucrăm la un proiect mai mare, unde etapa de compilare durează mult (spre exemplu, compilarea `nucleului Linux <https://github.com/torvalds/linux>`_).
Referința la compilarea nucleului Linux pune-o ca footnote.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +Ca să evităm recompilarea fișierelor cod sursă care nu au fost modifcate, putem să *spargem* etapa de compilare în 2 parți:
spargem- > descompunem că nu suntem țărani care sparg lemne sau capete sau buci

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +    +--------------+     +--------------+
Clarifică aici, în text, că pașii 1 sunt pași de compilare și pasul 2 este pas de legare. Apare în lista de mai sus, dar e mereu bine să clarifici.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +În subsecțiunile următoare vom compila fișierele sursă, ``main.c`` și ``algorithms.c``, în fișiere obiect și le vom lega astfel încât în final vom obține executabilul ``algorithms``.
, în final,

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +În această subsecțiune vom trece prin pasul ``1`` din diagrama din secțiunea :ref:`app_dev_object_files`.
... adică pașii de compilare.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +În această subsecțiune vom trece prin pasul ``2`` din diagrama din secțiunea :ref:`app_dev_object_files`.
adică pasul de legare

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +    algorithms.c  algorithms.h  algorithms.o    main.c  main.o
Dă o concluzie, reminder, legat de ce ai făcut. Și apoi reamintește beneficiile compilării în pași (compilare, legare).

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +În această subsecțiune modificăm fișierul ``main.c``, îl recompilăm într-un fișier obiect ``main.o``.
Din nou: spui ce faci, nu ce urmărești de fapt. Urmărești să demonstrezi beneficiile compilării în pași, în care anumite operații de compilare nu au loc.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-multiple.rst
> +Am văzut în această secțiune cum compilăm eficient un program din mai multe fișiere cod sursă.
Frumos. Așa da, o concluzie.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-lib.rst
> +Găsim implementarea funcției ``printf`` în **biblioteca stdio** (*Standard Input Output library*).
Treci la colt! Bate-te! Bate-te rău! Dormi pe cuie!

Ce durerea mea: biblioteca stdio. De-aia învață studenții numai bazaconii. Biblioteca este **biblioteca standard C**. Header-ul este ``stdio.h``.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-lib.rst
> +Prima linie din fișierul ``main.c``, ``#include <stdio.h>``, înseamnă că îm *inclus* biblioteca în fișierul nostru sursă și că putem să folosim funcțiile definite din bibliotecă.
Jesus F. Christ! Abia pot să respir. Flagelează-te urgent!

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-lib.rst
> +Atunci când am legat fișierele obiect ``main.o`` și ``algorithms.o`` în executabilul ``algorithms``, am legat, de fapt, fișierele obiect ``main.o``, ``algorithms.o`` **și** biblioteca stdio.
ooo, domane, nu mai pot să citesc. Nu citesc secțiunea asta, refă-o după ce te bați bine de tot.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +La fiecare schimbare pe care o facem în program, trebuie să *recompilăm* fișierul pe care l-am modificat și să creăm un nou executabil.
De ce? Ca să-l testăm, să-l rulăm si să vedem dacă are comportamentul așteptat. Spune asta.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +În loc să dăm de fiecare dată toate comenzile pentru recompilarea fișierelor, putem să dăm o singură comandă care să le facă pe toate.
Acest proces se numește *build automation*. Există mai multe soluții de build automation (pui footnote și spui de maven, ant, gradle, dai link aici: https://en.wikipedia.org/wiki/Build_automation). În această carte vom folosi ...

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +În secțiunile următoare vom folosi vedea cum funcționează utilitarul Make și care este structura lui.
Cum adică "care este structura lui". Nu are structură, fișierul "Makefile are structură", clarifică asta.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +#. ``gcc -c hangman.c``, comandă prin care am creat fișierul obiect ``hangman.o``
zi că e comandă de compilare

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +#. ``gcc -o hangman hangman.o``, comandă prin care am creat executabilul ``hangman``.
zi că e comandă de  legare

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +Practic, scriind doar comanda ``make``, am trecut fișierul ``hangman.c`` prin toate etapele compilării și am obținut executabilul final.
Fă referințaă la secțiunea cu fazele de compilare.

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +În secțiunea anterioară, :ref:`app_dev_use_makefile`, am folosit fișierul Makefile ca să compilăm programul Hangman.
Makefile cu monotype

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +Fișierul ``Makefile`` arată în felul următor:
Fișierul ``Makefile`` folosit la programul Hangman are următorul conținut:

"arată" e un cuvânt antropomorfic, evită-l

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +Avem în fișier 2 tipuri de rânduri:
Liniile din fișier sunt de două tipuri:

2020-10-31 08:41 UTC, razvand commented on chapters/app-dev/make-simple-automation.rst
> +În terminal facem acest lucru folosind comanda ``make`` urmată de numele regulii, în acest caz ``make clean``:
În terminal,

2020-11-01 07:46 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +Asta înseamnă că acum Git știe de noile modificări și așteaptă ca modificările să fie adunate într-un commit.
vezi acum

2020-11-01 07:47 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +Creăm un commit cu modificările făcute folosind comanda ``git commit``:
mi se pare că "creăm un commit.." e mai apropiat de "fă și tu asta acum"

2020-11-01 07:51 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +    .. code-block:: c
ți-am mai zis: se strică numărătoarea listei (1, 2, 1, 2 în loc de 1, 2, 3, 4)

2020-11-01 07:52 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +    .. code-block:: c
și dunga apare și dacă am 2 spații înainte de ``.. code-block:: c``

2020-11-01 07:54 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +
și dacă-l afișează și nu știu să-l citească, ce sens are? o să dea click pe link să vadă secțiunea cu git log unde o să vină lucrurile din senin

2020-11-01 07:57 UTC, lizababu commented on chapters/app-dev/git-first-commits.rst
> +Când am adăugat fișierul ``bubble-sort.c`` în staging area în imaginea din secțiunea :ref:`app_dev_create_new_commit`, comanda status ne arăta că fișierul ``bubble-sort.c`` este nou (*new file*).
Ai spus într-un comentariu anterior că este o diferență (mică) între atunci când adaugi un fișier nou în repo și atunci când modifici unul existent și că ar trebui să le tratez separat. Așa am explicat diferența dintre cele 2. Cred că dacă nu o explic, pentru ei pare că sunt 2 tutoriale identice, nimic mai mult

2020-11-01 09:01 UTC, lizababu commented on chapters/app-dev/git-branches.rst
> +Un repository Git are un branch principal de dezvoltare, numit **master**.
am testat, da, main e branch-ul default acum; la final de tot înlocuiesc master cu main peste tot; am pus în TODO

2020-11-01 09:20 UTC, lizababu commented on chapters/app-dev/git-branches.rst
> +Un repository Git are un branch principal de dezvoltare, numit **master**.
mamă dar local (adică până să legi repo-ul local de unul remote) tot master se cheamă că git nu e GitHub.. cum fac?

2020-11-01 09:25 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-11-01 10:10 UTC, razvand commented on chapters/app-dev/git-first-commits.rst
> +Creăm un commit cu modificările făcute folosind comanda ``git commit``:
Nu apare de ce. Apare doar ce. Poți spune: "Acum vrem ca modificările de mai sus să ajungă în repository. Pentru aceasta creăm un commit ..."

2020-11-02 15:25 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-11-02 19:33 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-11-02 20:06 UTC, razvand requested changes
Am recenzat conținutul. Arată foarte bine. Curge, are sens totul, e bine explicat. Pare un pic sărăcăcios în exerciții, dar aici cred că va ajuta secțiunea "Exerciții suplimentare".

Comentariile pe care le-am făcut ating forma, foarte puțin fondul. Rămâne discuția main vs master. Recomand să mergem pe master all the way cu precizarea undeva că e posibil să se cheme main în anumite soluții. Și cu asta basta.

2020-11-02 20:06 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +Ștergerea branch-ului în urma integrării în branch-ul master
Aici ai zis master. Cred că e OK to stick with master.

2020-11-02 20:06 UTC, razvand commented on chapters/app-dev/git-first-pull-request.rst
> +#. Lucrul pe un singur branch nu oferă posibilitatea de a da feedback pe schimbările făcute pe repository. Dacă nu avem posibilitatea să oferim feedback unui coleg prin intermediul GitHub, atunci vom
, înainte.

Ar trebui sa pui fiecare propoziție pe un rând nou. Și indentând-o să fie la același nivel cu prima din listă, ca sa fie afișarea ca lumea.

2020-11-02 20:46 UTC, lizababu commented on chapters/app-dev/intro.rst
> +Este un editor CLI și se pornește folosind comanda ``nano``, așa cum a fost prezentat în capitolul *Lucrul cu fișiere*.
after merge

2020-11-02 21:56 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Configurarea branch-ului în care vom integra PR-ul
mmm nu știu, la mine (pe Safari) apar bine

2020-11-02 22:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-11-03 08:30 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-11-03 08:33 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-11-03 11:48 UTC, edi33416 requested changes

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-first-commits.rst
> +Ne dăm seama de acest lucru pentru că ``HEAD`` se află în dreptul commitului tocmai făcut.
Nu văd HEAD în outputul `log`-ului de mai sus

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +În continuare vom lucra la proiectul nostru ``array-sorting-algorithms``, dar vom face schimbări de pe alt branch-uri.
s/pe alt/pe alte/g

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +În această secțiune vom adăuga un fișier ``.gitignore`` proiectului și vom adăuga implementarea pentru agloritmul Merge Sort.
s/În această secțiune/În secțiunea următoare/g

sau mută textul în secțiunea de mai jos.

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +
Spune care este scopul lui `gitignore`. Acum pare că îl adăugam doar ca să adăugăm ceva

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +Odată cu publicarea commitului pe GitHub, a fost creat și branch-ul ``add-gitignore`` remote.
s/remote/în repository-ul remote/g

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +#. Modificați conținutul fișierului **merge-sort.c** cu următorul conținut:
aici aș modifica numele variabilelor în ceva descriptiv: left, right, mid; în loc de l, r, m

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +#. Modificați conținutul fișierului **merge-sort.c** cu următorul conținut:
codul arătat să fie și un exemplu de cod scris frumos

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +        int L[n1], R[n2];
nu folosi `L` și `R`. `aux_left` (sau `tmp_left`), `aux_right` (sau `tmp_right`) sunt mai potrivite și mai descriptive

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-branches.rst
> +Atunci când contribuim la un proiect putem să lucrăm fie branch-ul **master**, fie pe un alt branch.
s/fie branch-ul/fie pe branch-ul/g

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-first-pull-request.rst
> +Configurarea branch-ului în care vom integra PR-ul
și la mine apar bine

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-first-pull-request.rst
> +			count[ (array[i]/exp)%10 ]++;
spațierea `count[(array[i] / exp) % 10]++;`

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-first-pull-request.rst
> +		int i, count[10] = {0};
declarații și definiții pe linii diferite

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-first-pull-request.rst
> +			output[count[ (array[i]/exp)%10 ] - 1] = array[i];
ditto spațiere

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-first-pull-request.rst
> +			count[ (array[i]/exp)%10 ]--;
ditto spațiere

2020-11-03 11:48 UTC, edi33416 commented on chapters/app-dev/git-first-pull-request.rst
> +		for (int exp = 1; m/exp > 0; exp *= 10)
`m / exp`

2020-11-03 22:37 UTC, lizababu commented on chapters/app-dev/git-first-pull-request.rst
> +Configurarea branch-ului în care vom integra PR-ul
am văzut și eu când micșorez fereastra se alungesc așa, nush care-o faza

2020-11-04 08:05 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +În această secțiune vom folosi fișierul Makefile pe care l-am folosit anterior.
cuvinte simple, Eduardo, simple!!

2020-11-04 08:12 UTC, edi33416 commented on chapters/app-dev/make-simple-automation.rst
> +În această secțiune vom folosi fișierul Makefile pe care l-am folosit anterior.
se tot repetă folosi/folosit acolo :))

2020-11-04 08:56 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2020-11-05 12:45 UTC, edi33416 commented on chapters/app-dev/make-intro.rst
> +        for (i = 2; i < n / 2; i++) {
trebuie să fie `<=`

2021-08-12 03:57 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2021-08-12 04:02 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/17/merge

2021-08-12 04:03 UTC, merged