WIP: Capitolul fișiere
systems-cs-pub-ro/uso-lab-book pull request #20
Opened 2020-08-20 12:09 UTC by CostinCarabas

Versiunea finală:
- [ ] Căi absolute și relative

- [ ] Interacțiunea cu fișiere în linia de comandă

- [ ] Editor de text

- [ ] Redirectări

- [x] Arhive

- [ ] Sistemul de fișiere

Signed-off-by: Costin Carabas <costin.carabas@gmail.com>

2020-08-20 12:10 UTC, CostinCarabas commented
@Sergiu121 , @lizababu , am făcut curat printre PR-uri.
Acesta este singurul relevant.

2020-08-20 12:10 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-08-20 12:13 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-08-20 15:21 UTC, lizababu requested changes
Am mai specificat unde personal mi-ar plăcea să fie mai multă informație.

O chestie generală (am scris-o explicit și în unele comentarii): eu prefer să apară explicațiile argumentelor să apară înainte de exemplu ca ei să poată ști ce înseamnă lucrurile alea la momentul rulării exemplului.

Îmi place treaba cu verificatul comenzilor (și că amintești des treaba asta). O s-o fur, mersi!

2020-08-20 15:21 UTC, lizababu commented on chapters/files/archive.rst
> +Sintaxa este în felul următor: ``zip **numele_arhivă.zip** ierarhia_de_fișiere``
aici nu merge boldul

2020-08-20 15:21 UTC, lizababu commented on chapters/files/archive.rst
> +Pentru a vizualiza arhiva **fără** dezarhivare folosim opțiunea **-sf**.
aș zice aici că folosim opțiunea -s (asta pentru că oricum spui după ce face -f)

2020-08-20 15:21 UTC, lizababu commented on chapters/files/archive.rst
> +Afișați conținutul arhivei **fără** dezarhivare.
Cred că poți să-i pui să arhiveze fișierele de la o cale din sistem. După să afișeze conținutul acestei arhive.

2020-08-20 15:21 UTC, lizababu commented on chapters/files/archive.rst
> +Dezarhivăm o arhivă de tipul **zip**, astfel:
La fel ca mai devreme, ștergem pentru că bla bla

2020-08-20 15:21 UTC, lizababu commented on chapters/files/archive.rst
> +Creați un director cu numele **zip** în directorului **dezarhivare** ca în ierarhia de mai sus.
poți adăuga aici să dezarhiveze întreaga arhivă creată de ei mai devreme la o cale specificată ca să nu fie tot arhiva din exemplu.

2020-08-26 05:18 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-09-02 05:20 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-09-02 14:34 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-09-17 14:18 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-09-18 04:24 UTC, lizababu reviewed
Am adăugat review pentru secțiunea Editoare de text. Îmi place că e totul simplu, clar.

Aș mai adăuga la final o subsecțiune "Cheatsheet" sau ceva în genul ăsta cu o sumarizare a chestiilor mai importante din nano (adică alea de le prezinți și în GIF să fie și scrise undeva ca să nu stea să se uite la GIF până când dai tu comanda care îi interesează). Și totodată să spui că în această carte vom folosi nano drept suport de exemplificare pentru că e ușor de folosit.

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +Poate cel mai folosit editor din această categorie este **Microsoft Word**.
Cred ar fi util să pui linkuri pentru fiecare editor ca să fie one click away dacă vrea cineva să vadă cum e MS Word sau sublime sau nano.

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +Printr-o singură apăsare de buton, se pornește simulatorul de iPhone și se execută aplicația.
Formatarea e bușită aici

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +.. figure:: gifs/pages.gif
Mi se pare foarte tare GIF-ul ăsta! 

Ar merge o notă în care să precizezi că Pages din GIF este folosit pe MacOS sau nu știu dacă ar trebui să fie făcut un tutorial similar pentru un editor de text din Linux, tu ce zici? @Sergiu121 tu?

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +Deschideți fișierul **Romanian Presidents** și completați fișierul cu cel puțin 3 președinți ai României.
Poate ar merita să le zici: folosiți editorul de text X (gedit, sublime, vezi ce e instalat pe VM). Ca să fie clar. Poate unii se așteaptă să găsească fix Pages din tutorialul de mai sus

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +Există editoare mai puternice **vim**, **emacs** care permit automatizarea unor sarcini precum cele de mai sus (Exerciții - editor grafic).
să bagi ref la exerciții

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +În partea de jos apare optiunea de **Y**es și **N**o.
Nu-mi dau seama de ce e așa, dar e bușită formatarea, apar niște * pe acolo

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +.. figure:: gifs/shortcuts.gif
Nu știu dacă să fiu picky acum: Ctrl+k vs. Ctlr+K, diacritice și uniformizare: copiere/lipire, copy/paste, nu copiere/paste

2020-09-18 04:24 UTC, lizababu commented on chapters/files/file_editor.rst
> +Deschideți fișierul **US Presidents** și completați fișierul cu cel puțin 3 președinți ai Statelor Unite are Americii.
Vor avea o ierarhie dată cumva? Dacă da, spune-le cum ajung să o aibă (fie că dau git clone, fie că o descarcă de altundeva). Aș face asta la începutul fiecărei secțiuni.

2020-09-18 04:41 UTC, lizababu requested changes
Am recenzat secțiunea "Redirectări". Mi se pare în regulă. Să te coordonezi cu @edi33416 să ne asigurăm că restul de redirectări sunt făcute undeva în carte, să nu uităm de ele.

2020-09-18 04:41 UTC, lizababu commented on chapters/files/io_redirection.rst
> +În acest capitol vom învăța cum să facem aceste direcționări (redirectări).
.. de output. Există mai multe tipuri de redirectări (input și error), însă acestea vor fi prezentate în capitolul <care o fi el + referință>

2020-09-18 04:41 UTC, lizababu commented on chapters/files/io_redirection.rst
> +    student@uso-demo:~$ ls -lh > lista_fisiere
student@uso-demo -> student@uso

2020-09-18 04:41 UTC, lizababu commented on chapters/files/io_redirection.rst
> +    Folosirea caracterului **>** șterge conținutul fișierului. Dacă **lista_fisiere** avea conținut, acesta era șters și înlocuit cu rezultatul comenzii **ls -lh**.
N-aș zice că șterge conțintul (să nu se înțeleagă că rolul lui > e să șteargă). Aș zice că suprascrie conținutul deja existent cu cel nou. 

Sumarizare: fișierul
1. există
   a. e gol: scrie în el
   b. nu e gol: suprascrie textul deja existent (nu păstrează nimic din conținutul anterior)
2. nu există: în creează și scrie outputul în el

Aș adăuga câte un exemplu pentru fiecare caz de mai sus ca să nu rămână loc de interpretări.

2020-09-18 04:41 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Folosiți **tree** pentru a afișa ierarhia de fișiere pornind de la **/home/student** și direcționați-o în fișierul **ierarhie_student**. Inspectați fișierul pentru a demonstra corectitudinea operație
Câte un exercițiu pentru fiecare caz de care am zis mai sus.

2020-09-18 04:41 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Putem observa că la sfârșitul fișierului s-a adăugat o linie cu noul rezultat al comenzii **ls**.
+ La fel ca în cazul lui >, dacă fișierul nu există, îl va crea și va scrie în el outputul. + exemplu cu asta

2020-09-18 04:41 UTC, lizababu commented on chapters/files/io_redirection.rst
> +    -rw-r--r-- 1 student student 5.0M Aug 19 11:55 fisier1
fișierN -> ceva c00l

2020-09-18 04:41 UTC, lizababu commented on chapters/files/io_redirection.rst
> +    student@uso-demo:~$ ls -lh > lista_fisiere
prima comandă: ls-lh > lista_fisiere nu mai produce output
poți să dai de 2 ori ls -lh, prima oară fără >, după cu

+ o precizare într-un note că odată redirectat outputul, acesta nu mai apare la terminal

2020-09-18 05:05 UTC, lizababu requested changes
Am făcut review pe secțiunea "Arhive".

2020-09-18 05:05 UTC, lizababu commented on chapters/files/archive.rst
> +Creați un fișier **UPB** și adăugați-l la arhiva **personal_data.zip**, ca în exemplul de mai sus.
la exerciții (în general) te poți folosi de faptul că au învățat să folosească editoare de text/redirectări într-o secțiune anterioară:

#. Creați arhiva TODO din fișierele TODO.
#. Verificați conținutul arhivei fără să o dezarhivați.
#. Folosind editorul nano, creați un nou fișier numit UPB cu conținutul "Make UPB great again!".
#. Adăugați fișierul la arhiva TODO creată la primul exercițiu **fără** a reface arhiva.

2020-09-18 05:05 UTC, lizababu commented on chapters/files/archive.rst
> +Creați un fișier **UPB** și adăugați-l la arhiva **personal_data.zip**, ca în exemplul de mai sus.
+ pași mărunți: fiecare chestie să fie un exercițiu: exercițiu de creare, exercițiu de verificare, exercițiu de adăugare, exercițiu de vizualizare, exercițiu de dezarhivare. Task-uri mărunte, fără "faceți X și Y și Z" în același exercițiu.

2020-09-18 17:02 UTC, Sergiu121 requested changes
In general la exercitii nu se simte un storyline, un context. Exercitiile sunt cam seci.

De exemplu, de ce vreu sa fac arhive? Cand vreau sa fac o arhiva tar? Dar o arhiva zip?

Mi se pare ca la editoare de text nu ar trebui sa ne atingem de Word sau Pages, deoarece acelea sunt editoare de documente, nu editoare de test. Pe noi ne intereseaza un public care lucreaza/vrea sa lucreze in IT si va folosi editorul de text pentru a scrie cod, a configura sisteme, a verifica continutul fisierelor.

La redirectari nu ai vorbit despre redirectarea erorii, lucru care mi se pare destul de folositor si nici nu ai vorbit despre redirectarea inputului pentru a face o comanda sa nu fie interactiva.

Acolo unde am putut, i-am pus pe ei sa faca o un exercitiu de recapitulare in tutorial. Am lasat un comentariu cu exemplu punctual, dar cred ca asta ar trebui sa fie prezent pretutindeni.

Cred ca in unele locuri limbajul este prea informal, sau sunt anumite cuvinte pe care eu nu le-as fi ales. Am lasat comentariu punctual pentru exemple unde eu nu as fi ales acele cuvinte.

2020-09-29 08:30 UTC, CostinCarabas commented on chapters/files/archive.rst
> +Putem observa că fișierul de tipul **tar** nou creat **nu** ocupă mai puțin spațiu; din contră, ocupă mai mult spațiu din cauza metadatelor fișierului.
@Sergiu121 să specific despre metadate?

2020-09-29 17:21 UTC, CostinCarabas commented on chapters/files/archive.rst
> +    În cazul în care nu le aveți, le puteți instala folosind comanda: ``sudo apt install tar`` respectiv ``sudo apt install zip`` (pentru mai multe detalii, vezi secțiunea de instalare de aplicații).
Voiam să le dau un exemplu de cum se instalează un pachet, dar mai bine nu complic lucrurile. Scot partea asta.

2020-09-30 12:48 UTC, CostinCarabas commented on chapters/files/archive.rst
> +   Verificați corectitudinea operațiilor.
Momentan pot să verifice doar că s-a creat o arhivă. Am adăugat detalii despre *file*.

2020-09-30 13:12 UTC, CostinCarabas commented on chapters/files/archive.rst
> +În primă fază am verificat că **fisier4** nu există în arhivă.
O las și aici să fie ca exemplu și o să fac și niște exerciții de recapitulare

2020-09-30 13:13 UTC, CostinCarabas commented on chapters/files/archive.rst
> +    Observăm cum după comanda de adăugare de fișier la arhivă, am verificat corectitudinea operației.
Ce să facă? Să adauge un fișier la arhivă?
Eu mă gândeam să creez alt scenariu și să fac și ei tot ce am făcut noi în tutorial.

2020-10-01 19:08 UTC, CostinCarabas commented on chapters/files/file_editor.rst
> +Poate cel mai folosit editor din această categorie este **Microsoft Word**.
Care este diferența în contextul nostru?
Care este definiția unui document și cu ce diferă el de text?
Încerc să pornesc de la ceva familiar. Aveți vreo altă idee?

2020-10-01 19:15 UTC, CostinCarabas commented on chapters/files/file_editor.rst
> +.. figure:: gifs/pages.gif
Dap, așa este. Bag sublime. Las și pe ăsta pentru diversitate.

2020-10-01 19:28 UTC, CostinCarabas commented on chapters/files/file_editor.rst
> +Acestea asigură funcționalitați restrânse de editare în comparație cu editoarele grafice.
Păi cum faci cu **vim** să scrii cu **Times New Roman**, cu **roșu** și cu **dimensiunea** **fontului 14**.

2020-10-01 19:32 UTC, CostinCarabas commented on chapters/files/file_editor.rst
> +Acesta are funcționalități de bază și este ușor de folosit.
Nu știu să răspund la întrebarea asta. Poți să dai o direcție de răspuns?

2020-10-01 20:21 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-01 20:29 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-04 08:25 UTC, lizababu requested changes
Adaugă recenzie pe subsecțiunea "Interacțiunea cu fișiere în linia de comandă".

2020-10-04 08:25 UTC, lizababu commented on chapters/files/files.rst
> +Ce se întâmplă dacă ștergem un fișier?
aș lăsa întrebările pentru la exerciții, aici doar să le arătăm ce se întâmplă

Ștergem fișierul X folosind comanda rm:

output

Explici aici ce s-a întâmplat.

2020-10-04 08:25 UTC, lizababu commented on chapters/files/files.rst
> +* Creați o legătură simbolică către directorul **Netflix**.
Spune și unde să o creeze

2020-10-04 08:25 UTC, lizababu commented on chapters/files/files.rst
> +Putem crea legături strânse, astfel
Creăm legături strânse (*hard*) folosind comanda ln:

2020-10-04 08:25 UTC, lizababu commented on chapters/files/files.rst
> +Putem crea legături strânse, astfel
exemplu

și după zici: legătura se numește X și indică spre fișierul/calea Y

2020-10-04 08:25 UTC, lizababu commented on chapters/files/files.rst
> +
Trage concluzia la ce ai făcut aici: ai șters Arya Stark și ce s-a întâmplat?

2020-10-04 08:25 UTC, lizababu commented on chapters/files/files.rst
> +Execuția fișierelor se face în felul următor: ``CALE/NUME``.
înțeleg aqsta pentru că știu cum se face

mai bine începem simplu cu ./executabil, simplu rapid fără prea multe explicații

după mai dai un exemplu zici: suntem în /home/student și vrem să rulăm fișierul executabil X de la /home/student/lalala/lalala/alla/X, facem așa:

2020-10-04 08:39 UTC, lizababu commented on chapters/files/file_editor.rst
> +Poate cel mai folosit editor din această categorie este **Microsoft Word**.
doar că documentul are un format specific (.docx, .xls, ce-o mai fi)
mi se pare ok familiarizarea cu ceva poate cunoscut, să nu rămânem la ele
în rest să alegem unul (nano) și să "stick with it"

2020-10-06 09:54 UTC, CostinCarabas commented on chapters/files/files.rst
> +Afișarea conținutului unui director
Done.

2020-10-06 13:04 UTC, CostinCarabas commented on chapters/files/files.rst
> +Ce se întâmplă dacă ștergem un fișier?
Era o întrebare retorică. 
Am pus afirmație în loc de întrebare.

2020-10-06 21:34 UTC, lizababu requested changes
Adaugă recenzie pentru secțiunea "Căi absolute și relative".

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +.. code-block:: bash
indentare cu 2 spații că se bușește numărătoarea de la listă

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +.. code-block:: bash
Ah și mai precizează că / e caracterul delimitator folosit în Linux. Ca notă de subsol poți pune o paralelă cu Windows (\) și macOS (/)

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +#. Pornind de la **/** (root), directorul de început - **cale absolută**.
Pornind din rădăcina ierarhiei de fișiere (_root_), reprezentat prin simbolul */*, numită **cale absolută**.

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +#. Pornind de la directorul curent - **cale relativă**.
Pornind din directorul în care ne aflăm (_directorul curent_), numită **cale relativă**.

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +* Față de episodul la care ne aflăm (în mod relativ): *În urmă cu 3 episoade s-a întâmplat ceva.*
listă ordonată (că am precizat câte elemente are lista)

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
>  Similar, ne referim la un fișier:
, în două moduri:

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +#. Pornind de la **/** (root), directorul de început - **cale absolută**.
aș tăia exemplele și notițele de la asta și de la următoarea și aș face 2 subsubsecțiuni noi în care să le iei pe rând

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +.. note::
ditto

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +Putem folosi atât cale absolută, cât și cale relativă.
Plasarea noastră într-un alt director decât cel curent înseamnă schimbarea căii curente.
Facem acest lucru folosind comanda `cd`:

exemplu cd+pwd

Acum ne aflăm la calea TODO.

linie nouă

Comanda cd primește ca parametru o _cale_.
Calea poate fi *relativă* sau *absolută*.

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +Putem folosi atât cale absolută, cât și cale relativă.
după:

Suntem în directorul /home/student.
Ne putem muta la calea /etc/ folosind o cale absolută în felul următor:

exemplu

Această comadnă poate fi folosită din orice director de aflăm deoarece folosește o cale absolută. Calea absolută rămâne aceeași, indeferent de directorul în care ne aflăm.

Revenim la calea /home/student și ajungem la aceeași cale, /etc/, folosind o cale relativă:

exemplu

Această comandă nu mai este universal valabilă, nu va funcționa din orice director în care ne-am afla.
Rulăm din nou comanda TODO (aia din ultimul exemplu):

exemplu

Comanda nu a funcționat deoarece calea dată ca argument comenzii cd  este una *relativă*, mai exact, relativă față de directorul /home/student (adică cel de la care am pornit), nu față de directorul /etc/ (adică cel în care ne aflăm acum).

Atunci când folosim căi riscăm să facem greșeli de tastare.
Evităm greșeșlile folosind tasta Tab. Tasta Tab are rolul de a face autocompletare la numele unui fișier sau director, ca în imaginea de mai jos:

bagi un GIF în care folosești o cale relativă să revii la calea /home/student din /etc/ și folosești Tab de fiecare dată (să nu scrii h<Tab>/s<Tab> că probabil face autocomplete direct și nu o să se vadă; să faci cu Tab+Tab)

Aici descrii pe ce ai apăsat ca să faci ce faci în GIF.

Și aici la final zici că dacă știi cu cel literă/litere începe numele unui director/fișier poți să o/le scrii și după să folosească Tab

Și bagi un alt GIF aici cu situația descrisă aici

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
>  * Folosim **-** pentru a referi la **calea anterioară**.
Folosim caracterul **-** ...

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
>  * Folosim **~** pentru a referi **calea home** a utilizatorului.
Folosim caracterul **~** ...

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +    /usr/bin
indentare cu 2 spații pentru acest code-block

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +    /usr/bin
după el poți pune o precizare "Dacă folosim repetat comanda cd - vom face un joc dute-vino (*ping-pong*) între 2 directoare.

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +    /home/student
indentare cu 2 spații pentru acest code-block

2020-10-06 21:34 UTC, lizababu commented on chapters/files/paths.rst
> +.. important::
aș tăia asta pentru că depinde de shell
spre exemplu în zsh nu mai apare așa
chiar și în bash când calea devine prea lungă parcă o face: ~/cale/lungă/lungă/.../până/la/fișier

2020-10-06 22:34 UTC, lizababu requested changes
Adaugă recenzie pentru secțiunea "Sistemul de fișiere"

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +De multe ori avem nevoie să căutăm dacă un fișier există pe sistem și unde.
Se poate întâmpla să vrem să aflăm dacă într-o ierarhie de fișiere găsim un anumit fișier și dacă există, vrem să aflăm  unde se află. Spre exemplu, serviciul TODO folosește un fișier de configurare numit TODO, dar nu mai ținem minte calea exactă până la acel fișier.

Linux ne oferă 2 utilitare, locate și find, care pot fi de ajutor în situația descrisă mai sus.
Vorbim mai în detaliu despre fiecare utilitar în subsecțiunile de mai jos.

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +
Înainte de exemplul ăsta poți căuta fișierul ala de configurare al cărui nume îl știm exact.

Căutăm fișierul TODO folosind utilitarul find:

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Căutăm în sistem un fișier folosind utilitarului ``find``, aftfel:
În mod obișnuit, numele fișierelor de configurare pentru servicii se termină în extensia ".conf". Găsim toate fișierele de configurare de pe sistem folosind comanda find:

exemplu ca mai jos

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Căutăm în sistem un fișier folosind utilitarului ``find``, aftfel:
cumva asta cu tar e cu dus și întors pentru că posibil să nu găsească prea multe și nu e convingător că acest utilitar poate face ceva minunat

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +    Mai multe informații și exemple se regăsesc în capitolul ##### TODO Capitol Edi ######
Găsim mai multe informații și exemple în capitolul TODO.

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Utilitarul ``locate`` rezolvă această problemă.
ne poate ajuta în astfel de situații

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +* Crearea și actualizarea unei baze de date folosind comanda **updatedb**;
care ce conține?

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +
toată introducerea asta merge pusă dirrect în subsecțiunea de locate

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +    student@uso:~$ sudo updatedb
nu știu dacă s-a mai vorbit de sudo până acum, merită pusă o explicație scurtă: am folosit sudo în fața comenzii updatedb pentru că

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +    student@uso:~$ sudo updatedb
înainte de exemplul ăsta aș căuta același fișier de conf (ca să fie o paralelă cu find de mai sus)
după asta cu pwd
și în cele din urmă toate fișierele de configurare (la fel aș merge pe asta în loc de arhive că ei pe sistem o să aibă probabil doar /home/student/usr_bin.tar)

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +.. note::
Găsim mai multe informații și exemple în capitolul TODO.

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Până acum am învățat câteva comenzi utile.
utile: ls, find, locate (zi-le pe toate).

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Până acum am învățat câteva comenzi utile.
Utilitarele sunt de fapt programe (executabile) care se află undeva în sistemul de fișiere.

Shell-ul știe să ruleze utilitarele din orice loc în care ne aflăm (din ierarhia de fișiere). 
Se întâmplă acest lucru pentru că shell-ul are o listă de câteva directoare în care se uită după utilitarele pe care le folosim.
Spre exemplu, atunci când rulăm utilitarul ls, el caută programul ls în lista pe care o are, îl găsește și îl rulează.

Această listă se găsește în *variabila de mediu* (notă de subsol pe scurt pentru ce e o variabilă de mediu și că vom vorbim despre ele mai mult în capitolul lui Edi, parcă) **PATH**. Vedem conținutul ei mai jos:

output echo $PATH

explicația pe cum arată outputul

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Observăm că variabila **PATH** are patru căi din sistem, despărțite de caracterul **:**.
fără observăm

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Observăm că variabila **PATH** are patru căi din sistem, despărțite de caracterul **:**.
pune `:`

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +De exemplu, putem să-l înlocuim cu utiltiarul nostru: dacă înlocuim utilitarul `ls` cu `pwd`, la fiecare execuție de `ls`, va fi afișată calea curentă.
nu mi se pare cp propoziția asta stă bine aici
aș tăia-o, treaba ar merge frumos la exerciții

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
>  Acest utilitar identifică calea programelor din sistem.
Căutăm calea la care se află utilitarul ls folosind comanda which:

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +.. note::
fără note

2020-10-06 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +.. note::
Vorbim mai mult despre utilitarul which în capitolul TODO.

2020-10-07 18:25 UTC, lizababu requested changes
Adaugă recenzie pentru secțiunea "Redirectări"

2020-10-07 18:25 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Observăm că la exemplul anterior, am vrut să afișăm conținutul fișierului **lista_materie**, fișier ce nu există.
Am vrut să afișăm conținutul fișierului `lista_materie`, însă acest fișier nu există.

2020-10-07 18:25 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Observăm că dacă folosim redirectarea simplă ``>``, eroarea tot este afișată.
Redirectăm outputul comenzii în fișierul copy_lista_materii:

exemplu: cat lista_materii > copy_lista_materii

Vedem că în terminal încă a fost afișat mesajul  *No such file or directory*, deși am redirectat outputul acestei comenzi.
Pentru a redirecta erorile de la această comandă folosim caracterul 2>:

exmplu: cat lista_materie 2> errors.txt
cat errors.txt

Acum eroarea a fost scrisă în fișierul `errors.txt` și nu a mai fost afișată la terminal.

2020-10-07 18:25 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Observăm că dacă folosim redirectarea simplă ``>``, eroarea tot este afișată.
și nu mai pomenești de SO2; sau păstrezi SO2 și tai lista_materie, cum vrei tu

2020-10-07 18:25 UTC, lizababu commented on chapters/files/io_redirection.rst
> +.. note::
nu ca notă
dă și un exemplu

2020-10-07 18:25 UTC, lizababu commented on chapters/files/io_redirection.rst
> +.. note::
Ca să redirectăm și outputul și erorile de la o comandă folosim și > și 2> ca mai jos:

exemplu aici

2020-10-07 18:25 UTC, lizababu commented on chapters/files/io_redirection.rst
> +În exemplul de mai sus încercăm să afișăm conținutul fișierelor ELTH, USO și SO2, dar cu fișierul SO2 neexistent.
Liniile `USO is the b3st` și `USO RULLZ` sunt conținutul fișierelor ELTH și USO. Comanda cat ne-a arătat conținutul celor 2 fișiere. Tot comanda cat a încercat să afișeze conținutul fișierului SO2, însă el nu există și a afișat eroarea Not such file or directory.

Redirectăm outuputul în fișierul materii și erorile în errors.txt:

exemplu aici și inspectarea celor 2 fișiere (ca în code-blockul de mai jos)

2020-10-08 07:52 UTC, CostinCarabas commented on chapters/files/file_editor.rst
> +Există editoare mai puternice **vim**, **emacs** care permit automatizarea unor sarcini precum cele de mai sus (Exerciții - editor grafic).
@lizababu , nu înțeleg, ce ref?

2020-10-09 11:02 UTC, CostinCarabas commented on chapters/files/paths.rst
> +.. important::
Transform în note, dar las. La mașina pusă la dispoziție de noi apare și își pot configura și ei.

2020-10-09 13:39 UTC, CostinCarabas commented on chapters/files/io_redirection.rst
@Sergiu121 , @edi33416 , @razvand ce părere aveți?
Mi se pare că încarcă foarte multe conținutul.
@lizababu

2020-10-09 13:44 UTC, edi33416 commented on chapters/files/io_redirection.rst
Cred că putem să punem la începutul cărții sau fiecărui capitol un link către unde se găsește codul.

Cărțile pe care le-am mai citit precizează, de regulă, la începutul cărții: “Codul folosit în această carte este disponibil la <link>.” Acolo e structurat Carte/{ch1, ch2, etc}

2020-10-09 16:04 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-10 08:53 UTC, lizababu requested changes
N-am terminat, dar pentru că și așa am promis și întârzit, dau măcar parțial

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +#. *Arhivare* - să avem o ierarhie de fișiere și directoare într-un singur fișier.
aș scrie mai întâi definiția și după cum se cheamă

Să avem o ierarhie de fișiere și directoare într-un singur fișier, pas numit **arhivare**
(...)

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +.. note::
cred că nu e nevoie de asta că oricum le zicem la început sp folosească VM-ul dat de noi

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Creăm o arhivă folosit utilitarul ``tar``:
s/folosit/folosind

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Creăm o arhivă folosit utilitarul ``tar``:
o arhivă cu fișierele X, Y, Z, numită T folosind utilitatul tar:

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Observăm cum după comanda de creare a arhivei *tar* am verificat corectitudinea operației.
Avem acum în directorul TODO arhiva TODO

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Putem observa că fișierul de tipul *tar* nou creat nu ocupă mai puțin spațiu; din contră, ocupă mai mult spațiu din cauza metadatelor fișierului.
fără "putem observa că"
spune cât ocupă arhiva (9.1M), cât ocupă fișierele separat (5.0M, 3.0M, 1.0M) ca să știe unde să se uite după dimensiune

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Metadatele sunt modalitatea sistemului de fișiere de a reține informații despre acesta: data creării, dimensiunea, utilizatorul ce deține fișierul, etc.
notă de subsol pentru metadate

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +.. note::
drop

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +.. note::
fără note

Verificăm tipul fișierului folosind utilitarul file:

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +
Concluzie: inregistrari.tar este o arhivă de tip tar ce mai zice ăla acolo

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Putem face acest lucru folosind parametrii *t* și *f* ale utilitarului ``tar`` ca în exemplul de mai jos:
Facem acest lucru folosind utilitarul tar:

și spui după că am folosit t și f

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Exerciții - afișarea conținutului unei arhive
Exercițiu

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +* Afișați conținutul arhivelor create la exercițiul anterior **personal_data.tar** și **net.tar** **fără** dezarhivare.
formatează fără cu italic, sau numele arhivelor cu italic și fără să rămână bold

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Având un fișier de tip *tar* vrem să obtinem ierarhia de fișiere din interiorul acesteia.
Avem deja o arhivă și vrem să extragem ierarhia de fișiere din ea.

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +Pentru a vedea mai clar efectul operației de dezarhivare, ștergem `fișierele înregistrare_lab01.mov`, `înregistrare_lab02.mov`, `înregistrare_lab03.mov`, adică fișierele care se află în arhiva `înreg
s/`fișierele în/fișierele `în

2020-10-10 08:53 UTC, lizababu commented on chapters/files/archive.rst
> +.. code-block:: bash
desparte code-blockul în 2: partea de ștergerem și verificare că nu mai sunt fișierele
după spui: dezarhivăm folosind comanda tar
și după al doilea code-block în care arăți treaba asta

2020-10-10 23:24 UTC, Sergiu121 requested changes
Mi se pare ca mai ai de facut niste lucruri:

Cai:
* sa pui double backticks la toate caile si caracterele speciale (cum ar fi ``~``)
* sa spui in paranteza cand vorbesti despre un caracter special cum ar fi ``~`` ca se numeste tilda
* sa scoti footnote-urile
* sa adaugi exercitii de aprofundare, chiar daca sunte chestii marunte. Mi se pare ca ar trebui sa se sedimenteze chestiile, ca ii treci prea repede prin demo-uri
* sa explici la cd ca ti se schimba si prompt-ul, de acolo poti sa iei CWD-ul

Lucrul cu fisiere:
* sectiunea de metadate nu mi se pare necesara
* cred ca sectiunea asta ar putea imbinata cu cea despre cai, astfel incat ierarhia de fisiere sa fie prezentata inainte de cai
* la ierarhia de fisiere poti adauga schema din carte de la ierarhia de fisiere. Mi se pare mai expresiva
* acolo cand vorbesti de fisiere si cai foloseste doua backtick-uri, ca sa se evidentieze ca ala este numele lor, nu prin italic sau bold

Redirectari:
* nu mi se par necesare sumarurile, deoarece continutul este cam sumar
* foloseste doua backtick-uri pentru numele fisierelor si cai, deoarece nu sunt evidente numele folosind caractere italice
* nu imi este clar daca ar trebui sa le mentionam si de ``&>``. Este folositor, dar poate e prea mult
* sectiunea de redirectare a erorii are nevoie de exercitii, ca sa le ramana informatia in cap

Arhive:
* cred ca ar fi o idee mai buna sa facem o paralela intre comprimare si arhivare folosind arhive ``tar`` si arhive comprimate ``tar.gz``
* mi se pare bine ca ai pus in exercitii sa verifice operatiile facute, dar trebuie sa le si zicem cum sa faca asta, ce sa afiseze, unde sa se uite
* este primul loc unde apare ``ls -lh``. Optiunea asta ar trebui sa fie explicata mai devreme, in sectiunea de fisiere.
* folosesti globbing in unele locuri unde nu e nevoie

File system:
* nu mi se pare necesara recapitularea de la inceputul sectiunii
* exemplul de la find e cam tras de par

2020-10-10 23:24 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +Spre exemplu, serviciul ``ssh`` folosește un fișier de configurare numit ``/etc/ssh/ssh_config``, dar nu mai ținem minte calea exactă până la acel fișier.
Nu mi se pare cel mai palpabil exemplu. Daca nu gasesc o chestie d-asta, caut pe Google. Un exemplu mai de oameni ar fi "nu mai stiu unde am descarcat pozele de la betie".

2020-10-10 23:24 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +Am căutat în calea `/` (*root*) orice fișier ce conține `ssh` și se termină cu `conf`.
Ar trebui sa zici ca find cauta de unde i-ai spus in jos in ierarhie. Asta inseamna ca daca l-ai pus sa caute in ``/`` acesta va cauta in tot sistemul.

2020-10-10 23:24 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +Utilitarul ``find`` nu scalează pentru situațiile când avem multe fișiere și dorim un răspuns rapid.
Ce inseamna ca scaleaza? Foloseste ceva mai simplu.

2020-10-10 23:24 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +Există cazuri când vrem să găsim locația exactă a unui utilitar.
Ar trebui sa spui cand vrei sa il folosesti. Da un exemplu.

2020-10-12 03:14 UTC, CostinCarabas commented on chapters/files/archive.rst
> +Vom folosi *tar* pentru arhivare și *zip* pentru comprimare.
Pot include `tar.gz` la comprimare și vedem cum iese.

2020-10-12 03:45 UTC, CostinCarabas commented on chapters/files/paths.rst
> +În lina de comandă afișăm calea până la directorul în care ne aflăm folosind comanda ``pwd`` [#]_ :
Așa l-am pus inițial dar l-am schimbat la review-ul Lizei. Cerem părerea celorlalți

2020-10-12 03:52 UTC, CostinCarabas commented on chapters/files/files.rst
> +* legături (linkuri);
Am schimbat în ``În această secțiune vom vorbi despre cum facem următoarele din linia de comandă``.
Cum ți se pare?

2020-10-12 03:53 UTC, CostinCarabas commented on chapters/files/files.rst
> +    drwxr-xr-x 2 student student 4096 Sep 29 19:21 GameOfThrones
Sunt în directoare diferite. Aș putea să le leg dar să pun un ``cd`` între ele. Le-aș lăsa așa.

2020-10-12 04:06 UTC, CostinCarabas commented on chapters/files/files.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Pun pe listă. Discutăm la ședință

2020-10-12 04:14 UTC, CostinCarabas commented on chapters/files/files.rst
> +-------------------
La același lucru mă gândeam și eu.
@lizababu ?

2020-10-12 04:17 UTC, CostinCarabas commented on chapters/files/files.rst
>  * Legături strânse (hard links)
La început așa am convenit. Trec pe lista de discutat la ședință.

2020-10-12 04:26 UTC, CostinCarabas commented on chapters/files/io_redirection.rst
> +Dacă voiam să salvăm outputul undeva (*de obicei într-un fișier*) trebuia să copiem outputul, să creăm un fișier nou sau să folosim unul deja existent, să îl deschidem, să lipim textul în el și să sa
Find e prea specific pentru ei. Până în punctul ăsta nu știu cât l-au folosit.
Aș vrea să rămân generic: poate unii se gândesc la un ``cat`` la un fișier, alții la ``tree`` sau ``ls -l``. Cu comenzile astea sunt obișnuiți ei.

2020-10-12 04:32 UTC, CostinCarabas commented on chapters/files/io_redirection.rst
> +    USO RL EGC lista_materii
A fost populat la exercițiul anterior cu:
``    -rw-r--r-- 1 student student 5.0M Aug 19 11:55 USO
    -rw-r--r-- 1 student student 3.0M Aug 19 11:55 RL
    -rw-r--r-- 1 student student 1.0M Aug 19 11:55 EGC``

2020-10-12 04:51 UTC, CostinCarabas commented on chapters/files/archive.rst
> +Avem situații când vrem să extragem conținutul arhivei la o anumită destinație.
Da, pare redundantă propoziția, dar cred că este util pentru ei să aibă puțin context înainte să intre în pâine.
@lizababu , ce zici?

2020-10-12 04:56 UTC, CostinCarabas commented on chapters/files/archive.rst
> +Există cazuri în care vrem să adăugăm un nou fișier la o arhivă există.
De acord. Aici e redundant pentru că e la începutul secțiunii, dar mai sus este în mijlocul secțiunii.

2020-10-12 04:59 UTC, CostinCarabas commented on chapters/files/archive.rst
> +Folosim utilitarul ``zip`` împreună cu parametrii potriviți:
Am uitat să o scot 🤦

2020-10-12 05:21 UTC, CostinCarabas commented on chapters/files/file_system.rst
> +Afișarea căii curente
Renunț doar la ``afișarea căii curente`` sau și la ``schimbarea căii curente``?
@lizababu , ce zici?

2020-10-12 05:23 UTC, CostinCarabas commented on chapters/files/file_system.rst
> +Spre exemplu, serviciul ``ssh`` folosește un fișier de configurare numit ``/etc/ssh/ssh_config``, dar nu mai ținem minte calea exactă până la acel fișier.
Păi și cum cauți o poză în sistemul de fișiere?

2020-10-12 05:42 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-12 06:52 UTC, CostinCarabas commented on chapters/files/io_redirection.rst
> +^^^^^^^^^^^^^^^^^^^^^^^
mutat într-o altă secțiune

2020-10-12 06:55 UTC, CostinCarabas commented on chapters/files/archive.rst
> +Avem situații când vrem să extragem conținutul arhivei la o anumită destinație.
Mutat într-o alta subsecțiune și șters fraza

2020-10-12 07:00 UTC, CostinCarabas commented on chapters/files/files.rst
> +-------------------
de pus subsecțiunea la începutul secțiunii

2020-10-12 17:54 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-12 17:59 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-12 19:17 UTC, razvand requested changes
Am recenzat secțiunea "Căi în ierarhia de fișiere". Arată bine, unele lucruri sunt prezentate o idee cam expeditiv. De avut în vedere că oamenii sunt începători și trebuie luați ușor.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Atunci când vrem să citim, scriem, ștergem un fișier sau director trebuie să ne referim la acel fișier sau director.
Mai zi. Practic, **orice operație în sistemul de fișiere (arhivare, criptare, ștergere, editare) folosește căi**. Este impropriu să spunem "deschide fișierul /home/student/a.txt"; tehnic corect este "deschide fișierul de la calea /home/student/a.txt."

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Spre exemplu, luăm un serial pe Netflix. Ne referim la un episod în două moduri:
Foarte mișto analogie. Bine, mă!

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +După cum am specificat mai sus, calea absolută începe întotdeauna cu caracterul ``/`` (slash), denumit și *root*.
specificat e un cuvânt robotic, ingiresc. E pentru specificații, nu pentru vorbit. Spune "După cum am spus mai sus" sau "După cum am precizat mai sus.

Nu root, directorul rădăcină.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Acesta specifică începutul ierarhiei de fișiere.
s/specifică/indică

... fișiere, rădăcina acestuia.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Observăm că la începutul căilor este întotdeauna caracterul **/** (root), directorul de început al ierarhiei de fișiere.
Spune, foarte pe scurt, ce face opțiunea `-l` a comenzii `ls`.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Observăm că ne aflăm la calea ``/home/student`` și urcăm spre vârful ierarhiei de fișiere folosind caracterele ``..``.
Nu, nu și nu. E prea mult `..` în acest punct.

Fă cale relativă în "jos". Adică sunt în /home/student dacă dau ls uso/curs-01/ văd cursul 1 de USO. La fel aș obtine și cu ls /home/student/uso/curs-01.

Și aici spui care e avantajul căilor relative și a celor absolute.

Apoi faci o subsecțiunea cu Intrarea .. în sistemul de fișiere.

Pune o notă să o refere ca punct punct (dot dot) nu ca două puncte ca să nu se confunde cu :

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Odată ajunși la *root* ``/``, coborâm spre fișierul ``touch``, trecând prin directoarele ``usr`` și ``bin``.
Fără roog.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +* Referiți fișirele ``/usr/bin/sudo``, ``/bin/cat``, ``/etc/passwd``, ``/dev/urandom`` atât prin cale relativă cât și prin cale absolută.
E prea mult. Spune-le întâi să afișeze unde se află (cu pwd). Repetițio mater studiorum. Apoi spune-le să afișeze directorul Downloads, /etc/ și chestii simple.

Apoi intră în căi relative și absolute. E prea brusc să le dai aceste exerciții fără niște repetiții mai simple de comenzi înainte.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +* Referiți directorul părite al directorului părinte (două niveluri mai sus față de cel curent) atât prin cale relativă cât și prin cale absolută.
părinte

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Facem acest lucru folosind comanda ``cd`` (Change Directory):
italic, litere mici: change directory

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +    Comanda ``cd`` schimbă promptul terminalului; aceasta este o indicație a directorului curent în care ne aflăm:
În general, comanda `cd` schimbă ...

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +    Comanda ``cd`` primeste ca parametru o cale care poate fi atât *relativă* cât și *absolută*.
La fel ca toate comenzile de lucru cu sistemul de fișiere, comanda `cd` primește ca parametru o cale. Calea poate fi ..

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +    Comanda ``cd`` primeste ca parametru o cale care poate fi atât *relativă* cât și *absolută*.
primește (diacritică)

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +
Explică ce ai făcut mai sus, că prima comandă cd a făcut ceva, a doua altceva.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +    /usr/bin
Pune un tag `important`. Una dintre cele mai importate informații când lucrăm în sistemul de operare (în special în linia de comandă) este unde ne aflăm. Dacă știm unde ne aflăm, ne putem orienta către destinație. Știm unde ne aflăm folosind comanda pwd; ne deplasăm în altă parte folosind comanda cd.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Observăm cum am urcat în ierarhie folosind ``..`` până la ``/`` (*root*) iar apoi am coborât spre ``usr`` și apoi ``bin``.
root -> directorul rădăcină

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +.. note::
Pune footnote, nu este critic să fie notă.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Funcția de *tab completion* este probabil una dintre cele mai utile funcții expuse de către terminal.
terminal -> shell

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Prin simpla apăsare a tastei ``Tab`` în timp ce scriem numele unei comenzi, al unei opțiuni a unei comenzi sau calea către un director sau fișier, terminalul va completa în mod automat textul sau va
shellul, nu terminalul

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Observăm că atunci când calea pe care o scriem se termină cu */* (slash), apăsând de 2 ori pe tasta ``Tab`` ne arată fișiere și directoarele din calea respectivă.
fișierele

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Observăm că dacă folosim repetat comanda ``cd -`` vom face un joc *dute-vino* (*ping-pong*) între 2 directoare.
du-te vino

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +Observăm că dacă folosim repetat comanda ``cd -`` vom face un joc *dute-vino* (*ping-pong*) între 2 directoare.
, dacă ..., vom face

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +* Folosim caracterul (``~``) pentru a referi *calea home* a utilizatorului.
directorul home, sună ciudat calea home

Și să folosim termenul directorul home de acum încolo.

2020-10-12 19:17 UTC, razvand commented on chapters/files/paths.rst
> +.. note::
Nu văd relevantă nota asta. Spune că atunci când suntem în directorul home, promptul conține caracterul ~ pentru a indica acest lucru.

2020-10-12 20:27 UTC, razvand requested changes
Am recenzat secțiunea "Interacțiunea cu fișiere în linia de comandă". E mare, are multe noțiuni. Cred că aici se va încheia laboratorul. E mai mult decât suficient. Unele lucruri trebuie detaliate; și aduse clarificări exemplelor. Și trebuie mai multe exerciții când sunt exerciții. Repetitio mater studiorum.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
>  Etimologia comenzii provine din engleză - *Remove Directory*.
litere mici

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +    drwxr-xr-x 2 student student 4096 Sep 29 17:44 Game of Thrones
Explică ce ai făcut mai sus.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Pentru a șterge un director gol, folosim utilitarul ``rm`` cu opțiunile de recursivitate ``-r``: ``rm -r``.
care **nu** este gol

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Pentru a șterge un director gol, folosim utilitarul ``rm`` cu opțiunile de recursivitate ``-r``: ``rm -r``.
opțiunea

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Pentru a șterge un director gol, folosim utilitarul ``rm`` cu opțiunile de recursivitate ``-r``: ``rm -r``.
detaliază ce înseamnă recursivitate: parcurgerea în adâncime a întregii ierarhii. Spune că multe comenzi au astfel de opțiuni de recursivitate, pentru realizarea unei operații în mod recursiv (ls -R, zip -r, chmod -R, chown -R).

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +    După executarea comenzii, verificăm corectitudinea operației.
Clarifică asta. Spune de ce, cum.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Mutăm înapoi directorul ``GameOfThrones`` (cu tot conținutul acestuia) folosind cale relativă pentru a specifica directorul și cale absoluta pentru a specifica locația unde vrem să ajungă directorul
cale relativă, pentru a specifica directorul, și cale absolută, pentru ...

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Mutăm înapoi directorul ``GameOfThrones`` (cu tot conținutul acestuia) folosind cale relativă pentru a specifica directorul și cale absoluta pentru a specifica locația unde vrem să ajungă directorul
spune loc, nu locație

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Am verificat că directorul ``GameOfThrones`` se află la calea specificată (calea curentă).
s/specificată/indicată

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +    Observăm că putem folosi atât căi relative cât și căi absolute.
Zi complet fraza: "ca argumente pentru comanda mv de mutare / redenumire de fișiere și directoare."

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +* Mutați directorul înapoi la locatia inițială folosind atât căi relative cât și căi absolute.
Fă un exercițiu mai complet aici. Creare, afișare, mutare. Și apoi încă unul la fel. Și apoi încă unul pentru cei care mai au timp. Repetitio mater studiorum.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Copiem fișierul ``Thor`` din directorul ``Avengers`` în calea curentă *(.)* folosind ``cp``:
E prima oară când spui de . (punct, dot). Nu spune acum. Foloseste cp, dă niște exerciții, abia mai apoi spune de dot.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Copeim fișierul ``Thor`` din calea curentă în directorul ``/tmp/`` folosind ``cp``:
Copiem

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +    -rw-r--r-- 1 student student    0 Sep 29 19:04 Thor
Explică ce ai făcut mai sus

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Pentru a copia în altă parte un director care nu este gol trebuie să folosim comanda ``cp -r``:
, trebuie

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Acesta se află acum în ambele locații.
s/locații/locuri

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Observăm două directoare noi ``.`` și ``..``.
Astea deja le-ai descris. Aici ar trebui doar clarificat ce era cu ele: iată că sunt directoare.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Observăm două directoare noi ``.`` și ``..``.
De fapt, referințe la directoare.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Directoul ``.`` face referire la directorul curent, iar ``..`` este o referință la directorul părinte.
Directorul

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Astfel, dacă vrem să vedem ce este în directorul părinte, verificăm cu ``ls -l``:
afișăm conținutul directorul părinte

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Observăm că acesta nu se vede la execuția ``ls -l``.
nu apare ...
Adaugă și "Dar apare la execuția `ls -al`."

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +* Creați un director cu numele **.LordOfTheRings**;
Aici trebuie să fie din nou exerciții de creare de ierarhii, de mutare, de ștergere, de afișare. Repetitio mater studiorum.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Afișarea informațiilor de tip metadata pentru un fișier
Out, out, out. Take it out!

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +.. important::
Pune foonote.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +.. note::
Asta pare redundantă. Cred că ai mai tot zis de ea.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +       │       └── seriale_vechi
Manele, nimic? @lizababu ?

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +   * Copiați întreaga ierarhie în calea ``/tmp``. Folosiți comanda ``cp``.
Dă-le hint de opțiunea de recursivitate.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +   * Ștergeți fișierul ``Favorite`` din Directorul Hulu. Confirmați ștergerea prin afișarea directorului părinte.
directorul `Hulu`. Literă mică, monotype.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
>  * Putem crea legături simbolice către directoare.
Cuvântul simbolică îi va băga în ceață. Zi doar legături pe moment.

2020-10-12 20:27 UTC, razvand commented on chapters/files/files.rst
> +Observăm că dacă am șters un fișier accesându-l prin legătura simbolică, s-a șters și la destinație.
Spune că există două tipuri de linkuri: simbolice șî hard (nu există ideea de soft, ăla e un barbarism). Și că vom clarifica altă dată aceste lucruri, fiind mai avansate.

2020-10-13 16:29 UTC, CostinCarabas commented on chapters/files/paths.rst
> +Ne mutăm la calea ``/usr/bin`` folosind comanda ``cd``:
Atunci outputul n-o să mai fie similar cu al lor.
Degeaba văd în tutorial așa, dacă pe mașina lor nu asta este convenția.

2020-10-13 18:28 UTC, CostinCarabas commented on chapters/files/files.rst
> +Dacă vrem să creăm un fișier cu numele ``orașe romania``, adică vrem ca numele fișierului să conțină caracterul *spațiu (space)*, folosim tot comanda ``touch`` ca în exemplul de mai jos:
Nu există mai târziu. De aici o să treacă la următorul lab.
Ei toată viața au folosit spații în denumire.
E important să le zicem asta

2020-10-13 18:36 UTC, razvand commented on chapters/files/paths.rst
> +Ne mutăm la calea ``/usr/bin`` folosind comanda ``cd``:
OK. Lasă așa.

2020-10-13 18:42 UTC, CostinCarabas commented on chapters/files/files.rst
> +Pentru a șterge un director gol, folosim utilitarul ``rm`` cu opțiunile de recursivitate ``-r``: ``rm -r``.
N-au timp de chown/chmod. Nu văd asta cu recursivitatea relevantă aici.

2020-10-13 18:45 UTC, razvand commented on chapters/files/files.rst
> +Pentru a șterge un director gol, folosim utilitarul ``rm`` cu opțiunile de recursivitate ``-r``: ``rm -r``.
Era o analogie / paralelă. Poți spune că e recursivitate și poți pune restul ca footnote.

2020-10-13 18:47 UTC, razvand commented on chapters/files/files.rst
> +Dacă vrem să creăm un fișier cu numele ``orașe romania``, adică vrem ca numele fișierului să conțină caracterul *spațiu (space)*, folosim tot comanda ``touch`` ca în exemplul de mai jos:
Mai târziu în laborator, nu în *alt* laborator. Întâi exemple, simple, nechinuite, fără spații, și exerciții fără spații. Apoi explicat că se folosesc și spații, și apoi exemple cu spații și exerciții cu spații. E prea dintr-o dată și comenzi și spații, când nu s-au acomodat bine cu comenzile.

2020-10-13 19:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-13 19:22 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-10-13 19:24 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2020-11-03 22:34 UTC, lizababu requested changes
Am recenzat. Arată bine, am lăsat chestii pe formă +  o chestie generală: peste tot ar fi bine să precizezi în ce director dai comenzile, dacă te-ai mutat într-un alt director, arată și în code-block asta, că sunt la început, nu se uită la prompt să vadă ce și cum

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +    cat: lista_materii: No such file or directory
arată și spune că te-au mutat la altă cale la partea asta că ei vor da comanda cat și n-o să le dea "no such file or directory" pentru că sunt încă în ~

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +
La fel, spune în ce director lucrezi

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Am vrut să afișăm conținutul fișierului *lista_materie*, însă acest fișier nu există.
monotype lista_materie

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Am primit informația *No such file or directory*, și aceasta este afișată *sub formă de eroare*.
sub formă de **eroare**

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +    Chiar dacă comanda de interes eșuează, direcționarea este făcută. În cazul de mai sus, fișierul ``materii`` este creat.
cacofonie; 
fix: Deși comanda ``cat`` eșuează, direcționarea este făcută. Fișierul materii a fost creat și este gol.

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Putem folosi sintaxa ``comanda > fișier_ieșire 2> fișier_erori`` pentru a face acest lucru..
ai un punct în plus la finalul propoziției

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Ca să redirectăm și outputul și erorile de la o comandă folosim și ``>`` și ``2>`` ca mai jos:
propoziția asta merge mai jos, unde foloseșt > și 2>

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +Tot comanda ``cat`` a încercat să afișeze conținutul fișierului ``SO2``, însă el nu există și a afișat eroarea ``Not such file or directory``.
s/Not/No

2020-11-03 22:34 UTC, lizababu commented on chapters/files/io_redirection.rst
> +În continuare am verificat conținutul acestor fișiere pentru a demonstra corectitudinea operației.
Secțiune de exerciții: redirectare simplă 2 exerciții (o dată cu fișier nou, o dată cu fișier existent), reidrectare anexare (ditto), redirectare erori (la fel), redirectare și erori și output (la fel)

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +Creăm o arhivă cu fișierele ``înregistrare_lab01.mov``, ``înregistrare_lab02.mov``, ``înregistrare_lab03.mov`` numită ``înregistrări.tar`` folosind utilitarul ``tar``:
iarăși: să spui în ce director sunt astea (support) + să le urci în directorul support (cred că mai bine treci de la înregistrările alea la ceva mai light :)) )

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +Avem cum în directorul curent arhiva ``înregistrări.tar``.
sper că n-avem cum în directorul curent =))
dar avem acum :D

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +Folosim opțiunea **f** pentru a specifica ce arhivă vrem să afișăm.
t și f cu monotype

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +* f: folosește arhiva dată ca parametru (în cazul de față, numele ei).
x, v, f cu monotype

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +După cum observăm în exemplu de mai sus, pentru a extrage fișierele către o anumită cale, folosim opțiunea *--directory* (- - d i r e c t o r y):
--directory cu monotype

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +În continuare am adăugat ``înregistrare_lab04.mov`` la arhivă.
folosind opțiunea `r`

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +* f: folosește arhiva dată ca parametru (în cazul de față, numele ei).
c, z, v, f cu monotype

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +Acțiunea de comprimare este compusă din doi pași: arhivare și reducerea dimensiunii (comprimare).
**arhivare** și **reducerea dimensiunii** (*comprimare*)

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +.. note::
fără note; să fie text normal

În continuare folosim utilitarul zip pentru arhivare și comprimare. Arhivarea este similară cu cea prezentată în subsecțiuena :ref:TODO, unde am folosit utilitarul tar

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +    student@uso:~$ ls -l inregistrari.*
fără *; ls -l inregistrari.tar inregistrari.zip

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +Facem arhivare și comprimare a ierarhiei de directoare ``/usr/bin`` si comparăm dimensiunea:
s/si/și

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +    Pentru o mai bună înțelegere a comenzii de creare a arhivelor inspectați manualul: ``man zip``.
, inspectați

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +Pentru a vizualiza arhiva **fără** dezarhivare folosim opțiunea **-sf** (prescurtare de la **show-files**).
-sf cu monotype

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +.. code-block:: bash
e cam mult code-block, poate merge spart în 2 sau chiar 3 bucăți

2020-11-03 22:34 UTC, lizababu commented on chapters/files/archive.rst
> +.. code-block:: bash
să zici de dinainte că folosești comanda unzip pentru dezarhivare

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Se poate întâmpla să vrem să aflăm dacă într-o ierarhie de fișiere găsim un anumit fișier și dacă există, vrem să aflăm unde se află.
și, dacă există, ..

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Spre exemplu, serviciul ``ssh`` folosește un fișier de configurare numit ``/etc/ssh/ssh_config``, dar nu mai ținem minte calea exactă până la acel fișier.
nu da aici toată calea, știm doar numele, nu și calea în punctul ăsta

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +.. note::
exemple despre ce
+ spune despre * că tot la Edi va fi detaliată

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +.. note::
și fără note, la fel ca mai jos

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Utilitarele sunt de fapt programe (executabile) care se află undeva în sistemul de fișiere.
**programe** (*executabile*)

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Afișăm valoarea **PATH** a sistemului folosind utilitarul ``echo``.
valoarea variabilei de mediu **PATH**, ca să le intre bine în minte ce e

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +Există cazuri când vrem să găsim locația exactă a unui utilitari: vrem să aflăm ce permisiuni are, cine îl deține sau ce dimensiune are.
s/utilitari/utilitar

2020-11-03 22:34 UTC, lizababu commented on chapters/files/file_system.rst
> +``Which`` folosește variabila de mediu **PATH** pentru a găsi utilitarul cerut și va afișa rezultatele în ordinea directoarelor din **PATH**.
s/Which/which

2020-11-07 23:03 UTC, Sergiu121 commented on chapters/files/file_editor.rst
> +Acesta are funcționalități de bază și este ușor de folosit.
Mi se pare că ar trebui să explici de ce este ușor de folosit.

2020-11-07 23:05 UTC, Sergiu121 commented on chapters/files/file_editor.rst
> +Atunci când ne conectăm remote la un server și nu avem interfață grafică, utilizarea unui editor în linie de comandă este necesară.
s/remote/la distanță/

2020-11-08 14:55 UTC, Sergiu121 requested changes
Mai sunt necesare niște schimbări minore

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +* v: afișează detalii despre operație (verbose);
Extract și verbose cu italic.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +Avem următorul scenariu: am descărcat scheletul de temă de la facultate, acesta se află în directorul ``~/Downloads``, iar noi vrem să o dezarhivăm în directorul ``~/facultate/uso/teme/``.
s/iar noi vrem să o dezarhivăm/iar noi vrem să îl dezarhivăm/

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +#. * Extrageți arhiva **net.tar** în directorul ``/tmp/``.
`net.tar` cu monotype

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +Există cazuri în care vrem să vedem conținutul unei arhive.
Dacă spui că există, spune și care este un caz.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +* Creați un fișier *UPB*; verificați operația afișând conținutul directorului părinte;
UPB cu monotype.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +Mai sus vedeam afișarea dimensiuni în format *human-readable* adică în MegaBytes (MegaOcteți).
MegaBytes ar trebui să fie italic, ca human-readable.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +Pentru a vizualiza arhiva **fără** dezarhivare folosim opțiunea **-sf** (prescurtare de la **show-files**).
Show-files cu italic.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +* Afișați conținutul arhivelor ``personal_data.zip`` și ``net.zip`` *fără* dezarhivare.
"Fără" să fie bold, nu italic.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +.. code-block:: bash
Și să explici ce ai făcut la fiecare pas.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +   * Dezarhivați *doar* fișierul oraș natal în directorul curent; verificați operația afișând conținutul directorului curent.
Doar ar trebui să fie bold, nu italic.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +* Creați un fișier **UPB** cu conținutul "Make UPB Great Again!";
UPB ar trebui să fie monotype, nu bold.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +* Verificați conținutul arhivei **personal_data.zip**;
personal_data.zip ar trebui să fie monotype, nu bold.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/archive.rst
> +* Adăugați fișierul **UPB** în arhivă;
UPB ar trebui să fie monotype, nu bold.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +Linux ne oferă 2 utilitare, ``locate`` și ``find``, care pot fi de ajutor în situația descrisă mai sus.
s/2/două/.
Am stabilit că folosim cuvinte atunci când sunt mai puțin de zece.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +Încercăm să căutăm fișierul **pwd** în sistemul de fișiere folosind ``locate``:
`pwd` să fie monotype.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +Afișăm valoarea **PATH** a sistemului folosind utilitarul ``echo``.
PATH să fie monotype. Ca mai jos.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +    Un utilitar poate fi la mai multe căi din PATH, dar va fi executat utilitarul din cea mai din stânga cale (prima, dacă nu a2a, etc.).
PATH să fie monotype.
s/a2a/a doua/

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +``Which`` folosește variabila de mediu **PATH** pentru a găsi utilitarul cerut și va afișa rezultatele în ordinea directoarelor din **PATH**.
PATH să fie monotype, ca mai sus.

2020-11-08 14:55 UTC, Sergiu121 commented on chapters/files/file_system.rst
> +  Astfel, la fiecare execuție a utilitarului ``ls``, se va afișa calea curentă.
Chiar vrem să facă asta în VM? Sună dureros si ireversibil. Mai bine să îl mute, sau ceva de genul ăsta.

2021-08-02 10:23 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2021-08-02 11:49 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2021-08-02 12:07 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/20/merge

2021-08-02 13:55 UTC, merged