Add admin tasks lab structure
systems-cs-pub-ro/uso-lab-book pull request #29
Opened 2020-12-28 14:14 UTC by Sergiu121

- [ ]  add content
- [ ]  add gifs
- [ ] add refs
- [ ] add docker infrastructure

2020-12-28 14:16 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-01-04 02:15 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-01-04 02:21 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-01-04 16:25 UTC, razvand requested changes
Am recenzat capitolul în formatul curent.

Arată bine pentru început, cred că e tot conținutul acolo. E cam mult pentru laborator, dar e carte, deci e în regulă. Vedem ce tăiem.

În opinia mea ordinea ar trebui să fie: întâi chestiuni non-administrative, comune, probabile, periodice, apoi chestiuni administrative, nișate, improbabil, "do once. works? awesome, leave it like that". Am adăugat observații acolo. Ca să fie cât mai util studenților, cât mai relevant pentru ei, cât mai USO-like, mai puțin admin-like.

Să pui, te rugăm, o propoziție pe linie. E greu de comentat altfel.

Să faci apoi câte un pull request per secțiune, că vom muri să comentăm un pull request mare.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Configurarea și administrarea serviciilor
Nu e OK secțiunea asta aici. Vine după conectare.

După conectare nu te apuci să administrezi servicii. Te apuci să-ți configurezi mediul de lucru, să instalezi ce ai nevoie, să-ți faci fișiere de configurare, .vimrc, .emacs, .tmux.conf, să faci persistent modul de conectare, să configurezi data etc.

Asta ar fi secțiunea asta: Configurarea stației la distanță

Apoi ar fi o secțiune: "Folosirea stației la distanță", cu scenarii frecvente de folosire (probabil bazate pe tmux), neadministrative.

Apoi aș face "Gestionarea spațiului de stocare partajat", că e de interes pentru un utilizator neprivilegiat

Apoi vine partea de cron, at ("Programarea rulării aplicațiilor").

Adică întâi acțiunile mai neprivilegiate, mai comune, mai probabile, mai periodice, apoi cele administrative, mai nișate, mai improbabile, mai "do once. work? awesome, leve it like that".

Apoi vin, în sfârșit "Configurarea și administrarea serviciilor", "Partea cu Docker", "Monitorizarea sistemului"

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +comenzi, cum ar fi `find` sau `ls` care rulează cât timp se execută comanda.
Spune de ce e nevoie de servicii, de ce nu se poate și fără.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Deoarece ne dorim să avem majoritatea timpului conectivitate la mașină, sau ne
Adică acest "de ce" trebuie mai sus. Vine prea la finalul paragrafului. Start with why.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Vrem să pornim diversele servicii din sistem care sunt instalate pe propria
De ce? Spui ce vrei, dar nu spui de ce vrei. Spune întâi nevoia, problema, scenariul, situația (de ce?). Apoi definește obiectivul (ce?) și soluția (cum?).

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Interfața oferite de toate distribuțiile moderne este systemd. Comanda folosită
oferită

Nu sunt chiar de acord cu fomularea, dar o vei ajusta mai târziu.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Vom verifica starea de funcționare a serviciului SSH, deoarece știu și au auzit
Pune o subsecțiune "Verificarea stării unui serviciu"

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +
Pune o secțiune "Configurarea unui serviciu" în care doar să amintești că fiecare serviciu are, în general, un fișier de configurare cu format specific. Probabil nu va fi nevoie de exerciții în secțiunea asta, va fi doar ceva "literar".

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-config.rst
> +să acceseze acest proxy din browser.
O altă idee potențial cool (nu e așa utilă - eu am avut nevoie de ea, dar a fost ceva particular, dar are coolness ridicat): configurarea [shellinabox](https://github.com/shellinabox/shellinabox)

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-install.rst
> +folosirii docker este că mediul oferit de Docker este unul izolat și efemer,
docker -> Docker

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/services-install.rst
> +mașinii, iar orice modificare asupra sistemului de fișiere din Docker nu se va
mașinii -> sistemului, că nu suntem

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/storage.rst
> +grafice, care nu pot rula mereu eficient de la distanță. Soluția la această
grafice -> grafic

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/storage.rst
> +o singură replică, ai șters un fișier și au dispărut toate replicile.
Pe lângă asta, dacă ai Internet slab, ai acces greu la fișiere (le vrei și local). Și, pe lângă asta, trebuie să ai SSH configurat, care poate necesita tunel etc.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/storage.rst
> +anterioară.
Cu dezavantajul că trebuie configurate. Și cu dezavantajul că acum informația este duplicată: dublu spațiu ocupat și pot apărea conflicte la modificări.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/storage.rst
> +
De spus și că, pentru cod sau fișiere text mai simple se poate folosi Git ca formă de duplicare, care vin și cu versionare. Și soluțiile de stocare online / cloud au versionare, dar în Git ai cel mai mult control.

Apoi de făcut un tabel cu SSHFS, online / cloud, Git și avantajele / dezavantajele fiecăreia.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/storage.rst
> +Dropbox este o soluție care se folosește de un server în internet care stochează
Internet

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/cron.rst
> +actualizarea regulată a pachetelor, crearea de copii de rezervă pentru fișierele
Nu recomand și nu vreau să recomandăm actualizarea pachetelor în mod neinteractiv și planificat. Shit happens. Scoate asta de acolo.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/cron.rst
> +Îi vom pune să își facă copii de rezervă fișierelor de configurare din /etc
Să fie copiate într-un director care aibă ca nume data curentă, ca să fie un fel de formă de versionare.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/cron.rst
> +într-un director partajat prin Dropbox.
Un exercițiu bun aici este să facă un script care să verifice că există tunelul SSH și, dacă nu există, să-l creeze.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/monitor.rst
> +Odată ce am început să rulă servicii pe sistem, vrem să vedem în ce parametri
Spune de ce-ul. Spune ce se poate întâmpla dacă nu: consum mare de resurse, spațiu ocupat, erori de funcționare netratate.

2021-01-04 16:25 UTC, razvand commented on chapters/task-admin/monitor.rst
> +
Cel mai util mi se pare să știe de utilitarele din suita [sysstat](https://github.com/sysstat/sysstat).

2021-01-04 19:28 UTC, Sergiu121 commented on chapters/task-admin/workstation.rst
> +Noi ca dezvoltatorii software sau administratorii de sisteme, avem nevoie de
Am pus disponibilitatea mai jos, o să sucesc argumentele. Pentru mine chiar este ceva important. Dacă aș avea puterea de procesare în laptop-ul meu compact, nu aș avea probleme de disponibilitate, că eu chiar am mereu acces la el. Tot aș avea un workstation, dar impetusul pentru a îmi lua unul ar fi semnificativ mai mic. Poate e doar de la mine.

2021-01-04 19:29 UTC, Sergiu121 commented on chapters/task-admin/workstation.rst
> +În mod obișnuit sistemele care oferă multă putere de procesare nu vin în pachete
Voiam să zic "form factor", dar nu mi-a venit (și încă nu îmi vine) cuvântul în română.

2021-01-04 19:36 UTC, Sergiu121 commented on chapters/task-admin/remote.rst
> +fi SSH fără să facem pași extra.
Voi face asta.

Problema la DNAT/port forwarding este că nu prea mai merge. Unde am mai testat, ISP-ul nu îți mai dă IP public pe ruter, treci prin 2 NAT-uri. Din acest motiv nu l-am adăugat. Să îl bag?

2021-01-04 19:45 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +Configurarea și administrarea serviciilor
După cum am discutat și pe teams, sunt de acord cu această rearanjare
* voi adăuga o secțiune "Folosirea stației la distanță", unde voi muta subsecțiunea cu tmux. Nu ți se pare cam scurt daca punem doar asta? Nu vreau să intru în vim/emacs. Nu mi se par relevante pentru majoritatea oamenilor. Poate un scenariu ar fi să descarce ceva ce ar dura mult să compileze și să se detașeze de la tmux?
* voi prelua orinea propusă de tine, cu excepția faptlui că în loc de cron voi pute secțiunea de servicii.

2021-01-04 19:46 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +să acceseze acest proxy din browser.
Nu știu cât de folositor e. Voi mai rumega.

2021-01-04 19:47 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
> +
Tabelul e pe TODO list. Voi adăuga un reminder despre Git.

2021-01-04 19:47 UTC, Sergiu121 commented on chapters/task-admin/cron.rst
> +actualizarea regulată a pachetelor, crearea de copii de rezervă pentru fișierele
Ai dreptate. Voi scoate.

2021-01-04 20:50 UTC, Sergiu121 commented on chapters/task-admin/remote.rst
> +Prima problemă cu care se vor confrunta este cum se vor conecta la mașina. De ce
Am adăugat o precizare în introducere despre VM-uri. E ok?

2021-01-04 21:00 UTC, Sergiu121 commented on chapters/task-admin/remote.rst
> +nu presupune înregistrarea unui cont pentru folosirea aplicației, dar asta vine
Era vorba de autentificarea, lipsa autentificării vine cu dezavantajul că nu poți conecta multe sisteme. Am modificat oricum.

2021-01-04 21:01 UTC, Sergiu121 commented on chapters/task-admin/remote.rst
> +Folosirea tmux
Am stabilit că mutăm toată bucata asta. Deci nu își mai are rost comentariul.

2021-01-04 21:46 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +Vrem să pornim diversele servicii din sistem care sunt instalate pe propria
Nu am răspuns deja la "de ce" mai sus?

2021-01-04 21:50 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +Interfața oferite de toate distribuțiile moderne este systemd. Comanda folosită
E mai bine?

2021-01-05 00:48 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-01-05 10:28 UTC, razvand commented on chapters/task-admin/workstation.rst
> +Noi ca dezvoltatorii software sau administratorii de sisteme, avem nevoie de
E un use case și e un argument. Dar nu cred că e primul, cred că e al doilea. Cred că primul este universalitatea accesului și disoponibilității. Al doilea e puterea de procesare.

2021-01-05 10:29 UTC, razvand commented on chapters/task-admin/workstation.rst
> +În mod obișnuit sistemele care oferă multă putere de procesare nu vin în pachete
"formă constructivă" folosim în cartea de curs în capitolul de hardware

2021-01-05 10:30 UTC, razvand commented on chapters/task-admin/remote.rst
> +Prima problemă cu care se vor confrunta este cum se vor conecta la mașina. De ce
Comentez din nou pe tot textul. Revin.

2021-01-05 10:30 UTC, razvand commented on chapters/task-admin/remote.rst
> +fi SSH fără să facem pași extra.
Eu zic că trebuie amintit. Nu insistat, nu detaliat, dar amintit.

2021-01-05 10:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Configurarea și administrarea serviciilor
În regulă.

Ideea e să își configureze mediul pentru folosirea stației. Poate să-și pună niște aliasuri de bash, să-și coloreze promptul something. Să instaleze niște pachete de bază. Sunt lucruri pe care le facem cam toți. Apoi sunt chestii punctuale, e adevărat. Asta e la configurare.

La folosire, da, în afară de tmux ca o chestie generală nu-mi vine altceva. Ceva de compilat remote / editat / prelucrat are sens. Nu cred că vom avea ceva universal aplicabil, așa că orice idee care are sens mi se pare OK.

2021-01-05 10:35 UTC, razvand commented on chapters/task-admin/services-config.rst
> +să acceseze acest proxy din browser.
Folositor nu e. Dar e cool și e serviciu configurat și e SSH / terminal în web. E ceva "wow".

2021-01-05 10:46 UTC, razvand requested changes
Am adăugat o recenzie nouă. Sunt observații de formă, în linii mari (consecvență, formatare, formulare) și unele idei.

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/workstation.rst
> +Noi ca dezvoltatorii software sau administratorii de sisteme, avem nevoie de multă putere de procesare pentru a ne realiza obiectivele.
E greșită gramatical asta, ai doi "i" la dezvoltatorii / administratorii. Îți făcusem o sugestie dar pare că s-a pierdut.

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/workstation.rst
> +Astfel, dacă vrem să lucrăm la o problemă care necesită multă putere de procesare, avem nevoie să fim în apropierea unui sistem care ne oferă multă putere de procesare, lucru care nu este mereu posib
sparge asta în 2, e prea lungă fraza

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/workstation.rst
> +În mod obișnuit, sistemele care oferă multă putere de procesare nu vin în pachete compacte, ci acestea sunt sub formă de calculatoare de timp stații de lucru (workstation), servere, sau laptopuri gre
enter după punct

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/usage.rst
> +Dacă avem o aplicație care rulează mult timp, cum ar fi un find, și coexiunea SSH se întrerupe, se va întrerupe și execuția comenzii find.
Nu mi se pare că find e un exemplu bun.

Aș pune: descărcarea unui fișier prin Bittorent (și ar fi și scenariu) - care durează mult timp.

Și apoi o sesiune interactivă: dezvoltarea unui program: editezi, ții sesiunea deschisă: ai un tab pentru editare, unul pentru compilare, unul pentru debugging. Te detașezi, te reatașezi.

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/storage.rst
> +Cu toate că noi vom rula aplicații pe serverul de la distanță, noi avem nevoie de acces la spațiul de stocare al acestuia, deoarece vrem ca într-un final să urmărim rezultatul procesării și eventual
E prea lungă fraza, de spart în două.

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/storage.rst
> +O altă nevoie pe care o avem, dacă suntem programatori este editarea codului la distanță, deoarece majoritatea programatorilor folosesc IDE-uri în mediu grafic, care nu pot rula mereu eficient de la
fără "dacă suntem programatori" (se presupune că suntem)

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/storage.rst
> +SSHFS nu este o soluție bună pentru a face backup fișierelor, deoarece existând o singură replică, ai șters un fișier și au dispărut toate replicile.Pe lângă asta, dacă ai Internet slab, ai acces gre
enter după punct

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/storage.rst
> +Avantajul aici este că aceste sisteme oferă suport pentru controlul versiunilor pentru a șterge modificarea anterioară. Cu dezavantajul că trebuie configurate. Și cu dezavantajul că acum informația e
enter după punct

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/services-install.rst
> +Instalarea aplicațiilor (serviciilor) folosind Docker
Nu ai peste tot o propoziție pe linie.

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/services-install.rst
> +Problema în momentul de față cu instalarea serviciilor este că acestea nu se instalează într-un mod simplu.
fără "în momentul de față"

Aș spune doar "Instalarea serviciilor nu este o operație ușoară."

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/services-install.rst
> +Un alt avantaj al folosirii Docker este că mediul oferit de Docker este unul izolat și efemer, adică o aplicație care rulează în Docker nu are acces în mod obișnuit la restul sistemului, iar orice mo
De spar în două

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Scopul serviciilor este să ruleze în continuu și să primească cereri de la aplicații client, cum ar fi un client `ssh` și să răspundă la aceste cereri.
client SSH

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Serviciile sunt aplicații care rulează în continuu pe stație, spre deosebire de comenzi, cum ar fi `find` sau `ls` care rulează cât timp se execută comanda.
Sintaxa RST e cu backtickuri duble.

2021-01-05 10:46 UTC, razvand commented on chapters/task-admin/monitor.rst
> +Monitorizarea sistemului
Nu ai pus o propoziție pe linie.

2021-01-05 10:58 UTC, Sergiu121 commented on chapters/task-admin/usage.rst
> +Dacă avem o aplicație care rulează mult timp, cum ar fi un find, și coexiunea SSH se întrerupe, se va întrerupe și execuția comenzii find.
Am lăsat-o așa ca să o mai rumeg eu. Nici mie nu mi se părea potrivit, dar asta mi-a venit pe moment

2021-01-05 10:59 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
> +O altă nevoie pe care o avem, dacă suntem programatori este editarea codului la distanță, deoarece majoritatea programatorilor folosesc IDE-uri în mediu grafic, care nu pot rula mereu eficient de la
De ce? Nu poate fi urmărit ghidul și de un administrator?

2021-01-05 11:22 UTC, Sergiu121 commented on chapters/task-admin/usage.rst
> +Dacă avem o aplicație care rulează mult timp, cum ar fi un find, și coexiunea SSH se întrerupe, se va întrerupe și execuția comenzii find.
Eu folosesc foarte mult screen/tmux pentru asta. Las foarte des operații de lungă durată peste seară într-un ecran detașat.

2021-01-05 12:52 UTC, razvand commented on chapters/task-admin/usage.rst
> +Dacă avem o aplicație care rulează mult timp, cum ar fi un find, și coexiunea SSH se întrerupe, se va întrerupe și execuția comenzii find.
De acord, acolo e exemplul cu bittorrent. Asta cu find e ceva cu care studenții se vor întâlni rar.

2021-01-05 12:53 UTC, razvand commented on chapters/task-admin/storage.rst
> +O altă nevoie pe care o avem, dacă suntem programatori este editarea codului la distanță, deoarece majoritatea programatorilor folosesc IDE-uri în mediu grafic, care nu pot rula mereu eficient de la
Administratorii din ziua de azi sunt și programatori. sysdevops

orice administrator cât de cât va lucra cu PHP, Python, Perl, Bash

2021-01-05 15:22 UTC, Sergiu121 commented on chapters/task-admin/cron.rst
> +într-un director partajat prin Dropbox.
Ăsta e genul de lucru pe care îl rezolvi cu un serviciu, nu cu cron.

2021-01-05 15:34 UTC, razvand commented on chapters/task-admin/cron.rst
> +într-un director partajat prin Dropbox.
Ai dreptate. Dar dacă nu ai permisiuni? Poate fi vorba să îți faci un systemd personal.

2021-01-06 00:52 UTC, Sergiu121 commented on chapters/task-admin/usage.rst
> +Dacă avem o aplicație care rulează mult timp, cum ar fi un find, și coexiunea SSH se întrerupe, se va întrerupe și execuția comenzii find.
Cât de des folosești bittorrent în CLI? E un use case, dar pentru mine este extraterestru.

2021-01-06 01:54 UTC, Sergiu121 commented on chapters/task-admin/cron.rst
> +într-un director partajat prin Dropbox.
Mi se pare cam tras de păr. Există deja soluție pentru asta:
https://computingforgeeks.com/how-to-run-systemd-service-without-root-sudo/

2021-01-06 02:05 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-01-08 14:53 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-01-08 15:22 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-11-11 16:02 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2021-11-11 16:21 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/29/merge

2023-09-11 14:23 UTC, merged