Add services config section of admin tasks lab
systems-cs-pub-ro/uso-lab-book pull request #35
Opened 2021-01-09 05:13 UTC by Sergiu121

2021-01-09 05:15 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/35/merge

2021-01-09 07:34 UTC, razvand requested changes
Am adăugat recenzie. Îmi place capitolul. Acoperă bine tot ce mi se pare relevant.

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
>  Deoarece ne dorim să avem majoritatea timpului conectivitate la mașină, sau ne dorim să avem acces la paginile web folosite, serverele care execută comenzi primite de la clienți rulează fără să se op
Fără spațiu la început de propoziție.

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
>  Deoarece ne dorim să avem majoritatea timpului conectivitate la mașină, sau ne dorim să avem acces la paginile web folosite, serverele care execută comenzi primite de la clienți rulează fără să se op
, serverele rulează fără oprire și servesc cereri venite de la clienți.
Un sever / serviciu este oprit explicit de utilizator prin comenzi specifice sau este oprit la oprirea sistemului.
Fără o intervenție explicită și fără oprirea sistemului, un serer / serviciu va rula nedefinit.

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
>  Vrem să pornim diversele servicii din sistem care sunt instalate pe propria stație pentru a ne conecta la sistem, pentru a găzdui site-uri web și altele.
Vrem să pornim și să configurăm servicii instalate în sistem, precum:
* TODO
* TODO
* TODO

(E mai curat așa)

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Mai sus am afișat starea serviciului SSH. Observăm că acesta este activ și putem urmări ce procese a generat și mesaje de diagnosticare pe care le afișează.
O propoziție pe rând

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Programul systemd se ocupă de pornirea, oprirea și gestionarea serviciilor folosite în sistem pe baza unor fișiere numite fișiere unitate.
``systemd``

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Fișierul care gestionează serviciul SSH este în ``/lib/systemd/system/ssh.service`` și putem să îl identificăm din rezultatul comenzii ``systemctl status``.
fără "în"
. (punct și linie nouă)
Îl putem identifica din rezultatul comenzii ...

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Atunci când un serviciu este instalat, acesta vine la pachet cu fișierul ``.service`` cu care acesta va fi gestionat de systemd, după cum putem vedea în rezultatul comenzii de mai jos.
jos: (două puncte)

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    student@uso:~$ sudo apt-get install ntp
fără `-get`

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    Serviciul ``ntp`` este folosit pentru sincronizarea ceasului cu surse precise de timp din internet.
internet -> Internet

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    Acesta este un serviciu important pentru buna funcționare a aplicațiilor în internet, deoarece atunci când o aplicație nu are timpul corect, comunicarea poate să nu funcționeze corect.
Internet

deoarece o configurare a timpului pentru o stație poate duce la o funcționare incorectă a acesteia în comunicare cu alte stații.

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +``netstat`` pentru a verifica dacă mai ascultă serverul SSH pe portul ``22``.
un singur rând

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Pornirea unei aplicații se face folosind comanda ``systemctl start`` în felul
s/unei aplicații/unui serviciu

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Pe parcursul rulării serviciilor pe un sistem ne vom dori să schimbăm configurația unui serviciu sau să adăugăm parametri de rulare în plus.
fără "ne"

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Majoritatea aplicațiilor citesc fișierele de configurare o singură dată, atunci când sunt lansate, deci orice modificare ulterioară a fișierelor de configurare nu va fi sesizată de serviciu.
lansate -> pornite (pentru consecvență)

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Acest lucru este dezactivat în mod predefinit de către serviciu din motive de securitate.
fără "către"

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Pentru a face asta, avem nevoie să reconfigurăm serviciul SSH.
asta -> acest lucru (fără țărănisme)

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Odată ce am adăugat opțiunea ``PermitRootLogin yes`` în fișierul de configurare al serviciului și am dat restart serviciului, am reușit să ne autentificăm ca utilizatorul ``root``.
am dat restart -> arm repornit

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Atunci când configurăm un sistem și vrem să definim servicii care rulează pe el, ne dorim ca serviciile să fie "setup and forget``, să nu fie necesar să le supraveghem și să le monitorizăm prea mult.
Ai pus ghilimele în loc de double backtick la setup and forget

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Acestea se pot găsi în mai multe locații:
s/locații/locuri

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +* /etc/default, unde sunt fișiere care permit modificarea opțiunilor de rulare a unei comenzi, ca și cum am adăuga noi opțiuni la rularea unei comenzi.
în directorul ``/etc/default/``

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +  Aceste fișiere sunt citite de systemd, înainte să pornească serviciul;
``systemd``

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +* /etc/<numele serviciului>, unde se află fișierele de configurare pentru multe servicii instalate.
în directorul ``/etc/<nume_serviciu>/`` sau fișierul ``/etc/nume_serviciu``

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +#) Configurați serviciul SSH astfel încât acesta să permită autentificarea ca utilizatorul ``root`` folosind numai autentificare bazată pe chei.
astfel încât acesta să permită -> pentru a permite

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    #) Realizați modificările necesare astfel încât acest serviciu să nu pornească la startup;
NU (cu majuscule sau cu bold)

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Noi vom găzdui propriul proxy care va trimite mesaje criptate prin SSH către o altă stație, de unde vor fi trimise mesaje în internet.
Noi vom găzdui -> "Ne propunem să găzduim ..."

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Noi vom găzdui propriul proxy care va trimite mesaje criptate prin SSH către o altă stație, de unde vor fi trimise mesaje în internet.
Internet

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Un serviciu în systemd se definește printr-un fișier de configurare în directorul ``/lib/systemd/system/libvirtd.service``.
``systemd``

2021-01-09 07:34 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    Pentru ca acest serviciu să funcționeze, este necesar să vă copiați cheia stației ``uso`` pe mașina ``fep.grid.pub.ro``.
fără "vă"

2021-01-09 18:15 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
>  Deoarece ne dorim să avem majoritatea timpului conectivitate la mașină, sau ne dorim să avem acces la paginile web folosite, serverele care execută comenzi primite de la clienți rulează fără să se op
Nu e spațiu la început de linie.

2021-01-09 21:13 UTC, razvand requested changes
Am adăugat recenzie, looking good.

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Scopul serviciilor este să ruleze în continuu și să primească cereri de la aplicații client, cum ar fi un client ``ssh`` și să răspundă la aceste cereri.
``ssh`` -> SSH

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Fără o intervenție explicită și fără oprirea sistemului, un serer / serviciu va rula nedefinit.
server

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Avem nevoie de o interfață unică, cu o sintaxă minimală, care ne poate permite să gestionăm serviciile pe sistem, cum le pornim, oprim și cum putem să generăm noi propriile servicii.
poate permite -> permită

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Atunci când instalăm o aplicație care rulează sub forma unui serviciu vom putea să îi verificăm starea folosind comanda ``systemctl status``.
, vom putea

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Atunci când un serviciu este instalat, acesta vine la pachet cu fișierul ``.service`` cu care acesta va fi gestionat de ``systemd``, după cum putem vedea în rezultatul comenzii de mai jos:
fișierul cu extensia ``.service``

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    Acesta este un serviciu important pentru buna funcționare a aplicațiilor în Internet, deoarece o configurare a timpului pentru o stație poate duce la o funcționare incorectă a acesteia în comunic
comunicarea

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Pe parcursul rulării serviciilor pe un sistem vom dori să schimbăm configurația unui serviciu sau să adăugăm parametri de rulare în plus.
, vom dori

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +.. code_block::
Aș sparge blocul în două: partea în care încerci și nu merge. Și partea în care adaugi opțiunea de configurare și merge.

Prima parte apare înaintea propoziției "Pentru a face acest lucru". A doua parte apare după.

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Dacă acesta conține șirul de caractere ``enabled``, atunci serviciul pornește la startup, iar dacă aceasta conține șirul ``disabled``, atunci serviciul nu va porni la startup.
Dacă acesta -> Dacă rezultatul

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +În majoritatea cazurilor, serviciile sunt configurate prin fișiere de configurarea.
configurare

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +* directorul ``/etc/nume_serviciu/`` sau fișierul ``/etc/nume_serviciu``, unde se află fișierele de configurare pentru multe servicii instalate.
directorul ..., unde se află fișierele de configurare, sau, direct, fișierul ...

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +  De exemplu, pentru configurarea serviciului NTP, există fișierul ``/etc/ntp.conf``.
Mai dă un exemplu cu un director, de exemplu ``/etc/apache2/``.

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    #) Dezactivați funcționalitatea bazată pe IPv6 a serviciului Hint: ``listen_ipv6``, ``listen``.
. **Hint**:

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +    #) Asigurați-vă că serviciul rulează. Acest serviciu ascultă pe portul ``21``.
O propoziție pe linie

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Atunci când vrem să ne conectăm la Internet printr-un proxy, avem nevoie ca proxy-ul să fie deschis în permanență și să fie gestionat, dacă este pierdută conexiunea cu proxy-ul.
Nu îmi e clară partea cu "dacă este pierdută conexiunea cu proxy-ul"

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Putem să facem asta folosind servicii ``systemd`` pe care să le gestionăm noi folosind suita de comenzi ``systemctl``.
asta -> acest lucru

2021-01-09 21:13 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Astfel vom putea trece peste anumite filtre pe locație.
pe locație -> care țin cont de poziția geografică

2021-01-10 11:42 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +Avem nevoie de o interfață unică, cu o sintaxă minimală, care ne poate permite să gestionăm serviciile pe sistem, cum le pornim, oprim și cum putem să generăm noi propriile servicii.
Voiai să zici doar permite?

2021-01-10 11:50 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +.. code_block::
L-am spart astfel:
* am lăsat partea cu pentru înainte
* am pus primul codeblock
* am explicat că nu merge
* am pus rezolvarea
* am explicat rezolvarea
Mi se pare că are sens să le explic mai întâi contextul

2021-01-10 12:11 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +  De exemplu, pentru configurarea serviciului NTP, există fișierul ``/etc/ntp.conf``.
Am dat ``/etc/ssh``

2021-01-10 12:14 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +Atunci când vrem să ne conectăm la Internet printr-un proxy, avem nevoie ca proxy-ul să fie deschis în permanență și să fie gestionat, dacă este pierdută conexiunea cu proxy-ul.
Dacă crapă conexiunea să repornească serviciul. Am clarificat.

2021-01-10 12:16 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/35/merge

2021-01-10 12:53 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Avem nevoie de o interfață unică, cu o sintaxă minimală, care ne poate permite să gestionăm serviciile pe sistem, cum le pornim, oprim și cum putem să generăm noi propriile servicii.
da, "permite"

2021-01-10 16:21 UTC, razvand requested changes
Am adăugat o nouă recenzie.

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Scopul serviciilor este să ruleze în continuu și să primească cereri de la aplicații client, cum ar fi un client SSH și să răspundă la aceste cereri.
SSH,

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Serviciile sunt aplicații care rulează în continuu pe stație, spre deosebire de comenzi, cum ar fi ``find`` sau ``ls`` care rulează cât timp se execută comanda.
``ls``,

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Avem nevoie de o interfață unică, cu o sintaxă minimală, care ne permite să gestionăm serviciile pe sistem, cum le pornim, oprim și cum putem să generăm noi propriile servicii.
fără "cum le pornim, oprim"

și care ne permite sa generăm noi propriile servicii.

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Observăm că acesta este activ și putem urmări ce procese a generat și mesaje de diagnosticare pe care le afișează.
și ce mesaje de diagnosticare afișează.

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Pentru a opri un serviciu vom folosi comanda ``systemctl stop`` în felul următor
următor:

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Pentru a face acest lucru, avem nevoie să reconfigurăm serviciul SSH.
Mutat mai jos propoziția asta, după code blockul din continuare.

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Un mod de a ne ușura lucrul cu serverul este pornirea serviciilor la bootup, ca să nu fie nevoie sa intervenim noi după secvența de pornire a sistemului, ca să le pornim de mână, folosind comanda ``s
folosește consecvent bootup sau startup

2021-01-10 16:21 UTC, razvand commented on chapters/task-admin/services-config.rst
> +Atunci când vrem să ne conectăm la Internet printr-un proxy, avem nevoie ca proxy-ul să fie deschis în permanență și să dacă conexiunea este întreruptă, aceasta să fie repornită.
și să redeschidă conexiunea în cazul în care aceasta este întreruptă.

2021-01-10 16:52 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/35/merge

2021-01-10 17:21 UTC, Sergiu121 commented on chapters/task-admin/services-config.rst
> +Un mod de a ne ușura lucrul cu serverul este pornirea serviciilor la bootup, ca să nu fie nevoie sa intervenim noi după secvența de pornire a sistemului, ca să le pornim de mână, folosind comanda ``s
Am zis să nu mă repet.

2021-01-10 17:23 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/35/merge

2022-09-16 09:53 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/35/merge

2023-08-27 16:31 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/35/merge

2024-02-29 10:22 UTC, merged