Fix issues #38
systems-cs-pub-ro/uso-lab-book pull request #59
Opened 2021-08-24 08:42 UTC by CostinCarabas

files: Formatting issues when building chapter #38

Signed-off-by: Costin Carabas <costin.carabas@gmail.com>

2021-08-24 08:43 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/59/merge

2021-08-29 18:47 UTC, lizababu approved these changes

2021-08-30 14:54 UTC, razvand requested changes
This warning still persists:
```
/home/razvan/school/uso/uso-lab-book.git/chapters/files/io_redirection.rst:199: WARNING: Title level inconsistent:

Exerciții
"""""""""
```

2021-09-27 11:29 UTC, CostinCarabas commented
@razvand , I don't have any compilation errors.

2023-08-25 14:40 UTC, merged