Aplicare Feedback pt Laboratorul 1 - Acomodare in mediul Linux
systems-cs-pub-ro/uso-lab-book pull request #64
Opened 2021-09-07 16:07 UTC by andreia-oca

Pentru acest laborator nu există feedback de la studenți.

Am aplicat feedbackul pe care l-au dat asistenții.

Modificările aduse sunt următoarele:
- Corectarea typo-urilor;
- Imbunătățirea câtorva fraze;
- Marcarea consecventâ a secțiunilor cu `Exerciții`;
- Mutarea unor secțiuni de warning din cheatsheet în textul laboratorului (cheatsheetul ar trebui sa fie cât mai light)

2021-10-03 08:42 UTC, lizababu requested changes

2021-10-03 08:42 UTC, lizababu commented on chapters/basic/apps.rst
> +În mod similar putem pornim alte aplicații care au iconuri.
s/pornim/porni

2021-10-03 08:42 UTC, lizababu commented on chapters/basic/apps.rst
> +>>>>>>> 88513da570298066b2ba6f7bac9328637ea75210
au rămas niște git conflict markers

2021-10-03 08:42 UTC, lizababu commented on chapters/basic/apps.rst
> +Cele două moduri pot fi:
Porniți fiecare aplicație în cele două moduri: 
* mod 1
* mod 2

2021-10-03 08:42 UTC, lizababu commented on chapters/basic/browser.rst
> +Putem porni browserul Firefox în mai multe moduri (așa cum am menționat în secțiunea :ref:`basic_start_stop_apps`):
:)) bun ochi

2021-10-03 08:42 UTC, lizababu commented on chapters/basic/cheatsheet.rst
> -
aș zice că warningurile astea sunt bune că mulți sunt obișnuiți cu Ctrl+c
ce părere ai?

2021-10-03 08:42 UTC, lizababu commented on chapters/basic/terminal.rst
> +
ah văd că le-ai mutat mai jos

2021-10-03 09:56 UTC, andreia-oca commented on chapters/basic/browser.rst
> +Putem porni browserul Firefox în mai multe moduri (așa cum am menționat în secțiunea :ref:`basic_start_stop_apps`):
Danke :D

2021-10-03 09:57 UTC, andreia-oca commented on chapters/basic/cheatsheet.rst
> -
Am mutat warningurile din cheatsheet în textul laboratorului. IMO, ar trebui ca cheatsheetul să fie cât mai lightweight.

2021-10-03 10:00 UTC, andreia-oca commented on chapters/basic/apps.rst
> +În mod similar putem pornim alte aplicații care au iconuri.
done

2021-10-03 10:00 UTC, andreia-oca commented on chapters/basic/apps.rst
> +>>>>>>> 88513da570298066b2ba6f7bac9328637ea75210
scuzele mele, i-am șters.

2021-10-03 10:00 UTC, andreia-oca commented on chapters/basic/apps.rst
> +Cele două moduri pot fi:
Am modificat

2021-10-03 10:02 UTC, andreia-oca commented on chapters/basic/terminal.rst
> +
dap, le-am pus aici ca să degrevez cheatsheetul de fraze lungi.

2022-09-16 13:42 UTC, lizababu approved these changes

2022-09-16 13:42 UTC, lizababu commented on chapters/basic/browser.rst
> +Putem opri browserul Firefox în mai multe moduri (așa cum am menționat în secțiunea :ref:`basic_stop_gui_app_icons`):
```suggestion
Putem opri browserul Firefox în mai multe moduri, așa cum am menționat în secțiunea :ref:`basic_stop_gui_app_icons`:
```

2022-09-18 10:09 UTC, merged