Beautiful changes
systems-cs-pub-ro/uso-lab-book pull request #69
Opened 2021-09-15 13:48 UTC by ClaudiuChelcea

2021-09-15 13:59 UTC, ClaudiuChelcea commented
![image](https://user-images.githubusercontent.com/74200190/133447463-d913e170-c782-4bde-b436-2ed36df6db5f.png)

2021-11-02 21:15 UTC, lizababu requested changes
Am lăsat ceva comentarii aici. Majoritatea se referă la lucruri care sunt <prea mult> pentru momentul acesta. Nu vrem ca în această carte să acoperim exhaustiv toate variantele, ci prezentăm una, să o înțeleagă pe asta, și când se vor lovi de o altă situație, vor învăța singuri cum să adapteze ceea ce știu la ceea ce trebuie în particular acolo.

La vreo 2-3 secțiuni am dat skip pentru că ele nu vor intra oricum în laborator și am zis să nu ne concentrăm pe asta acum, ne vom ocupa de ele ulterior, să nu ne mâncăm timpul acum :D 

Să te uiți cu atenție peste comentarii, unde e neclar, dai reply și vorbim acolo specific pe comentariu, schimbăm idei și opinii.

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-intro.rst
> +Ordinea argumentelor pentru gcc nu contează, astfel că ``gcc -o is-prime is-prime.c`` este echivalent cu ``gcc is-prime.c -o is-prime``, contând doar ca după opțiunea ``-o`` să urmeze numele executab
extra details, nu merită să încărcăm

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-intro.rst
> +Ce utilitar puteți folosi pentru a vedea dacă rezultatele sunt identice? Hint: diff / vimdiff.
diff pe 2 binare nu spune mare lucru, should dump it

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +Pentru aceasta trebuie să *recompilăm* fișierul/fișierele pe care le-am modificat și să creăm un nou executabil.
poți scrie direct fișierele

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +* De asemenea, putem să evităm compilarea unor fișiere pe care nu le-am modificat de la ultima compilare, astfel salvând mult timp.
fără "De asemenea"

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +În această carte vom folosi fișiere `Makefile <https://www.gnu.org/software/make/manual/make.html#Makefiles>`_ care fac disponibil utilitarul `Make <https://linux.die.net/man/1/make>`_ ca să automati
nu fișierele fac utilitarul disponibil

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +O *regulă* din fișierul Makefile este, de fapt, un nume asociat unui set de *comenzi*. Spunem că rulăm *regula* ``clean`` atunci când vrem să executăm *comanda* ``rm -rf *.o hangman``.
keeping it simple: e asociată unei comenzi, că pot fi mai multe e un detaliu extra

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +#. **Comandă**, care începe cu un ``Tab`` la începutul rândului, urmat de o comandă (``gcc -o hangman hangman.o``). Dacă sunt mai multe comenzi ce trebuiesc executate, *nu* inserăm mai multe taburi,
same here

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +Utilizând a doua formă, simplă, se va apela implicit prima regulă găsită din fișierul Makefile, în cazul nostru regula 'all'. Aceasta la rândul ei poate trimite către una sau mai multe reguli care să
``all`` (formatat)

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +    student@uso: ~/TODO$ ls
nu punem căile aici în prompt, încarcă prea mult

2021-11-02 21:15 UTC, lizababu commented on chapters/app-dev/make-simple-automation.rst
> +    student@uso: ~/TODO$ ls
e mai mult o convenție și așa trebuie să fie în toată cartea :D

2021-11-02 23:13 UTC, ClaudiuChelcea commented on chapters/app-dev/git-intro.rst
> +Un repository reprezintă o metodă de împărțire a proiectelor: poate fi o temă la o materie, poate conține chiar toate temele la o materie, în foldere diferite sau poate conține doar un simplu README.
Ok, las doar cu README.

Easter-egg-ul este ca, daca ai un repositoy gol, doar un readme (si eventual poze in el), va aparea pe profil direct ca un first-page.

Check this: 

- https://github.com/adriangeorge
- https://github.com/ClaudiuChelcea

2021-11-02 23:15 UTC, ClaudiuChelcea commented on chapters/app-dev/git-intro.rst
> +Un repository reprezintă o metodă de împărțire a proiectelor: poate fi o temă la o materie, poate conține chiar toate temele la o materie, în foldere diferite sau poate conține doar un simplu README.
Repository-ul trebuie sa aiba exact numele contului, in cazul tau "lizababu".

2021-11-02 23:32 UTC, ClaudiuChelcea commented on chapters/app-dev/make-simple-automation.rst
> +Utilizând a doua formă, simplă, se va apela implicit prima regulă găsită din fișierul Makefile, în cazul nostru regula 'all'. Aceasta la rândul ei poate trimite către una sau mai multe reguli care să
Nu prea inteleg comment-ul. Il formatez sau sterg aceasta parte? Si daca il formatez, cum, adica in ce  sens?

2023-08-25 14:46 UTC, lizababu approved these changes

2023-08-25 14:46 UTC, merged