Adaugă conținut pentru capitolul "Instalarea și utilizarea aplicațiilor"
systems-cs-pub-ro/uso-lab-book pull request #9
Opened 2020-08-08 10:57 UTC by razvand

Adaugă conținutul efectiv (activități: breviar, tutoriale, exerciții) pentru capitolul "Instalarea și utilizarea aplicațiilor".

2020-08-08 10:58 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-08-08 15:01 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-08-11 11:13 UTC, edi33416 commented on chapters/app-install/start.rst
> +1. Pornim, în terminal, aplicația grafică (**Firefox**) folosind comanda ``firefox``.
Poate să menționezi că acum aplicația rulează în **foreground** ?

2020-08-11 11:16 UTC, edi33416 commented on chapters/app-install/start.rst
> +În acest mod avem aplicația **Firefox** în rulare și avem acces la terminal să introducem noi comenzi.
Nu menționezi nimic de `jobs` și `fg [n]`. Eu sunt de părere că trebuie menționate. Eu unul le folosesc constant

2020-08-11 11:18 UTC, edi33416 commented on chapters/app-install/start.rst
> +În acest mod avem aplicația **Firefox** în rulare și avem acces la terminal să introducem noi comenzi.
Dă un `jobs` înainte și după comanda `bg` ca să vadă trecerea din starea **stopped** în starea **running**

2020-08-11 11:20 UTC, edi33416 commented on chapters/app-install/start.rst
> +Cel mai adesemea numim aplicațiile în linie de comandă **utilitare**.
Defapt cel mai adesea le numim pur și simplu **comenzi**

2020-08-11 11:21 UTC, edi33416 commented on chapters/app-install/start.rst
> +Interacțiunea lor cu utilizatorul se face prin intermediul terminalului: la terminal se introduc informații de la utilizator și tot la terminal se afișează rezultatele rulării aplicațiilor.
Mi se pare că sună mai bine "în terminal se introduc/afișează ..." vs "la terminal se introduc/afișează ..."

2020-08-11 11:24 UTC, edi33416 commented on chapters/app-install/start.rst
> +Se poate întâmpla ca o aplicație în linia de comandă să ruleze pentru prea mult sau să se blocheze.
să ruleze pentru prea mult timp

2020-08-11 11:25 UTC, edi33416 commented on chapters/app-install/start.rst
> +Acest lucru în facem folosind combinația de taste ``Ctrl+c`` care oprește aplicația care rulează în terminal.
s/în facem/îl facem

2020-08-11 11:27 UTC, edi33416 commented on chapters/app-install/start.rst
> +          Vom discuta despre semnale în :ref:`app_install_run_signal`.
În pagina de [preview](https://sergiu121.github.io/refs/pull/9/merge/chapters/app-install/start.html#d-oprirea-fortata-a-aplicatiilor-in-linia-de-comanda) văd că nu merge referința

2020-08-11 11:29 UTC, edi33416 commented on chapters/app-install/start.rst
> +* ``ls -R /usr``: pentru a afișa recursiv conținutul directorului ``/usr``
Lasă un newline între `forțat:` și bullet list. Acum nu este afișată lista

2020-08-11 11:32 UTC, edi33416 commented on chapters/app-install/start.rst
> +O aplicația grafică pornită din terminal va "acapara" terminalul și acesta nu va accepta alte comenzi.
s/aplicația/aplicație

2020-08-11 11:34 UTC, edi33416 commented on chapters/app-install/start.rst
> +Pentru acesta putem trece aplicația grafică în background, folosind combinația de taste ``Ctrl+z`` urmată de comanda ``bg``.
s/acesta/aceasta ?

2020-08-11 11:36 UTC, edi33416 commented on chapters/app-install/start.rst
> +O aplicația care rulează, adică folosește resursele sistemului pentru a executa cod și a prelucra date, se numește **proces**.
s/aplicația/aplicație

2020-08-11 11:39 UTC, edi33416 commented on chapters/app-install/start.rst
> +Vom afla mai multe despre folosirea ``ps`` și a altor aplicații de vizualizare a proceselor în :ref:`app_install_run`.
Nu merge referința

2020-08-11 11:40 UTC, edi33416 commented on chapters/app-install/start.rst
> +Aceste două faze vin în continuarea celor două faze prezentate în capitolul TODO:
`TODO:` ?

2020-08-11 11:43 UTC, edi33416 commented on chapters/app-install/start.rst
> +#. Faza rulării procesului se numește *running* sau *run-time*.
Poate ceva despre comanda `time`?

2020-08-11 11:49 UTC, edi33416 commented on chapters/app-install/start.rst
> +Atunci când lucrăm la distanță e posibil să nu avem facil acces la interfață grafică.
Mie îmi sună mai bine fără inversiunea "facil acces", adică scris "acces facil". Deasemeni, tind să cred că facil trebuie încadrat între `,`, dar nu mai știu atât de multă gramatică

2020-08-11 11:50 UTC, edi33416 commented on chapters/app-install/start.rst
> +Sau, chiar când lucrăm pe sistemul local, nu vrem să complicăm sau interfața cu o încă o aplicație care rulează cu interfața grafică.
Trebuie reformulat. Nu înțeleg ce ai vrut să spui, mai ales în ultima parte a frazei

2020-08-11 21:34 UTC, edi33416 commented on chapters/app-install/start.rst
>  -----------------------------------------
Ai uitat să modifici `-` în `^` pentru subsubsecțiune

2020-08-25 19:00 UTC, razvand commented on chapters/app-install/start.rst
> +În acest mod avem aplicația **Firefox** în rulare și avem acces la terminal să introducem noi comenzi.
În secțiunea următoare. De-aia am pus referința:
```
Vom afla mai multe despre background și suspendarea proceselor în :ref:`app_install_run_signal`.
```

2020-08-25 19:06 UTC, razvand commented on chapters/app-install/start.rst
> +Vom afla mai multe despre folosirea ``ps`` și a altor aplicații de vizualizare a proceselor în :ref:`app_install_run`.
Am rezolvat.

2020-08-25 19:09 UTC, razvand commented on chapters/app-install/start.rst
> +#. Faza rulării procesului se numește *running* sau *run-time*.
Nu, e prea mult.

2020-08-27 17:17 UTC, edi33416 requested changes
Am terminat de revizuit iterația asta

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +    La fel, comanda ``fg`` transmite un semnal numit
Ai mâncat semnalul, SIGCONT

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +Așa cum reiese de mai sus, procesul ``sleep`` rulează (``Running``) în **background**.
Fă explicită și observația că `&` pune procesul în background în starea running

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +    :alt: Utilitarul top
copy-pasta; trebuie actualizat textul alternativ

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +.. image:: img/background-foreground.svg
Posibil să fie rupere, dar n-ar fi bine să faci schema asta cu ditaa?

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +Comanda ``jobs`` are astfel rolul de a afișa toate procesele aflate în **background**, indiferent de starea lor (suspendate sau în rulare).
Adaugă și un exemplu care face `fg`, `bg`, `fg #n` și `bg #n`

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +Omorâți-le pe toate într-o singură comandă.
s/într-o/cu o/g ?

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +Porniți un proces ``sleep`` direct în **background** în rulare.
s/în rulare/în starea running/g

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +Proces nebun
s/nebun/abuziv/g

2020-08-27 17:17 UTC, edi33416 commented on chapters/app-install/run.rst
> +Procesele pot găsi în **background** (suspendate sau în rulare) sau în **foreground** (doar în rulare).
se pot găsi

2020-09-04 16:01 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-09-04 16:09 UTC, razvand commented on chapters/app-install/run.rst
> +#. Procesul ajunge la sfârșitul codului programului și își încheie execuția.
Cele care rulează în background sunt batch, nu este cazul aici.

2020-09-04 16:11 UTC, razvand commented on chapters/app-install/run.rst
> +Adică, amuzant spus, ``SIGKILL`` este o bombă nucleară, un glonț care trece prin vesta anti-glonț, cianură de potasiu.
Ce tre

2020-09-04 16:13 UTC, razvand commented on chapters/app-install/run.rst
> +Comanda ``jobs`` are astfel rolul de a afișa toate procesele aflate în **background**, indiferent de starea lor (suspendate sau în rulare).
Mi se pare prea mult. @Sergiu121 , tu ce zici?

2020-09-04 16:31 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-09-04 16:33 UTC, razvand commented on chapters/app-install/run.rst
> +.. image:: img/background-foreground.svg
Ba da, așa ar fi bine, dar aș lăsa asta pe mai târziu.

2020-09-04 16:35 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-09-05 17:20 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-09-08 16:19 UTC, edi33416 requested changes
Am revizuit ultima versiune

2020-09-08 16:19 UTC, edi33416 commented on chapters/app-install/config.rst
> +De exemplu, în cadrul interfeței browserul web Firefox putem modifica pagina de start sau putem activa anumite pluginuri sau putem personaliza dispunerea meniurilor sau fonturile folosite.
s/browserul/browserului/g

2020-09-08 16:19 UTC, edi33416 commented on chapters/app-install/config.rst
> +De exemplu utilitarele ``wget`` și ``curl``, clienți web, folosesc variabilele de mediu ``http_proxy`` și ``https_proxy`` pentru a folosi un proxy web.
Două cuvinte despre ce este un proxy web?

2020-09-08 16:19 UTC, edi33416 commented on chapters/app-install/config.rst
> +Atunci când folosește valoarea ``POSIX`` se afișează întâi intrările al căror nume începe cu literă mare.
Spune că modificarea variabilei, în modul ăsta, nu este persistentă

2020-09-08 16:19 UTC, edi33416 commented on index.rst
> -   chapters/app-install/update.rst
Este prea mult sau de ce ai șters-o?

2020-09-08 16:19 UTC, edi33416 commented on chapters/app-install/config.rst
> +
Spune-le că acum pot folosi numele de `fav` și pentru scp

2020-09-09 13:56 UTC, Sergiu121 commented on chapters/app-install/start.rst
> +Porniți aplicația Firefox și opriți-o în toate modurile de mai sus.
Să notezi cumva că ăsta e un exercițiu, așa cum am discutat în call.

2020-09-17 02:57 UTC, razvand commented on chapters/app-install/config.rst
> +Urmăriți conținutul fișierelor de configurare ``.gitconfig``, ``.vimrc``, ``.tmux.conf``.
E doar exemplu. Am adăugat precizare.

2020-09-17 03:21 UTC, razvand commented on index.rst
> -   chapters/app-install/update.rst
Am integrat conținutul în `install.rst`. Avea sens să fie acolo.

2020-09-17 03:28 UTC, razvand commented on chapters/app-install/config.rst
> +
Nu știu unde va fi capitolul și nu aș intra și în `scp`. Se vor prinde ei dacă este cazul. Pun referință la secțiunea din capitolul "Conectarea la Internet".

2020-09-17 03:42 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-09-17 13:57 UTC, Sergiu121 requested changes
Am facut review doar la start si run.

Mi se pare ca este prea mult continut. Se repeta prea multe lucruri si sunt explicate de doua ori lucruri cum ar fi rularea in foreground si backgroud. Stiu ca in principiu asta este o idee buna, dar duce la prea mult continut. Cum zicea si @edi33416 in call, ti se face sila cand vezi cat de mult text e.

Cred ca sunt lucruri care ar putea fi taiate. Sunt lucruri, cum ar fi diferitele moduri de afisare de la ps care nu sunt atat de relevante. Am inteles ca le-ai aratat cateva, dar e super mult si ti se ia de citit.

2020-09-17 13:57 UTC, Sergiu121 commented on chapters/app-install/run.rst
> +"""""""""""""""""""""""""
Nu mi se pare relevant sa stie cum afla identificatorul semnalelor. Sunt relevante doar SIGKILL si SIGTERM, in rest nu ne doare de unde vin celelalte, ca nu le folosim in viata de zi cu zi. Mai rau ii aburim si crestem volumul de informatie.

2020-09-17 13:57 UTC, Sergiu121 commented on chapters/app-install/run.rst
> +Comanda ``jobs`` are astfel rolul de a afișa toate procesele aflate în **background**, indiferent de starea lor (suspendate sau în rulare).
Mi se pare deja prea mult

2020-09-19 13:30 UTC, razvand commented on chapters/app-install/start.rst
> +    student@uso:~/uso-lab-book$ inkscape chapters/app-install/support/Tux.svg --export-pdf Tux.pdf
Este în repository, așteptarea mea este că cititorul va clona repository-ul și acolo va avea suportul. Asta va fi și la celelalte capitole care au fișiere de suport.

2020-09-19 14:26 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-09-23 13:25 UTC, Sergiu121 reviewed
Mi se pare ca ar trebui mutata sectiunea de instalarea aplicatiilor inainte de sectiune de configurarea aplicatiilor.

Sectiunile sunt mult mai digerabile decat primele doua. Informatia este la obiect.

2020-09-26 20:24 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-10-01 10:10 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-10-01 16:44 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2020-10-15 23:03 UTC, edi33416 requested changes
Am trecut prin tot. În mare parte am găsit typouri și am lăsat 2-3 întrebări.

2020-10-17 09:30 UTC, Sergiu121 requested changes
install:
Nu mi se pare ca se vad ok numerele liniilor.

2020-10-17 09:30 UTC, Sergiu121 commented on chapters/app-install/install.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aici de ce nu ai mai aratat si metoda GUI?

2020-10-17 09:30 UTC, Sergiu121 commented on chapters/app-install/install-non-standard.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nu ar trebui sa le arati intr-un paragraf cum se sterge aplicatia?

2020-10-19 20:17 UTC, razvand commented on chapters/app-install/install-non-standard.rst
> +^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
@Sergiu121 , nu înțeleg la ce te referi.

2020-10-19 20:26 UTC, razvand commented on chapters/app-install/start.rst
> +* ``dd if=/dev/zero of=/dev/null``: pentru a consuma timp de procesor (*busy waiting*)
Am scos-o, e mai safe.

2020-10-19 20:30 UTC, razvand commented on chapters/app-install/run.rst
> +La fel ca în cazul utilitarului ``less``, ieșirea din utilitarul ``top`` se realizează folosind tasta ``q`` [#top]_.
Nu, e prea mult. Și așa e prea mult.

2020-10-19 20:34 UTC, razvand commented on chapters/app-install/run.rst
> +**Exercițiu**: Identificați fișierul executabil al aplicațiilor / utilitarelor Shutter, Gedit, ``ls``, ``df``.
Acolo unde sunt nume de comenzi, sunt cu backticks. Acolo unde sunt nume de aplicații, sunt cu majusculă.

2020-10-19 20:45 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2021-08-06 19:10 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/9/merge

2021-08-06 19:11 UTC, merged